//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antd.sync.Strings {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChecksumFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChecksumFile() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("anthilla.sync.Strings.ChecksumFile", typeof(ChecksumFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End of stream occured while reading initial 4 bytes of signature file.
        /// </summary>
        internal static string EndofstreamBeforeSignatureError {
            get {
                return ResourceManager.GetString("EndofstreamBeforeSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End of stream occured while reading blocksize in signature file.
        /// </summary>
        internal static string EndofstreamInBlocksizeError {
            get {
                return ResourceManager.GetString("EndofstreamInBlocksizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End of stream occured while reading stronglen in signature file.
        /// </summary>
        internal static string EndofstreamInStronglenError {
            get {
                return ResourceManager.GetString("EndofstreamInStronglenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End of stream occured while reading strong signature from signature file.
        /// </summary>
        internal static string EndofstreamInStrongSignatureError {
            get {
                return ResourceManager.GetString("EndofstreamInStrongSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blocklen in signature file was: {0}, which does not seem correct.
        /// </summary>
        internal static string InvalidBlocksizeError {
            get {
                return ResourceManager.GetString("InvalidBlocksizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The size of the signature file is invalid.
        /// </summary>
        internal static string InvalidFilesizeError {
            get {
                return ResourceManager.GetString("InvalidFilesizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signature stream did not have the correct start marker.
        /// </summary>
        internal static string InvalidSignatureHeaderError {
            get {
                return ResourceManager.GetString("InvalidSignatureHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stronglen in signature file was: {0}, which does not seem correct.
        /// </summary>
        internal static string InvalidStrongsizeError {
            get {
                return ResourceManager.GetString("InvalidStrongsizeError", resourceCulture);
            }
        }
    }
}
