//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antd.sync.Strings {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeltaFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeltaFile() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("anthilla.sync.Strings.DeltaFile", typeof(DeltaFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End of stream occured while reading initial 4 bytes of delta file.
        /// </summary>
        internal static string EndofstreamBeforeSignatureError {
            get {
                return ResourceManager.GetString("EndofstreamBeforeSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stream ended but had no end marker.
        /// </summary>
        internal static string EndofstreamWithoutMarkerError {
            get {
                return ResourceManager.GetString("EndofstreamWithoutMarkerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Internal error, had buffered both matched and unmatched blocks!.
        /// </summary>
        internal static string InternalBufferError {
            get {
                return ResourceManager.GetString("InternalBufferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid length for copy data.
        /// </summary>
        internal static string InvalidCopyLengthError {
            get {
                return ResourceManager.GetString("InvalidCopyLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid offset for copy data.
        /// </summary>
        internal static string InvalidCopyOffsetError {
            get {
                return ResourceManager.GetString("InvalidCopyOffsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid size for literal data.
        /// </summary>
        internal static string InvalidLitteralSizeError {
            get {
                return ResourceManager.GetString("InvalidLitteralSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delta stream did not have the correct start marker.
        /// </summary>
        internal static string InvalidSignatureError {
            get {
                return ResourceManager.GetString("InvalidSignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unexpected end of stream detected.
        /// </summary>
        internal static string UnexpectedEndofstreamError {
            get {
                return ResourceManager.GetString("UnexpectedEndofstreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown command in delta file.
        /// </summary>
        internal static string UnknownCommandError {
            get {
                return ResourceManager.GetString("UnknownCommandError", resourceCulture);
            }
        }
    }
}
