#!/bin/bash
. /etc/kerbynet.conf
PPP="$1"
[ -z "$PPP" ] && exit 1
I=0
PID=`ps -ef |grep -w pppd |grep $PPP| awk '{print $2}'`
while [ -n "$PID" -a $I -lt 15 ] ; do
   kill $PID
   sleep 1
   I=$((I+1))
   PID=`ps -ef |grep -w pppd |grep $PPP| awk '{print $2}'`
done
if [ -n "$PID" ] ; then
   kill -9 $PID
   sleep 1
   rm -f /var/run/$PPP.pid
fi
PID=`ps -ef |grep -w 3Gconnect |grep $PPP| awk '{print $2}'`
I=0
while [ -n "$PID" -a $I -lt 5 ] ; do
   kill  $PID 2>/dev/null
   sleep 1
   I=$((I+1))
   PID=`ps -ef |grep -w 3Gconnect |grep $PPP| awk '{print $2}'`
done
if [ -n "$PID" ] ; then
   kill -9 `cat $PID` 2>/dev/null
   sleep 1
fi

