#!/bin/bash
. /etc/kerbynet.conf

killall -w acctd 2>/dev/null

CONFIG=$REGISTER/system/acct
rm -rf $CONFIG/requests/tmp/
mkdir $CONFIG/requests/tmp/
cd $CONFIG
if [ "`cat Enabled 2>/dev/null`" = yes ] ; then
  if [ "`cat $REGISTER/system/radius/Enabled 2>/dev/null`" != checked ] ; then
    echo checked > $REGISTER/system/radius/Enabled
    $SCRIPTS/radius_start 2>/dev/null >/dev/null
  fi
  $SCRIPTS/acctd 2>/dev/null >/dev/null &
fi
