#!/bin/bash
. /etc/kerbynet.conf
ID="$1"
USERNAME="$2"
MAC="$3"
INPUT_OCTETS="$4"
OUTPUT_OCTETS="$5"
INPUT_PACKETS="$6"
OUTPUT_PACKETS="$7"
SESSION_TIME="$8"
[ -z "$ID" ] && exit 2
[ -z "$USERNAME" ] && exit 3
MAC=`echo $MAC |sed 'y/:ABCDEF/-abcdef/'`
INPUT_GIGAWORDS=$(((INPUT_OCTETS&0xFFFFFFFF00000000)>>32))
INPUT_OCTETS=$((INPUT_OCTETS&0xFFFFFFFF))
OUTPUT_GIGAWORDS=$(((OUTPUT_OCTETS&0xFFFFFFFF00000000)>>32))
OUTPUT_OCTETS=$((OUTPUT_OCTETS&0xFFFFFFFF))
[ -z "$INPUT_PACKETS" ] && INPUT_PACKETS=0
[ -z "$OUTPUT_PACKETS" ] && OUTPUT_PACKETS=0
cat <<EOF | $SCRIPTS/acct_enqueue Interim-Update "$ID" "$USERNAME" 
Acct-Status-Type = Interim-Update
Acct-Session-Id = "$ID"
Acct-Multi-Session-Id = "$USERNAME"
User-Name = "$USERNAME"
Calling-Station-Id = "$MAC"
NAS-Identifier = "`hostname`"
Acct-Input-Octets = $INPUT_OCTETS
Acct-Input-Gigawords = $INPUT_GIGAWORDS
Acct-Input-Packets = $INPUT_PACKETS
Acct-Output-Octets = $OUTPUT_OCTETS
Acct-Output-Gigawords = $OUTPUT_GIGAWORDS
Acct-Output-Packets = $OUTPUT_PACKETS
Acct-Session-Time = $SESSION_TIME
EOF
