#!/bin/sh
. /etc/kerbynet.conf
FILTER="$1"
CONFIG=$REGISTER/system/acct/entries
DECIMALS=`cat $REGISTER/system/acct/Decimals`
cd $REGISTER/system/acct/entries 
ENTRIES=`ls -d *$FILTER*| sed 's/ /_--_/g'`
NUMCONN=0
for E in $ENTRIES ; do
  E=`echo "$E" |sed 's/_--_/ /g'`
  TIME=`cat "$E/Time" 2>/dev/null`
  [ -z "$TIME" ] && TIME=0
  TIME=`echo "$((TIME/60))" | awk '{printf "%2d:%02d",$0/60,$0%60}'`
  MB=`cat "$E/MB" 2>/dev/null`
  [ -z "$MB" ] && MB=0
  MB=`echo "$MB" |awk '{printf "%.2f",$1/1048576}'`
  COST=`cat "$E/Cost" 2>/dev/null`
  COST=`printf "%.${DECIMALS}f" $COST`
  CREDIT=`cat "$REGISTER/system/acct/credits/$E/Credit" 2>/dev/null`
  CREDIT=`printf "%.${DECIMALS}f" $CREDIT`
  LAST=`cat "$E/Last" 2>/dev/null`
  LAST=`date  --date="1970-01-01 $LAST sec GMT" +"%D %H:%M" 2>/dev/null` 
  echo "<tr align=center style='color: #404040;'><td><input type=radio name=CLT value='$E'></td><td class=Smaller1 nowrap><a href='#' onclick='OpenDetails(\"$E\")'>$E</a></td><td class=Smaller1 nowrap>$MB</td><td class=Smaller1 nowrap>$TIME</td><td class=Smaller1 nowrap>$COST</td><td class=Smaller1 nowrap>$CREDIT</td><td class=Smaller1 nowrap>&nbsp;$LAST&nbsp;</td></tr>"
  NUMCONN=$((NUMCONN+1))
done
echo "<script>parent.document.getElementById('NumConn').innerHTML=$NUMCONN;</script>"
