#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/acct
if ! [ -d $CONFIG/classes ] ; then
   mkdir -p $CONFIG/classes
fi
cd $CONFIG/classes
CURRENCY=`cat $REGISTER/system/acct/Currency`
DECIMALS=`cat $REGISTER/system/acct/Decimals`
FORMAT="%.${DECIMALS}f"
CLASSES=`ls -d *`
for C in $CLASSES ; do
  MB=`cat $C/MB`
  HOURS=`cat $C/Hours`
  MBITS=`cat $C/Mbits`
  COSTM=`cat $C/CostM`
  COSTH=`cat $C/CostH`
  [ -z "$MB" ] && MB="-"
  [ -z "$HOURS" ] && HOURS="-"
  [ -z "$MBITS" ] && MBITS="-"
  [ -z "$COSTM" ] && COSTM="0"
  [ -z "$COSTH" ] && COSTH="0"
  COSTM=`printf "$FORMAT" $COSTM`
  COSTH=`printf "$FORMAT" $COSTH`
  echo "<tr align=center style='color: #404040;'><td><input type=radio name=CLASS value=$C></td><td class=Smaller1 align=left>$C</td><td class=Smaller1>$MB</td><td class=Smaller1>$HOURS</td><td class=Smaller1>$MBITS</td><td class=Smaller1>$COSTM$CURRENCY</td><td class=Smaller1>$COSTH$CURRENCY</td></tr>"

done
