#!/bin/bash
. /etc/kerbynet.conf
tac $REGISTER/system/alerts/AlertLog| head -12
DIR="$REGISTER/system/alerts/"
ALERTSEQ=/tmp/AlertSeq
echo > $ALERTSEQ
cd "$DIR/Events"
EVENTS=`ls -drt * 2>/dev/null`
if [ -n "$EVENTS" ] ; then
  for E in $EVENTS ; do
    if [ "`cat $E/State/Status 2>/dev/null`" = ALERT ] ; then
      echo -n $E >> $ALERTSEQ
    fi
  done
fi
[ -f $ALERTSEQ.1 ] || touch $ALERTSEQ.1 
if ! diff $ALERTSEQ $ALERTSEQ.1 2>/dev/null >/dev/null ; then
  echo "<script>top.body.ListEvents()</script>"
  mv $ALERTSEQ $ALERTSEQ.1
fi
exit 0

