#!/bin/bash
. /etc/kerbynet.conf
EVENT="$1"
DIR="$REGISTER/system/alerts/Events/$EVENT"
[ -d "$DIR" ] || exit 1
[ -z "$EVENT_TS" ] && EVENT_TS="`date +%s`"
TIME=`echo $EVENT_TS |awk '{print strftime("%b %e %H:%M", $0);}'`
SEVERITY="`cat $DIR/Severity`"
SUBSYSTEM="`cat $DIR/Subsystem`"
DESCRIPTION="`cat $DIR/Description`"
STATUS="`$SCRIPTS/alerts_getstate $EVENT Status`"
echo -n "[$TIME] $STATUS:$SEVERITY:$SUBSYSTEM: $DESCRIPTION" >> $REGISTER/system/alerts/AlertLog
if ! [ -t 0 ] ; then
  echo -n ": " >> $REGISTER/system/alerts/AlertLog
  cat >> $REGISTER/system/alerts/AlertLog 
fi
if [ "`tail -c1 $REGISTER/system/alerts/AlertLog ; echo x`" != $'\nx' ]; then
    echo >> $REGISTER/system/alerts/AlertLog
fi

