#!/bin/sh
. /etc/kerbynet.conf
NAME="$1"
[ -z "$NAME" ] && exit 1
DESC="$2"
TYPE="$3"
RECIPIENT="$4"
SEVERITY="$5"
CDIR="$REGISTER/system/alerts/Recipients/$NAME"
if ! [ -d "$CDIR" ] ; then
  mkdir -p "$CDIR"
  echo yes > "$CDIR/Enabled"
fi
echo "$DESC" > "$CDIR/Description" 
echo "$TYPE" > "$CDIR/Type" 
echo "$RECIPIENT" > "$CDIR/Recipient" 
echo "$SEVERITY" > "$CDIR/Severity" 
