#!/bin/sh
. /etc/kerbynet.conf
EXCLUDE="$1"
DIR="$REGISTER/system/alerts/"
cd "$DIR/Events"
EVENTS=`ls -drt * 2>/dev/null`
if [ -n "$EVENTS" ] ; then
  for E in $EVENTS ; do
   if [ "$E" != "$EXCLUDE" ] ; then
     echo -n " $E "
   fi
  done
fi

