#!/bin/sh
. /etc/kerbynet.conf

if [ "`cat $REGISTER/system/alerts/EMAIL/SMTPEnabled 2>/dev/null`" = yes ] ; then
  echo "<font color=#00d000>ACTIVE</font>"
else
  echo "<font color=#ff4040>DOWN</font>"
fi
