#!/bin/bash
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/alerts
if [ ! -d $CONFIG ] ; then
  mkdir $CONFIG
  mkdir -p $CONFIG/SMS
  mkdir -p  $CONFIG/EMAIL
  mkdir -p  $CONFIG/Spooler/Queue
  echo 7200 > $CONFIG/Spooler/MaxAge
  echo 300 > $CONFIG/Spooler/Retry
  echo 50 > $CONFIG/SMS/SMSRateLimit
  mkdir $CONFIG/Recipients
  mkdir $CONFIG/Events
  IDENTITY=`cat $REGISTER/system/misc/hostname |awk -F. '{print $1}'`
  echo $IDENTITY > $CONFIG/Identity
  echo yes > $CONFIG/Enabled
  echo no > $CONFIG/SMS/SMSEnabled
  echo no > $CONFIG/EMAIL/SMTPEnabled
  echo smtp.gmail.com > $CONFIG/EMAIL/SMTPServer
  echo STARTTLS > $CONFIG/EMAIL/SMTPSecurity
  echo 587 > $CONFIG/EMAIL/SMTPPort
  echo "username@gmail.com" > $CONFIG/EMAIL/SMTPUsername
  echo "$IDENTITY <noreply@gmail.com>" > $CONFIG/EMAIL/SMTPSender 
    
  
   
  touch $CONFIG/AlertLog
  chown apache $CONFIG/AlertLog
  $SCRIPTS/alerts_mk_default_events
  $SCRIPTS/crontabgen 
fi
rm -rf $CONFIG/Events/*/State/*
killall -w spoolerd 2>/dev/null
if [ "`cat $CONFIG/Enabled 2>/dev/null`" = yes ] ; then
  $SCRIPTS/spoolerd 2>/dev/null >/dev/null &
fi



