#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
OP="$2"
WHAT="$3"
[ -z "$ID" ] && exit 1
[ -z "$OP" ] && exit 2
TYPE=`echo "$ID" |awk -F: '{print $2}'`
ID=`echo "$ID" |awk -F: '{print $1}'`
TREE=$REGISTER/system/AutoUpdate/pkgs/$ID/
if [ "$WHAT" = INSTALLER ] ; then
  if [ -d "$TREE/Cache/installer" ] ; then
     rm -rf $TREE/Cache/installer
     $SCRIPTS/autoupdate-logger "$ID" "$OP" "Installer cleanup process executed"
     echo
     echo "Installer cleanup process executed"
  fi
else
  rm -rf $TREE/pkg $TREE/Enabled 
  $SCRIPTS/autoupdate-logger "$ID" "$OP" "Package cleanup process executed"
  echo "Package cleanup process executed"
fi 





