#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
OP="$2"
FLAGS="$3"
[ -z "$ID" ] && exit 1
[ -z "$OP" ] && exit 2
TYPE=`echo "$ID" |awk -F: '{print $2}'`
ID=`echo "$ID" |awk -F: '{print $1}'`
export ERRORFILE=/tmp/installer-error-$ID
rm -f "$ERRORFILE"
if [ "$OP" = ABORT ] ; then
  killall -w autoupdate-installer-bg
  $SCRIPTS/autoupdate-cleanup "$ID:$TYPE" "$OP" >> "/tmp/installer-$ID"
  $SCRIPTS/autoupdate-error "$ID:$TYPE" "$OP" "Process aborted by user request" 
else
  $SCRIPTS/autoupdate-installer-bg "$ID:$TYPE" "$OP" "$FLAGS" > "/tmp/installer-$ID" 2>&1 &
  date +%s > /tmp/installer-elapsed-$ID

fi
