#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
CONFIG="$REGISTER/system/net/interfaces/"
cd $CONFIG
INTERFACES=`ls |sort -f`
for I in $INTERFACES ; do
  if ! [ -f $CONFIG/$I/Bond/Name -o -f $CONFIG/$I/Bridge/Name ] ; then
    VLAN_=""
    echo "<option value=$I>$I</option>"
    if cd $CONFIG/$I/VLAN 2>  /dev/null ; then
      VLANS=`ls`
      for VLAN_ in $VLANS ; do
         echo "<option value=$I.$VLAN_>$I vlan $VLAN_</option>"
      done
    fi
  fi
done
