#!/bin/sh
. /etc/kerbynet.conf
function TERM () {
  I=0
  ps -e |grep -w -q bandwidthd || return 0
  while [ $I -lt 30 ] ; do
    if ps -e |grep -w -q bandwidthd ; then
      killall -TERM  bandwidthd 2>/dev/null >/dev/null
    else 
       return 0
    fi
    I=$((I+1))
  done
  return 1
}
TERM
ENABLED="`cat $REGISTER/system/bandwidthd/Enabled 2>/dev/null`"
if [ "$ENABLED" == yes ] ; then
  $SCRIPTS/rendertemplate bandwidthd.conf
  bandwidthd
fi 
