#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES="`ls`"
for I in $INTERFACES ; do
   echo "<option value='$I'>$I</option>"
   if [ -d "$I/VLAN" ] ; then
       cd $I/VLAN
       VLANS=`ls`
       for V in $VLANS ; do
         echo "<option value='${I}.$V'>$I vlan $V</option>"
       done
       cd $CONFIG
   fi
done
