#!/bin/sh
source /etc/kerbynet.conf
c_rehash
[ -d $SSLDIR/certs/trusted_CAs ] || mkdir $SSLDIR/certs/trusted_CAs 
cd $SSLDIR/certs/trusted_CAs
ln -sf ../cacert.pem .cacert.pem
ln -sf ../crl.pem
c_rehash .
echo > $SSLDIR/trusted_CAs.pem
for T in `ls *.0` ; do
  cat "$T" >> $SSLDIR/trusted_CAs.pem
done

 
