#!/bin/bash
GRUB="$1"
[ -z "$GRUB" ] && exit 1
FILE="$GRUB/zeroshell.txt"
[ -f "$FILE" ] || exit 2
YEARDEV="$(awk '{print $2}'< /etc/release)"
YEARLAST="$(grep '(C) 2006-20' $FILE |sed -r 's/.*\(C\) 2006-(....) .*/\1/')"


if [ "$YEARDEV" -gt "$YEARLAST" ] 2>/dev/null ; then
  SUB="s/2006-$YEARLAST/2006-$YEARDEV/"
  sed "$SUB" < $FILE | sed 's/Z e r o S h e l l/Z E R O S H E L L/'> /tmp/zeroshell.txt
  mv /tmp/zeroshell.txt $FILE
fi
