#!/bin/bash
. /etc/kerbynet.conf
VPN="$1"
cd $REGISTER/system/net/interfaces/$VPN || exit
FAILURE=0
sleep 5
while true ; do
  if [ "`cat STATUS 2>/dev/null`" = up ] ; then
    if ! ps -ef |grep -w openvpn |grep -q -w $VPN ; then
      [ $FAILURE -lt 6 ] && FAILURE=$((FAILURE+1))
      logger -t "${VPN}_L2L" "Restarting OpenVPN process ..."
      $SCRIPTS/vpn_ctl $VPN 2>/dev/null >/dev/null
    else
      FAILURE=0
    fi
  else 
    exit
  fi
  if [ $FAILURE -gt 0 ] ; then
    DELAY=$((FAILURE*4))
  else
    DELAY=103
  fi
  sleep $DELAY
done
