#!/bin/sh
. /etc/kerbynet.conf
RESULT="$1"
CONFIG=$REGISTER/system/ClamAV/
if [ "$RESULT" == success ] ; then
  rm -f $CONFIG/WR/UpdateError  
  kill -1 `cat /tmp/havp.pid`
  date +"%b %e, %Y %X" > $CONFIG/WR/LastUpdate
  killall -9 -w clamav_resetdb 2>/dev/null
  $SCRIPTS/clamav_resetdb &
else
  touch $CONFIG/WR/UpdateError
fi


