#!/bin/sh
. /etc/kerbynet.conf
RESULT="$1"
CONFIG=$REGISTER/system/ClamAV/
if ! [ -f $CONFIG/WR/LastUpdate ] ; then
  echo "<font color=#F02020>Warning: Virus signatures not updated</font>" 
else
  if [ -f $CONFIG/WR/UpdateError  ] ; then
    echo "<font color=#F02020> Check Failed. Last update on `cat $CONFIG/WR/LastUpdate`</font>"
  else
    echo "<font color=#40b040>Last update on `cat $CONFIG/WR/LastUpdate`</font>" 
  fi
fi


