#!/bin/sh
. /etc/kerbynet.conf
IP="$1"
USER="$2"
[ -z "$IP" ] && exit 1
[ -z "$USER" ] || USERTXT=" ($USER)"
ACCT="`cat $REGISTER/system/acct/Enabled 2>/dev/null`"
CONFIG=$REGISTER/system/cp
CI=`cat $CONFIG/ClientIdentity 2>/dev/null`
SIMULTANEOUS=`cat $CONFIG/Simultaneous 2>/dev/null`
if [ "$CI" == IPMAC ] ; then
  MAC=`$SCRIPTS/cp_IP2MAC "$IP"`
  if ! echo "$MAC" | egrep -q "^..:..:..:..:..:..$" ; then
     logger -t "CaptivePortal" "GW: Warning: MAC address indentity required but the gateway is not able to know it for the client $IP$USERTXT" 
     $SCRIPTS/cp_msg SystemError >&2
     exit 10
  fi
fi
CONFIG=$REGISTER/system/cp/Connected
mkdir -p $REGISTER/system/cp/Connected 2>/dev/null
cd $REGISTER/system/cp/Connected
if [ -d "$IP" ] ; then
  CUSER=`cat $IP/User 2>/dev/null`
  CMAC=`cat $IP/MAC 2>/dev/null`
  logger -t "CaptivePortal" "GW: Warning: the client $IP is already connected (User: $CUSER MAC: $CMAC)"
  $SCRIPTS/cp_msg NoSimultaneous >&2
  exit 10
else
  if [ "$SIMULTANEOUS" == no ] ; then
    CLT=`grep -l -i -w "^$USER$" */User 2>/dev/null |tail -1| awk -F/ '{print $1}'`
    if [ -n "$CLT" ] ; then
      logger -t "CaptivePortal" "GW: Warning: the user $USER is already connected (IP:$CLT) and simultaneous connections are not allowed" 
      $SCRIPTS/cp_msg NoSimultaneous >&2
      exit 11
    fi
  fi
  mkdir "$IP"
  rm -rf "$REGISTER/system/cp/Disconnected/$IP"
  echo "$USER" > "$IP/User"
  echo "$MAC" > "$IP/MAC"
  UUID="`uuidgen`"
  echo "$UUID" > "$IP/UUID"
  echo 0 > "$IP/TX-Packets"
  echo 0 > "$IP/TX-Octets"
  echo 0 > "$IP/RX-Packets"
  echo 0 > "$IP/RX-Octets"
  NOW=`date +%s`
  echo "$NOW" > $IP/Started
  echo "$NOW" > $IP/Updated

  $SCRIPTS/cp_authorize_client yes $IP $MAC
  
  [ "$ACCT" = yes ] && $SCRIPTS/acct_enqueue_start "$UUID" "$USER" "$MAC" "$IP"
  logger -t "CaptivePortal" "GW: Success: user $USER (IP: $IP MAC: $MAC) connected"
fi
 
