#!/bin/sh
. /etc/kerbynet.conf
USERNAME="$1"
REALM="$2"
IP="$3"
USERNAME="$USERNAME@$REALM"
U="$REGISTER/system/cp/Connected/$IP/User"
if [ -r "$U" ] ; then
  UN=`cat "$U"`
  if [ "$UN" == "$USERNAME" ] ; then
    echo "C"
    exit 0
  fi
fi
echo "D"
 
