#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
MULTI=`cat $REGISTER/system/cp/Multi 2>/dev/null`
for I in $MULTI ; do
   V=`echo $I | awk -F. '{print $2}'`
   if [ -n "$V" ] ; then
     I=`echo $I | awk -F. '{print $1}'`
     echo "<option value='$I.$V'>$I vlan $V</option>"
   else
     echo "<option value='$I'>$I</option>"
   fi
done

