#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/cp
TIMEOUT=`cat "$CONFIG/Timeout" 2>/dev/null`
[ -z "$TIMEOUT"  ] && TIMEOUT=1
SLEEPTIME=$((TIMEOUT*13))
MINCHECK=$((TIMEOUT/2))
[ -d "/tmp/cp_outgoing_traffic" ] || mkdir -p "/tmp/cp_outgoing_traffic"
[ -d "$CONFIG/Connected" ] || mkdir -p "$CONFIG/Connected/"
MODE="`cat $CONFIG/Mode 2>/dev/null`"
INTERFACE="`cat $CONFIG/Interface 2>/dev/null`"
if [ "$MODE" = Bridged ] ; then
  VLAN=`echo $INTERFACE | awk -F. '{print $2}'`
  if [ -z "$VLAN" ] ; then   
    INTERFACE="`cat $REGISTER/system/net/interfaces/$INTERFACE/Bridge/Name 2>/dev/null`"
  else
    INTERFACE=`echo $INTERFACE | awk -F. '{print $2}` 
    INTERFACE="`cat $REGISTER/system/net/interfaces/$INTERFACE/VLAN/$VLAN/Bridge/Name 2>/dev/null`"
  fi
fi
[ -z "$INTERFACE" ] && exit 1
cd "$CONFIG/Connected"
while true; do
  find . -type f -name NoPopup -cmin +$MINCHECK -exec $SCRIPTS/cp_check_activity_wrapper "{}" "$INTERFACE" \;
  sleep $SLEEPTIME
done
