#!/bin/bash
. /etc/kerbynet.conf
if [ -d "$REGISTER/system/cp/Auth/Shibboleth/Release/" ] ; then
  cd "$REGISTER/system/cp/Auth/Shibboleth/Release/"
  echo '<table width=100% cellpadding=3 style="color: #404040">'
  for S in `ls` ; do
    R=`cat $S`
    echo "<tr><td width=30%>$S</td><td width=10%>:</td><td>$R</td></tr>"
  done
  echo "</table>"
else
  echo "<br><br>"
  echo "<font color=#f03030>&nbsp;&nbsp;&nbsp;&nbsp;Shibboleth SP has not been correctly installed</font>"
  echo "<br><br><br>"
fi
