#!/bin/bash
. /etc/kerbynet.conf
EXT="$1"
if [ -d "/etc/shibboleth" ] ; then
  cd "/etc/shibboleth"
  echo "<select name=Filename size=10 style='width: 100%' ondblclick='EditFile()'>"
  if [ -z "$EXT" ] ; then
    FILES=`ls`
  else
    FILES=`ls *$EXT`
  fi
  for F in $FILES ; do
    echo "<option value='/etc/shibboleth/$F'>$F</option>"
  done
  echo "</select>"
fi
