#!/bin/sh
. /etc/kerbynet.conf
LIST="$1"
cd "$REGISTER/system/cp/Auth/X509/CAs/" || exit 1
rm -f $REGISTER/system/cp/Auth/X509/CAs/*
for CA in $LIST ; do
  ln -s /etc/ssl/certs/trusted_CAs/${CA}.0 
  ln -s /etc/ssl/certs/trusted_CAs/${CA}.r0 
done
$SCRIPTS/cp_auth_start
