#!/bin/sh
. /etc/kerbynet.conf
DESC="$1"
IP="$2"
[ "$IP" == Any ] && IP=""
MAC="$3"
[ "$MAC" == Any ] && MAC=""
CONFIG=$REGISTER/system/cp
cd $CONFIG/FreeClients
LAST=`ls -d * 2>/dev/null |tail -1`
if [ -z "$LAST" ] ; then
  NEW=0000
else
  LAST=$(echo $LAST | sed 's/^0*//')
  [ -z "$LAST" ] && LAST=0
  NEW=$(printf "%04d" $((LAST+1)))
fi
mkdir $NEW
echo "$DESC" > $CONFIG/FreeClients/$NEW/Desc
echo "$IP" > $CONFIG/FreeClients/$NEW/IP
echo "$MAC" > $CONFIG/FreeClients/$NEW/MAC
$SCRIPTS/cpAddClientIPT "$IP" "$MAC"
