#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/cp
if ! [ -d $CONFIG/FreeClients ] ; then
   mkdir -p $CONFIG/FreeClients
fi
cd $CONFIG/FreeClients
CLIENTS=`ls -d *`
for C in $CLIENTS ; do
  Desc=`cat $C/Desc`
  IP=`cat $C/IP`
  [ -z "$IP" ] && IP=Any
  MAC=`cat $C/MAC`
  [ -z "$MAC" ] && MAC=Any
  echo "<tr align=center style='color: #404040;'><td><input type=radio name=CLT value=$C></td><td class=Smaller1 align=left>$Desc</td><td class=Smaller1>$IP</td><td class=Smaller1>$MAC</td></tr>"

done
