#!/bin/sh
. /etc/kerbynet.conf
IP="$1"
[ "$IP" == Any ] && IP=""
MAC="$2"
[ "$MAC" == Any ] && MAC=""
if ! [ -z "$IP" ] ; then
  SOURCE="-s $IP"
fi
if ! [ -z "$MAC" ] ; then
  SOURCE="$SOURCE -m mac --mac-source $MAC"
fi
iptables -D CapPortFC $SOURCE -j ACCEPT

iptables -t nat -D CapPortHTTP $SOURCE -j CapPortProxy 2>/dev/null
iptables -t nat -D CapPortHTTPS $SOURCE -j ACCEPT 2>/dev/null
iptables -t nat -D CapPortGW $SOURCE -j ACCEPT 2>/dev/null

