#!/bin/bash
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
. $SCRIPTS/readvalue
function DefaultNetmask {
  FIRST=`echo $1 | awk -F. '{print $1}'`
  if [ "$FIRST" -lt 128 ] ; then
     echo 255.0.0.0
  else
    if [ "$FIRST" -lt 192 ] ; then
       echo 255.255.0.0
    else
       echo 255.255.255.0
    fi
  fi
}
DEV="$1"
[ -z "$DEV" ] && exit 3
xDESC="DEFAULT PROFILE"
readvalue "Profile Description" "$xDESC" "" "" "" RejectNull
xDESC="$READVALUE"
xHOSTNAME="`hostname`"
readvalue "Hostname" "$xHOSTNAME" "" "" "" RejectNull
xHOSTNAME="$READVALUE"
xPW="zeroshell"
readvalue "Admin Password" "$xPW" "" "" "" RejectNull
xPW="$READVALUE"
xLDAPBASE="`cat $REGISTER/system/ldap/base`"
REPEAT=yes
until [ "$REPEAT" = no ] ; do
  readvalue "LDAP Base" "$xLDAPBASE" "" "" "" RejectNull
  xLDAPBASE="$READVALUE"
  
  if $SCRIPTS/createLDAPDB /tmp/ldapbasetest "$xLDAPBASE" "testpw" "$xHOSTNAME" TEST "192.168.0.75" 2>/dev/null ; then
    REPEAT=no
  else
    echo "The LDAP base is malformed"
  fi
done
xREALM="`cat $REGISTER/system/k5/realm`"
REPEAT=yes
until [ "$REPEAT" = no ] ; do
  readvalue "Kerberos 5 REALM" "$xREALM" "" up "" RejectNull
  xREALM="$READVALUE"
  if $SCRIPTS/checkk5realm "$xREALM" 2>/dev/null >/dev/null ; then
    REPEAT=no
  else
    echo "The Kerberos 5 REALM is malformed"
  fi
done
echo
H=0
ALLOW=""
INTERFACES="`( cd $REGISTER/system/net/interfaces && ls -d ETH?? )`"
for I in $INTERFACES ; do
  H=$((H+1))
  echo "  <$H>  $I - `cat $REGISTER/system/net/interfaces/$I/Description 2>/dev/null`"
  ALLOW="$ALLOW $I"
done
echo
xINTERFACE=1
readvalue "Management Interface" "$xINTERFACE" "`seq 1 $H`" num "$ALLOW"  RejectNull
xINTERFACE="$READVALUE"
xDEFAULTIP=""
for I in `seq 0 9` ; do
  xDEFAULTIP="`cat $REGISTER/system/net/interfaces/$xINTERFACE/IP/0$I/IP 2>/dev/null`"
  [ -n "$xDEFAULTIP" ] && break
done
xIP=""
while [ -z "$xIP" ] ; do
  readvalue "IP Address to assign to $xINTERFACE" "$xDEFAULTIP" "" "" "" RejectNull
  xIP=$READVALUE
  if ! IsValidIPAddr "$xIP" ; then
    echo "Invalid IP"
    xIP=""
  fi
done
if [ "$xIP" = "$xDEFAULTIP" ] ; then
  xDEFAULTNM="`cat $REGISTER/system/net/interfaces/$xINTERFACE/IP/0$I/Netmask 2>/dev/null`"
else
  xDEFAULTNM="`DefaultNetmask $xIP`"
fi
xNM=""
while [ -z "$xNM" ] ; do
  readvalue "Netmask" "$xDEFAULTNM" "" "" "" RejectNull
  xNM=$READVALUE
  if ipcalc -n "$xIP/$xNM" | grep -q INVALID ; then
      echo "Invalid Netmask"
      xNM=""
  fi
done
xDEFAULTGW="`$SCRIPTS/getdefaultgw |awk '{print $1}'`"
if [ -n "$xDEFAULTGW" ] ; then
  if [ "`ipcalc $xDEFAULTGW/$xNM 2>/dev/null |grep ^Network: | awk '{print $2}'`" != "`ipcalc $xIP/$xNM 2>/dev/null |grep ^Network: | awk '{print $2}'`" ] ; then
    xDEFAULTGW=""
  fi
fi
xGW=""
while [ -z "$xGW" ] ; do
  readvalue "Default Gateway" "$xDEFAULTGW"
  xGW=$READVALUE
  [ -z "$xGW" ] && break
  if [ "`ipcalc $xGW/$xNM 2>/dev/null |grep ^Network: | awk '{print $2}'`" != "`ipcalc $xIP/$xNM 2>/dev/null |grep ^Network: | awk '{print $2}'`" ] ; then
    echo "$xGW does not belong to the network `ipcalc $xIP/$xNM 2>/dev/null |grep ^Network: | awk '{print $2}'`"
    xGW=""
  fi
done
echo
echo -n "Creating the new Profile ... "
$SCRIPTS/makedb ${DEV} "$xDESC" New '' '' "$xHOSTNAME" "$xLDAPBASE" "$xREALM" "$xPW" "$xINTERFACE" "$xIP" "$xNM" "$xGW" 2>/dev/null >/dev/null
