#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
TAG="$2"
DESCRIPTION="$3"
[ -z "$INTERFACENAME" -o -z "$TAG" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
INTERFACE=`echo $INTERFACENAME |cut -d. -f1`
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
VLANDIR="$IDIR/VLAN/$TAG"
if [ -d "$VLANDIR" ] ; then
   echo "Interface $INTERFACE has already VLAN $TAG." 1>&2
   exit 3
fi
if [ "${INTERFACE:0:4}" == BOND -a "`getmac $INTERFACE`" == 000000000000 ] ; then
  echo $INTERFACE has not component interfaces or is down. 1>&2
  exit 10
fi 
if ! ip link show dev $INTERFACENAME | grep $INTERFACENAME | grep -q -w UP ; then
   DOWN=true
   ifconfig $INTERFACENAME up
fi
ERROR=`vconfig add $INTERFACENAME $TAG 2>&1`
if [ "$DOWN" == true ] ; then
   ifconfig $INTERFACENAME down
fi
$SCRIPTS/mrtg_reload
if echo $ERROR |grep -v -q -i error ; then 
  mkdir -p $VLANDIR 2>/dev/null
  echo $DESCRIPTION > $VLANDIR/Description
  ifconfig $INTERFACENAME.$TAG up 2>/dev/null
  echo up > $VLANDIR/STATUS
  if [ "${INTERFACENAME:0:6}" == BRIDGE ] ; then 
    setallbridgedinterface $INTERFACENAME
  fi
  if [ "${INTERFACENAME:0:4}" == BOND ] ; then 
    setallbondedinterface $INTERFACENAME
  fi
else
  echo $ERROR >&2
  exit 1
fi
