#!/bin/sh
. /etc/kerbynet.conf

if ! [ -d "$REGISTER/system/net/FW/ConnTrackLog/Filters/" ] ; then 
  mkdir -p "$REGISTER/system/net/FW/ConnTrackLog/Filters/"
fi
cd "$REGISTER/system/net/FW/ConnTrackLog/Filters/"
INCLUDE=""
EXCLUDE=""
for I in `seq 1 10` ; do
   if [ $I -lt 10 ] ; then
      F=0$I
   else
      F=$I
   fi 
   ENABLED="`cat $F/Enabled 2>/dev/null`"
   FILTERACTION="`cat $F/FilterAction 2>/dev/null`"
   REGEXPR="`cat $F/RegExpr 2>/dev/null`"
   if [ "$ENABLED" == yes -a -n "$REGEXPR" ] ; then
      if [ "$FILTERACTION" == Exclude ] ; then
         EXCLUDE="$EXCLUDE|$REGEXPR"
      else
         INCLUDE="$INCLUDE|$REGEXPR"
      fi
   fi
done
EXCLUDE="${EXCLUDE:1}"
INCLUDE="${INCLUDE:1}"
logger -t ConnTrack "Include filter: $INCLUDE"
logger -t ConnTrack "Exclude filter: $EXCLUDE"
if [ -z "$INCLUDE" -a -z "$EXCLUDE" ] ; then
  cat
else
  if [ -n "$INCLUDE" -a -n "$EXCLUDE" ] ; then
     egrep --line-buffered -w -i -e "$INCLUDE" | egrep --line-buffered -v -w -i -e "$EXCLUDE"
  else
    if [ -n "$INCLUDE" ] ; then     
      egrep --line-buffered -w -i -e "$INCLUDE"
    else
      egrep --line-buffered -v -w -i -e "$EXCLUDE"
    fi
  fi
fi

