#!/bin/sh
NAME="$1"
DEFAULTIP=192.168.0.75
DEFAULTPW=zeroshell
if ! [ -z "$NAME" ] ; then
  case "$NAME" in
     DEFAULTIP)
	echo "$DEFAULTIP"
        ;;
     DEFAULTPW)
	echo "$DEFAULTPW"
        ;;
  esac
fi

