#!/bin/sh
source /etc/kerbynet.conf
function  UMOUNT () {
  if [ "$ALREADYMOUNTED" == No ] ; then
     umount "$MP" && rmdir "$MP"
  fi
}
DEV="$1"
DB="$2"
[ -z "$DEV" -o -z "$DB" ] && exit 1
NODEV=${DEV:2}
LINE=`df -T -P | grep "$NODEV "`
if [ -z "$LINE" ] ; then 
   MP=/storage/`echo $DEV | sed -e "s/\//_/g"`;
   mkdir -p "$MP"
   mount -o rw "$DEV" "$MP" || exit 1
   ALREADYMOUNTED=No
else 
   MP=`echo $LINE | cut -f7 -d' '`
   mount -oremount,rw "$MP"
   ALREADYMOUNTED=Yes
fi
[ -z "$MP" ] && exit 1
rm -rf "$MP/$DB"
rm -f "$MP/${DB}.AUX"
UMOUNT


