#!/bin/sh
. /etc/kerbynet.conf
rm -f /tmp/dhcpd_started
OUTPUT=/tmp/dhcpd_tmp
OPT="$1"
function TERM () {
  I=0
  ps -e |grep -w -q dhcpd || return 0
  while [ $I -lt 30 ] ; do
    if ps -e |grep -w -q dhcpd ; then
      killall -TERM dhcpd 2> /dev/null
    else 
       return 0
    fi
    I=$((I+1))
  done
  return 1
}
if [ "`$SCRIPTS/dhcp_subnetenabled`" == "" ] ; then
  TERM
fi
if [ "$OPT" == noconfig ] ; then
  TERM
  if [ -r "$REGISTER/system/dhcp/Enabled" ] && grep -q subnet $REGISTER/system/dhcp/dhcpd.conf 2>/dev/null ; then
      dhcpd -cf $REGISTER/system/dhcp/dhcpd.conf -lf $REGISTER/system/dhcp/dhcpd.leases 2>/dev/null -q && touch /tmp/dhcpd_started

  fi

else
  if $SCRIPTS/dhcp_createconfig 2>/dev/null ; then
    TERM
    rm -f $REGISTER/system/dhcp/ERROR
    if [ -r "$REGISTER/system/dhcp/Enabled" ] && grep -q subnet $REGISTER/system/dhcp/dhcpd.conf ; then
      dhcpd -cf $REGISTER/system/dhcp/dhcpd.conf -lf $REGISTER/system/dhcp/dhcpd.leases 2>/dev/null -q && touch /tmp/dhcpd_started
      
    fi
  else
    cp $OUTPUT $REGISTER/system/dhcp/ERROR
    exit 2
  fi
fi



