#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/dhcp"
if cd $CONFIG/subnets 2>/dev/null ; then
  SUBNETS=`ls -d [0123456789][0123456789] 2>/dev/null`
  for S in $SUBNETS ; do
    ENABLED="`cat $S/Enabled 2>/dev/null`"
    if [ "$ENABLED" == yes ] ; then
       SNE="$SNE $S"
    fi
  done
fi
echo $SNE


