#!/bin/sh
. /etc/kerbynet.conf
NETWORK="$1"
NETMASK="$2"
[ -z "$NETWORK" -o -z "$NETMASK" ] && exit 1
CONFIG="$REGISTER/system/dhcp"
cd $CONFIG/subnets || mkdir -p $CONFIG/subnets
SUBNETS=`ls -d [0123456789][0123456789] 2>/dev/null`
for S in $SUBNETS ; do
  if [ "`cat $S/Network`" == "$NETWORK" -a "`cat $S/Netmask`" == "$NETMASK" ] ; then
    echo "Subnet already exists." 1>&2
    exit 2
  fi
done
NUM=$S
if [ "$NUM" == "" ] ; then
  NUM=00
else
  if [ "${NUM:0:1}" == 0 ] ; then
    NUM=${NUM:1:1}
  fi
  NUM=`echo $((NUM+1)) | awk '{printf "%02s",$0 }'`
fi
mkdir $CONFIG/subnets/$NUM
echo $NETWORK > $CONFIG/subnets/$NUM/Network
echo $NETMASK > $CONFIG/subnets/$NUM/Netmask
echo yes > $CONFIG/subnets/$NUM/Enabled
echo 08 > $CONFIG/subnets/$NUM/DefaultLeaseHours
echo 12 > $CONFIG/subnets/$NUM/MaxLeaseHours
echo $NUM >$CONFIG/SelectedSubnet
IPs=`ifconfig | grep "inet addr:" |sed -r 's/.*inet addr:([0123456789]{1,3}\.[0123456789]{1,3}\.[0123456789]{1,3}\.[0123456789]{1,3}).*/\1/' |grep -v 127\.0\.0\.1`
for I in $IPs ; do
  if $SCRIPTS/ip_belongs_network $I $NETWORK $NETMASK ; then
    GW=$I
  fi
done
echo $GW > $CONFIG/subnets/$NUM/Router
echo $GW > $CONFIG/subnets/$NUM/DNS1

$SCRIPTS/dhcp_start
exit 0
