#!/bin/sh
. /etc/kerbynet.conf
mkdir $REGISTER/system/dns/Forwarders 2>/dev/null
mkdir $REGISTER/system/dns/SlaveServer 2>/dev/null
rm -f /tmp/named.conf
rm -f /tmp/slavelist
touch /tmp/slavelist
cd $REGISTER/system/dns/SlaveServer
for SLAVE in `ls` ; do
  echo "    $SLAVE;" >> /tmp/slavelist
done
cd "$REGISTER/system/dns/Forwarders"
for ZONE in `ls` ; do
  DOMAIN=`cat $ZONE/Domain 2>/dev/null`
  if [ "$DOMAIN" == ANY ] ; then
    SERVER=`cat $ZONE/Server 2>/dev/null | tr \, \;`
    ANYFORWARDERS="forwarders { $SERVER; };"
  fi
done
DNS_AUTHORIZED="`$SCRIPTS/dns_allow-query`"
if iptables -L SYS_DNS -n >/dev/null 2>/dev/null ; then 
  $SCRIPTS/dns_iptables "$DNS_AUTHORIZED"
fi
echo "  acl localclients { localhost ; $DNS_AUTHORIZED };" >> /tmp/named.conf
echo "options {" >> /tmp/named.conf
echo "  directory \"/var/register/system/dns/data/\";" >> /tmp/named.conf
echo "  listen-on port 53 { `cat $REGISTER/system/dns/listen`; };" >> /tmp/named.conf
echo "  allow-transfer { " >> /tmp/named.conf
cat /tmp/slavelist >> /tmp/named.conf
echo "  };" >> /tmp/named.conf
echo "  also-notify {" >> /tmp/named.conf
cat /tmp/slavelist >> /tmp/named.conf
echo "  };" >> /tmp/named.conf
if [ -n "$ANYFORWARDERS" ] ; then
  echo "  $ANYFORWARDERS" >> /tmp/named.conf
fi
if [ -r "$REGISTER/system/dns/Options" ] ; then
  cat "$REGISTER/system/dns/Options" >> /tmp/named.conf
fi
echo "  allow-query { localclients; };" >> /tmp/named.conf
echo "  allow-query-cache { localclients; };" >> /tmp/named.conf
echo "  version none;" >> /tmp/named.conf
echo "};" >> /tmp/named.conf
cat <<EOF >> /tmp/named.conf
logging { 
  category "general" { "general"; };
  category lame-servers { null; };
  category security { null; };
  category edns-disabled { null; }; 
  channel "general" {
    file "/tmp/bind.log";
    print-time yes;
  };
};
key "rndc-key" {
  algorithm hmac-md5;
  secret "tZW4xN5xKEkf1P1QHN1iGQ==";
};
controls {
  inet 127.0.0.1 port 953
  allow { 127.0.0.1; } keys { "rndc-key"; };
};
EOF
echo > /tmp/named.local-view
echo > /tmp/named.external-view
echo > /tmp/named.common-view
BASE=`cat $REGISTER/system/ldap/base`
ZONES=`ldapsearch -LLL -x -b "ou=DNS,$BASE" "relativeDomainName=@" zoneName | egrep ^zoneName: | awk '{print $2}'|sort -u`
for Z in $ZONES ; do
  DCZ=`echo "$Z" | awk -vRS=. '{printf "dc=%s,",$1}'`
  TTL=`ldapsearch -LLL -x -b"ou=DNS,$BASE" "(&(zoneName=$Z)(relativeDomainName=@))" sOARecord |egrep ^sOARecord: |awk '{print $8}'`
  echo "  zone \"$Z\" {" >> /tmp/named.local-view
  echo "    type master;" >> /tmp/named.local-view
  echo "    database \"ldap ldap://127.0.0.1/${DCZ}ou=DNS,$BASE $TTL\";" >> /tmp/named.local-view
  echo "  };" >> /tmp/named.local-view
  echo "  zone \"$Z\" {" >> /tmp/named.external-view
  echo "    type master;" >> /tmp/named.external-view
  echo "    database \"ldap ldap://127.0.0.1/${DCZ}ou=DNS,$BASE $TTL\";" >> /tmp/named.external-view
  echo "    allow-query { any; };" >> /tmp/named.external-view
  echo "  };" >> /tmp/named.external-view
done
mkdir $REGISTER/system/dns/SlaveZones 2>/dev/null
cd $REGISTER/system/dns/SlaveZones
for ZONE in `ls` ; do
  MASTER=`cat $ZONE/master 2>/dev/null`
  if ! [ -z "$MASTER" ] ; then
    echo "  zone \"$ZONE\" {" >> /tmp/named.local-view
    echo "    type slave;" >> /tmp/named.local-view
    echo "    masters { $MASTER; };" >> /tmp/named.local-view
    echo "    file \"slaves/$ZONE.zone\";" >> /tmp/named.local-view
    echo "  };" >> /tmp/named.local-view
    echo "  zone \"$ZONE\" {" >> /tmp/named.external-view
    echo "    type slave;" >> /tmp/named.external-view
    echo "    masters { $MASTER; };" >> /tmp/named.external-view
    echo "    file \"slaves/$ZONE.zone\";" >> /tmp/named.external-view
    echo "    allow-query { any; };" >> /tmp/named.external-view
    echo "  };" >> /tmp/named.external-view
  fi
done
cd "$REGISTER/system/dns/Forwarders"
for ZONE in `ls` ; do
  DOMAIN=`cat $ZONE/Domain 2>/dev/null`
  SERVER=`cat $ZONE/Server 2>/dev/null | tr \, \;`
  if ! [ -z "$DOMAIN" -o "$DOMAIN" == ANY ] ; then
    echo "  zone \"$DOMAIN\" {" >> /tmp/named.local-view
    echo "    type forward;" >> /tmp/named.local-view
    echo "    forwarders { $SERVER; };" >> /tmp/named.local-view
    echo "    forward only;" >> /tmp/named.local-view
    echo "  };" >> /tmp/named.local-view
    echo "  zone \"$DOMAIN\" {" >> /tmp/named.external-view
    echo "    type forward;" >> /tmp/named.external-view
    echo "    forwarders { $SERVER; };" >> /tmp/named.external-view
    echo "    forward only;" >> /tmp/named.external-view
    echo "  };" >> /tmp/named.external-view
  fi
done
echo '  zone "." IN {' >>/tmp/named.common-view
echo '        type hint;' >>/tmp/named.common-view
echo '        file "root.cache";' >>/tmp/named.common-view
echo '  };' >>/tmp/named.common-view
echo 'view "internal-in" in {' >> /tmp/named.conf
echo '  match-clients { localclients; };' >> /tmp/named.conf
echo '  recursion yes;' >> /tmp/named.conf
echo '  additional-from-auth yes;' >> /tmp/named.conf
echo '  additional-from-cache yes;' >> /tmp/named.conf

cat /tmp/named.common-view /tmp/named.local-view >> /tmp/named.conf
echo '};' >> /tmp/named.conf
echo 'view "external-in" in {' >> /tmp/named.conf
echo '  match-clients { any; };' >> /tmp/named.conf
echo '  recursion no;' >> /tmp/named.conf
echo '  additional-from-auth no;' >> /tmp/named.conf
echo '  additional-from-cache no;' >> /tmp/named.conf
cat /tmp/named.common-view /tmp/named.external-view >> /tmp/named.conf
echo '};' >> /tmp/named.conf
rm -f /tmp/named.local-view /tmp/named.external-view /tmp/named.common-view



