#!/bin/sh
. /etc/kerbynet.conf
ZONE="$1"
MASTER="$2"
[ -z "$ZONE" ] && exit 1
[ "$ZONE" == "." ] && exit 1
[ "$ZONE" == ".." ] && exit 1
BASE=`cat $REGISTER/system/ldap/base`
DCZ=`echo "$ZONE" | awk -vRS=. '{printf "dc=%s,",$1}'`
if ldapsearch -LLL -x -b"${DCZ}ou=DNS,$BASE" relativeDomainName=@ zonename 2>/dev/null |grep -q -i "zoneName: $ZONE" ; then
  echo "Master zone $ZONE already exists" >&2
  exit 2
fi
if [ -r "$REGISTER/system/dns/SlaveZones/$ZONE/master" ] ; then
  echo "Slave zone $ZONE already exists" >&2
  exit 2
fi
if mkdir "$REGISTER/system/dns/SlaveZones/$ZONE" 2>/dev/null ; then
  echo $MASTER > "$REGISTER/system/dns/SlaveZones/$ZONE/master"
else
  exit 3
fi

$SCRIPTS/dns_start

