#!/bin/bash
CACHE=/tmp/dc
if [ -f $CACHE.new ] ; then
  exit
fi
tail -200 $CACHE 2>/dev/null > $CACHE.new
for IP in $@ ; do
  FQDN=`host $IP 2>/dev/null |awk -F'domain name pointer ' '{print \$2}'|head -1`
  if [ -n "$FQDN" ] ; then
    if ! grep -q "^$IP:" $CACHE.new 2>/dev/null ; then
      echo "$IP:${FQDN%.}" >> $CACHE.new
    fi
  fi
done
mv $CACHE.new $CACHE 2>/dev/null


