#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
IP="$2"
NETMASK="$3"
OBJ="$4"
STATUS="$5"
[ -z "$INTERFACENAME" -o -z "$IP" -o -z "$OBJ" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
VLAN=`echo $INTERFACENAME | awk -F. '{print $2}'`
INTERFACE=`echo $INTERFACENAME |cut -d. -f1`
if $SCRIPTS/checkNetworkOverlap "$IP" "$NETMASK" "$INTERFACE" "$VLAN" ; then
  exit 5
fi
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
if ! [ -z "$VLAN" ] ; then 
  IDIR="$IDIR/VLAN/$VLAN"
  if ! [ -d "$IDIR" ] ; then
     echo "VLAN $VLAN doesn't exist." 1>&2
     exit 3
  fi
fi
ALIAS=`basename $OBJ`
IPDIR="$IDIR/IP"
mkdir $IPDIR 2>/dev/null
cd $IPDIR
IPS=`ls | sort`
for i in $IPS ; do
   if ! [ "$i" -eq "$ALIAS" ] ; then
      xIP=`cat $i/IP 2>/dev/null`
      xNETMASK=`cat $i/Netmask 2>/dev/null`
      if [ "$xIP" == "$IP" ] ; then
         echo "IP $IP already exists." 1>&2
         exit 4
      fi
   fi
done
if [ "$STATUS" != up ] ; then
  STATUS=down
fi

if ifconfig $INTERFACENAME:$ALIAS $IP netmask $NETMASK broadcast `getbroadcast $IP $NETMASK` $STATUS ; then
  echo $IP > $IPDIR/$ALIAS/IP
  echo $NETMASK > $IPDIR/$ALIAS/Netmask
  echo $STATUS > $IPDIR/$ALIAS/STATUS
  $SCRIPTS/ip_restart_daemon 2>/dev/null >/dev/null &
  exit 0
else 
  echo "No IP changed."
  exit 5
fi

