#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/cp"
cd "$CONFIG"
iptables -N CaptivePortal 2>/dev/null
iptables -t nat -N CaptivePortal 2>/dev/null
ENABLED=`cat Enabled 2>/dev/null`
iptables -D FORWARD -j CaptivePortal 2>/dev/null
iptables -t nat -D PREROUTING -j CaptivePortal 2>/dev/null
if [ "$ENABLED" == yes ] ; then
  iptables -I FORWARD 1 -j CaptivePortal
  iptables -t nat -I PREROUTING 1 -j CaptivePortal
fi
