#!/bin/sh
. /etc/kerbynet.conf
iptables -N SYS_HTTPS 2> /dev/null
iptables -F SYS_HTTPS
iptables -A SYS_HTTPS -i lo -j ACCEPT
ACLs="`cat /var/register/system/httpd/ACL 2>/dev/null`"
if [ -n "$ACLs" ] ; then
  for A in $ACLs ; do
    IP=`echo "$A" | awk -F: '{print $1}'`
    INTERFACE=`echo "$A" | awk -F: '{print $2}'`
    RULE=""
    if ! [ -z "$INTERFACE" ] ; then
      VLAN=`echo $INTERFACE | awk -F. '{print $2}'`
      MODE=Routed
      if [ -z "$VLAN" ] ; then
        if [ -f "$REGISTER/system/net/interfaces/$INTERFACE/Bridge/Name" ] ; then
          MODE=Bridged
        fi
      else
        INTERFACE=`echo $INTERFACE | awk -F. '{print $1}'`
        if [ -f "$REGISTER/system/net/interfaces/$INTERFACE/VLAN/$VLAN/Bridge/Name" ] ; then
          MODE=Bridged
        fi
      fi
      [ -n "$VLAN" ] && INTERFACE=$INTERFACE.$VLAN
      if [ "$MODE" == Bridged ] ; then
        RULE=" -m physdev --physdev-in $INTERFACE"
      else
        RULE=" -i $INTERFACE"
      fi
    fi
    if ! [ -z "$IP" ] ; then
      RULE="$RULE -s $IP"
    fi
    iptables -A SYS_HTTPS $RULE -j ACCEPT
  done
fi
if [ "`cat $REGISTER/system/httpd/Local 2>/dev/null`" = yes ] ; then
  for C in `$SCRIPTS/list_local_subnet` ; do
    iptables -A SYS_HTTPS -s $C -j ACCEPT
  done
fi
iptables -A SYS_HTTPS -j DROP
