#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls |sort -f`
for I in $INTERFACES ; do
   cd $CONFIG
   echo "<option value='$I'>$I</option>"
   if [ -d "$I/VLAN" ] ; then
     cd $I/VLAN
     VLANS=`ls`
     for V in $VLANS ; do
        echo "<option value='$I.$V'>$I vlan $V</option>"
     done
   fi
done


