#!/bin/sh
. /etc/kerbynet.conf
CHAIN="$1"
[ -z "$CHAIN" ] && exit 1
CONFIG="$REGISTER/system/net/FW"
if iptables -N "$CHAIN" ; then
  mkdir "$CONFIG/Chains/$CHAIN" || exit 3
  echo ACCEPT > "$CONFIG/Chains/$CHAIN/Policy"
  echo yes > "$CONFIG/Chains/$CHAIN/Enabled"
else
  exit 2
fi
