#!/bin/sh
. /etc/kerbynet.conf
CHAIN="$1"
[ -z "$CHAIN" ] && exit 1
CONFIG="$REGISTER/system/net/FW"
REF="`iptables -L $CHAIN |grep -w 'references)' |sed -r 's/.*\((.*) references\)/\1/'`"
if [ "$REF" == 0 ] ; then
  iptables -F "$CHAIN"
fi
if iptables -X "$CHAIN" ; then
  rm -rf "$CONFIG/Chains/$CHAIN" || exit 3
else
  echo " ($REF references)" >&2
  exit 2
fi
