#!/bin/sh
. /etc/kerbynet.conf
iptables -N SYS_SSH 2> /dev/null
iptables -F SYS_SSH
iptables -A SYS_SSH -i lo -j ACCEPT
ACLs="`cat /var/register/system/ssh/ACL 2>/dev/null`"
if [ -z "$ACLs" ] ; then
  iptables -A SYS_SSH -j ACCEPT
else
  for A in $ACLs ; do
    IP=`echo "$A" | awk -F: '{print $1}'`
    INTERFACE=`echo "$A" | awk -F: '{print $2}'`
    RULE=""
    if ! [ -z "$INTERFACE" ] ; then
      VLAN=`echo $INTERFACE | awk -F. '{print $2}'`
      MODE=Routed
      if [ -z "$VLAN" ] ; then
        if [ -f "$REGISTER/system/net/interfaces/$INTERFACE/Bridge/Name" ] ; then
          MODE=Bridged
        fi
      else
        INTERFACE=`echo $INTERFACE | awk -F. '{print $1}'`
        if [ -f "$REGISTER/system/net/interfaces/$INTERFACE/VLAN/$VLAN/Bridge/Name" ] ; then
          MODE=Bridged
        fi
      fi
      [ -n "$VLAN" ] && INTERFACE=$INTERFACE.$VLAN
      if [ "$MODE" == Bridged ] ; then
        RULE=" -m physdev --physdev-in $INTERFACE"
      else
        RULE=" -i $INTERFACE"
      fi
    fi
    if ! [ -z "$IP" ] ; then
      RULE="$RULE -s $IP"
    fi
    iptables -A SYS_SSH $RULE -j ACCEPT
  done
  iptables -A SYS_SSH -j DROP
fi
