#!/bin/sh
. /etc/kerbynet.conf
DB="$1"
if [ -z "$DB" ] ; then
  CONFIG="$REGISTER/system/net/router"
else
  CONFIG="$DB/router"
fi
if [ -d $CONFIG/Statics ] ; then
  cd $CONFIG/Statics
  ENTRIES=`ls 2>/dev/null`
  for E in $ENTRIES ; do
    export RouteType="`cat $E/RouteType`"
    export Dest="`cat $E/Dest`"
    export Netmask="`cat $E/Netmask`"
    export Via="`cat $E/Via`"
    export Gateway="`cat $E/Gateway`"
    export Metric="`cat $E/Metric`"
    export Interface="`cat $E/Interface`"
    if [ "$Via" == GW -a "$Netmask" == "0.0.0.0" -a "$Dest" == "0.0.0.0" -a "$Metric" == "0" ] ; then
      echo "$Gateway $E"
      exit 
    fi
  done
fi
exit 1
