#!/bin/sh
. /etc/kerbynet.conf
SELECTED="$1"
cd /sys/class/net
INTERFACES=`ls -d ETH[0123456789][0123456789] 2>/dev/null`
for I in $INTERFACES ; do
  if [ "$I" == "$SELECTED" ] ; then
    SEL=selected
  else
    SEL=""
  fi
  DESC="`$SCRIPTS/getintdesc $I`"
  echo "<option value='$I' $SEL>$I -$DESC</option>"  

done
