#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
[ -z "$ID" ] && exit 1
ID=`echo "$ID" | awk -F":" '{print $1}'`
export RELEASE=`$SCRIPTS/release`
export PATCHLEVEL=`$SCRIPTS/patchlevel`
if [ -f "$REGISTER/system/AutoUpdate/pkgs/$ID/pkg/Installed" ] ; then
  if [ -f "$REGISTER/system/AutoUpdate/pkgs/$ID/Enabled" ] ; then
    echo ENABLED
  else
    echo DISABLED
  fi
else
  echo "NOT INSTALLED"
fi
exit 0




