#!/bin/bash
. /etc/kerbynet.conf
PRE="$1"
E="$2"
if [ -z "$E" ] ; then
   E=`cd /sys/class/net/ ; ls -d ETH?? 2>/dev/null|head -1`
fi

#MAC=`cat /sys/class/net/$E/address 2>/dev/null|sed 's/://g'`
MAC=`cd $REGISTER/system/net/interfaces/$E/MAC 2>/dev/null && ls -d ???????????? 2>/dev/null|head -1 |tr '[:upper:]' '[:lower:]' 2>/dev/null`
FEATURE=${PRE}$MAC

echo $FEATURE |grep ^..............$

