#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
[ -z "$ID" ] && exit 1
DEPS=`$SCRIPTS/autoupdateGetField "$ID" DEPS`
if [ -n "$DEPS" ] ; then
  DEPS=`echo $DEPS|tr ',' ' '`
  echo '<table width=100%>'
  for D in $DEPS ; do
     if [ -f "$REGISTER/system/AutoUpdate/pkgs/$D/pkg/Installed" ] ; then
       COLOR=30C030
     else
       COLOR=F03030
     fi
     echo "<tr><td width=1%><font color=#$COLOR><b>$D</b></font></td><td>&nbsp;&nbsp;&nbsp;&nbsp;<font>`$SCRIPTS/autoupdateGetField $D DESCRIPTION`</font></td><td nowrap width=1%><font>`$SCRIPTS/autoupdateGetSize $D`</font></td></tr>"

  done
  echo '</table>'
else

  echo "No required packages found"
fi
