#!/bin/sh
INTERFACE="$1"
if [ -z "$INTERFACE" ] ; then
   echo "No interface specified." 1>&2
   exit 1
fi
if [ "${INTERFACE:0:6}" == BRIDGE -o "${INTERFACE:0:4}" == BOND -o "${INTERFACE:0:3}" == VPN ] ; then
  DESC=" `cat /var/register/system/net/interfaces/$INTERFACE/Description 2>/dev/null`"
fi
if [ -d "/var/register/system/net/interfaces/$INTERFACE/WiFi/" ] ; then
  SSID=`cat /var/register/system/net/interfaces/$INTERFACE/WiFi/SSID 2>/dev/null`
  if [ "`cat /var/register/system/net/interfaces/$INTERFACE/WiFi/Hide 2>/dev/null`" == 0 ] ; then
    HIDE='[Hidden:no]'
  else
    HIDE='[Hidden:yes]'
  fi
  SEC=`cat /var/register/system/net/interfaces/$INTERFACE/WiFi/Encryption 2>/dev/null`
  MODE=`cat /var/register/system/net/interfaces/$INTERFACE/WiFi/Mode 2>/dev/null`
  [ "$MODE" == sta ] && HIDE=""
  echo " WiFi - [SSID:$SSID] [Mode:$MODE] [Security:$SEC] $HIDE"
  exit
fi

if [ "${INTERFACE:0:3}" == PPP ] ; then
    echo "Point to Point over Ethernet"
    exit
fi
INTSYS="/sys/class/net/$INTERFACE"
if [ ! -d "$INTSYS" ] ; then
   echo "Interface doesn't exist." 1>&2
   exit 2
fi
if [ -r "$INTSYS/device/vendor" -a -r "$INTSYS/device/device" ] ; then
   VENDOR=`cat "$INTSYS/device/vendor"`
   DEVICE=`cat "$INTSYS/device/device"`
   DESC=`lspci -d "$VENDOR:$DEVICE" | tail -1 | awk -F: '{printf "%s%s%3s",$3,$4,$5 }'`
else
  :
fi


if [ -z "$DESC" ] ; then
  echo " Unknown Model"
else
  echo "$DESC"
fi
