#!/bin/sh
TMP="/tmp/CRL_Import.tmp"
source /etc/kerbynet.conf
cd "$SSLDIR/certs/trusted_CAs/"
/usr/local/ssl/bin/openssl crl >"$TMP"

HASH=`/usr/local/ssl/bin/openssl crl -hash -noout -in "$TMP"`
if [ -r "$SSLDIR/certs/trusted_CAs/$HASH.0" ] ; then
  cp "$TMP" "$SSLDIR/certs/trusted_CAs/$HASH.r0"  
  /usr/local/ssl/bin/openssl x509 -in "$SSLDIR/certs/trusted_CAs/$HASH.0" -text -noout |grep Subject: |awk -F'Subject: ' '{print $2}'| awk -F'CN=' '{print $2}' |sed -r 's/(.*).*, [A-Z]{1,2}=.*/\1/'
else
  echo "There is not a trusted CA related to the CRL you want to import" >&2
  exit 3
fi

 
