#!/bin/awk -f
BEGIN {
   if (ARGC!=4) exit 1
   FS=".";
   split(ARGV[1],IP);
   split(ARGV[2],NETWORK);
   split(ARGV[3],NETMASK);
   if (and(IP[1],NETMASK[1])!=and(NETWORK[1],NETMASK[1])) exit 2;
   if (and(IP[2],NETMASK[2])!=and(NETWORK[2],NETMASK[2])) exit 2;
   if (and(IP[3],NETMASK[3])!=and(NETWORK[3],NETMASK[3])) exit 2;
   if (and(IP[4],NETMASK[4])!=and(NETWORK[4],NETMASK[4])) exit 2;
   exit 0;
}
