#!/bin/sh
. /etc/kerbynet.conf

if ! ps -e |grep -w routerconfig ; then
  $SCRIPTS/routerconfig 2>/dev/null >/dev/null
fi
if ! ps -e |grep -w dns_hup ; then
  $SCRIPTS/dns_hup
fi
if ! ps -e |grep -w dhcp_start ; then
  $SCRIPTS/dhcp_start 2>/dev/null >/dev/null
fi
if [ "`cat $REGISTER/system/httpd/Local 2>/dev/null`" = yes ] ; then
  $SCRIPTS/fw_https_chain
fi
