#!/bin/sh
. /etc/kerbynet.conf
REALM="$1"
KDC="$2"
[ -z "$REALM" ] && exit 1
[ -z "$KDC" ] && exit 2
cd $REGISTER/system/k5/client/realms/ || exit 2
if grep -q -w "^$REALM\$" [0123456789][0123456789]/name ; then
  echo "Realm already configured" >&2
  exit 10
fi
NUM=`ls -d [0123456789][0123456789] 2>/dev/null | tail -1`
if [ "$NUM" == "" ] ; then
  NUM=00
else
  if [ "${NUM:0:1}" == 0 ] ; then
    NUM=${NUM:1:1}
  fi
  NUM=`echo $((NUM+1)) | awk '{printf "%02s",$0 }'`
fi
mkdir $NUM
echo $REALM > $NUM/name
echo $KDC > $NUM/KDC
$SCRIPTS/k5_createConf

