#!/bin/sh
. /etc/kerbynet.conf
function Convert () {
  DESC="$1"
  ENCDESC="`echo "$DESC" | awk -F", " '{print $1}'`"
  SALTDESC="`echo "$DESC" | awk -F", " '{print $2}'`"
  ENC=`egrep ",$ENCDESC$" $REGISTER/system/k5/supported_enctypes | awk -F"," '{print $1}'`
  SALT=`egrep ",$SALTDESC$" $REGISTER/system/k5/supported_salts | awk -F"," '{print $1}'`
  if ! [ -z "$ENC" -o -z "$SALT" ] ; then
    echo -n "$ENC:$SALT "
  fi
}
DEFAULTENC="$REGISTER/system/k5/default_keys"
N=`cat "$DEFAULTENC" | wc -l` 
if [ "$N" -ge 1 ] ; then
  for I in `seq 1 $N` ; do
    Convert "`head -$I "$DEFAULTENC" | tail -1`" 
  done
fi
