#!/bin/sh
source /etc/kerbynet.conf
cd "$SSLDIR/certs/trusted_CAs/" || mkdir "$SSLDIR/certs/trusted_CAs/"
ENTRIES=`ls ".cacert.pem" [0123456789][0123456789].pem 2>/dev/null`
for C in $ENTRIES ; do
  NAME=${C%.pem}
  TXT=`/usr/local/ssl/bin/openssl x509 -in $SSLDIR/certs/trusted_CAs/$C -text -noout |grep Subject: |awk -F'Subject: ' '{print $2}'| awk -F'CN=' '{print $2}' |sed -r 's/(.*).*, [A-Z]{1,2}=.*/\1/'`
  if [ -z "$TXT" ] ; then
    TXT=`/usr/local/ssl/bin/openssl x509 -in $SSLDIR/certs/trusted_CAs/$C -text -noout |grep Subject: |awk -F'Subject: ' '{print $2}'`
  fi
  TXT=${TXT:0:85}
  if [ "$NAME" == ".cacert" ] ; then
    TXT="$TXT&nbsp;&nbsp;(Local CA)"
  fi
  HASH=`/usr/local/ssl/bin/openssl x509 -hash -noout -in $SSLDIR/certs/trusted_CAs/$C`

  if [ -r "$SSLDIR/certs/trusted_CAs/${HASH}.r0" ] ; then
    LASTUPDATE=`/usr/local/ssl/bin/openssl crl -noout -lastupdate -in "$SSLDIR/certs/trusted_CAs/${HASH}.r0" |awk -F= '{print $2}'|sed -r 's/(.*) ..:..:.. (.*) (.*)/\1 \2/'`
    TXT="$TXT&nbsp;&nbsp;[CRL:$LASTUPDATE]"
  fi
  echo "<option value='$NAME'>$TXT</option>"
done

 
