#!/bin/sh
. /etc/kerbynet.conf
MSGBOARD="/tmp/msgboard.html"
LANGUAGE=`cat $REGISTER/system/AutoUpdate/Language 2>/dev/null`
for I in 12345 ; do
  PID=`ps -ef |grep -w wget | grep "/tmp/msgboard.html" | awk '{print $2}'`
  if ! [ -z "$PID" ] ; then
    kill $PID   
  fi
done
if [ "$LANGUAGE" == Ita ] ; then
  URL="http://www.zeroshell.net/msgboard.php"
else
  URL="http://www.zeroshell.net/eng/msgboard.php"
  LANGUAGE=Eng
fi
if wget --timeout=10 -t 1 -O "$MSGBOARD" "$URL" ; then
  mv "$MSGBOARD" "$REGISTER/system/AutoUpdate/Msg$LANGUAGE.html"
  echo > "$REGISTER/system/AutoUpdate/LocalMsg$LANGUAGE"
else
  LastUpdate=`ls -l --time-style=+"#%B %d, %Y  %R#" /var/register/system/AutoUpdate/Msg$LANGUAGE.html |sed -r 's/.*#(.*)#.*/\1/g'`
  cat <<EOF > "$REGISTER/system/AutoUpdate/LocalMsg$LANGUAGE"
<font color=#ff0000 style="font-size: 10px;">The site http://www.zeroshell.net is unreachable from ZeroShell host `$SCRIPTS/server_name`</font><br>
<font color=#2020f0 style="font-size: 10px;">Last Connection: $LastUpdate</font><br>
<br>
EOF
fi
export QUERY_STRING="onlyrender"
render $REGISTER/system/AutoUpdate/Msg$LANGUAGE.html
rm -f "$MSGBOARD" 
