#!/bin/sh
. /etc/kerbynet.conf
 echo -e "Please wait: scanning storage devices ...\n"
$SCRIPTS/storage nomount 2>/dev/null >/dev/null
INFO="/storage/INFO"
DISKS=`cd $INFO/DISK/ 2>/dev/null && ls 2>/dev/null`
ACTIVEDB="`$SCRIPTS/getactivedb | tr '/' '_'`"
I=0
for D in $DISKS ; do
  echo "Disk: `sed 's/^ *//' < $INFO/DISK/$D/Model |sed 's/[^[:print:]]//g'|sed -r 's/ {2,}/ /g'`"
  PARTS=`cd $INFO/DISK/$D/PART 2>/dev/null && ls 2>/dev/null`
  for P in $PARTS ; do
    DBS=`cd $INFO/DISK/$D/PART/$P/DB 2>/dev/null && ls 2>/dev/null`
    for DB in $DBS ; do
      I=$((I+1))
      DBDIR="$INFO/DISK/$D/PART/$P/DB/$DB"
      DESC="  <$I> `cat $DBDIR/Description 2>/dev/null`"
      if [ "$ACTIVEDB" == "$P:$DB" ] ; then
        DESC="$DESC (ACTIVE)"
      fi
      echo "$DESC"
      DBMEM[$I]="$D:$P:$DB"
    done
  done
done
echo
if [ $I != 0 ] ; then
  S=0
  while [ "$S" -lt 1 -o "$S" -gt $I ] ; do
    echo -n "Select a profile from the list (1-$I): "
    read S
    S=`echo "$S" | sed 's/[^[:digit:]]//g'`
    [ -z "$S" ] && S=0
  done
  DISK=`echo ${DBMEM[$S]} |awk -F: '{print $1}'`
  PARTITION=`echo ${DBMEM[$S]} |awk -F: '{print $2}'`
  DATABASE=`echo ${DBMEM[$S]} |awk -F: '{print $3}'`
  $SCRIPTS/localman_infodb "$DISK" "$PARTITION" "$DATABASE"
  if [ "$PARTITION:$DATABASE" == "$ACTIVEDB" ] ; then
     echo "WARNING: The profile is already active!!!"
     echo
     echo -n "Press any key to return to the main menu."
     read -n1     
     exit 5
  fi

  echo "WARNING: after the profile activation the system will be rebooted with the new configuration!!!"
  echo -n "Are you sure you want to continue (y/n)? "
  read -n1 Y
  echo 
  Y=`echo $Y | awk '{print toupper($0)}'`
  if [ "$Y" == "Y" ] ; then
    PARTITION=`echo $PARTITION | tr '_' '/'`
    if $SCRIPTS/activatedb $PARTITION $DATABASE ; then
      echo "Profile successfully activated."
    else 
      echo "Profile activation ERROR."
    fi
    echo "The system is rebooting..."
    echo
    reboot
  fi
  exit 5
else
  cat <<EOF
No profile found!!!

You have to connect to the web interface to create one and active it.
Remember that if you do not active a profile, all the configurations and
data changes will be lost after you switch off or reboot the system.

EOF
  echo -n "Press any key to continue. "
  read -n1
  exit 5
fi
