#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/defaultvalue
ACTIVEDB="`$SCRIPTS/getactivedb`"
if ! echo "$ACTIVEDB" | grep -q ":" ; then
   echo
   echo -e "WARNING: no profile is active. The system is running with temporary\nconfiguration and data."
   echo
   echo -n "Press any key to return to the main menu."
   read -n1
   exit 5
fi
echo "Please wait: scanning storage devices ..."
$SCRIPTS/storage nomount 2>/dev/null >/dev/null
INFO="/storage/INFO"
PARTITION=`echo "$ACTIVEDB" | awk -F: '{print $1}' |tr / _`
DATABASE=`echo "$ACTIVEDB" | awk -F: '{print $2}'`
DISK=`find /storage/INFO/ |egrep "/storage/INFO/DISK/.*/PART/${PARTITION}$"|awk -F/ '{print $5}'`
$SCRIPTS/localman_infodb "$DISK" "$PARTITION" "$DATABASE"
echo -e "WARNING: after the profile deactivation the system will be rebooted\nwith temporary default configuration and data stored in the RAM.\nThe default URL for the web interface will be https://$DEFAULTIP and\nthe admin user password will be \"$DEFAULTPW\"\n"
echo -n "Are you sure you want to continue (y/n)? "
read -n1 Y
echo 
Y=`echo $Y | awk '{print toupper($0)}'`
if [ "$Y" == "Y" ] ; then
  if ! $SCRIPTS/deactivatedb ; then
    echo "Profile deactivation ERROR!!!"  
  fi
  echo "The system is rebooting..."
  echo
  reboot
else
  exit 5
fi
