#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
NAME="$1"
DESCRIPTION="$2"
BRIDGEDLIST="$3"
STP="$4"
ForwardDelay="$5"
Ageing="$6"
MaxAge="$7"
BridgePrio="$8"
HelloTime="$9"
[ -z "$NAME" ] && exit 1
export GUICONFIGBR=Yes
CONFIG="$REGISTER/system/net/interfaces/"
BRIDGEDIR="$CONFIG/$NAME"
if brctl addbr $NAME  ; then
   mkdir -p $BRIDGEDIR
   echo "$DESCRIPTION" > $BRIDGEDIR/Description
   echo "$STP" > $BRIDGEDIR/STP
   echo "$BRIDGEDLIST" > $BRIDGEDIR/BridgeList
   echo "$ForwardDelay" > $BRIDGEDIR/ForwardDelay
   echo "$Ageing" > $BRIDGEDIR/Ageing
   echo "$MaxAge" > $BRIDGEDIR/MaxAge
   echo "$BridgePrio" > $BRIDGEDIR/BridgePrio
   echo "$HelloTime" > $BRIDGEDIR/HelloTime
   echo up > $BRIDGEDIR/STATUS
   ifconfig $NAME up
   $SCRIPTS/setbridge $NAME && $SCRIPTS/mrtg_reload
else
   exit 3
fi




