#!/bin/bash
. /etc/kerbynet.conf
GW="$1"
[ -z "$GW" ] && exit 1
CDIR=$REGISTER/system/mrtg/counters/GW$GW
HEX=`echo 1$GW |awk '{printf("0x%2x",$0)}'`
iptables -t mangle -L NB_STAT -n -v -x 2>/dev/null > /tmp/NB_STAT_out
TRAF=`grep -w "match $HEX" < /tmp/NB_STAT_out | awk '{printf "%d\n",$2}'`
TOT=`awk '{X=X+$2;} END {printf "%d\n",X}' < /tmp/NB_STAT_out`
[ -z "$TRAF" ] && TRAF=0
[ -z "$TOT" ] && TOT="$TRAF"
if [ "$TRAF" -gt "$TOT" ] ; then
  TOT="$TRAF"
fi
if ! [ -d "$CDIR/traf" ] ; then
  mkdir -p "$CDIR/traf"
  echo 0 > $CDIR/traf/Counter
  echo 0 > $CDIR/traf/Delta
fi
if ! [ -d "$CDIR/tot" ] ; then
  mkdir -p "$CDIR/tot"
  echo 0 > $CDIR/tot/Counter
  echo 0 > $CDIR/tot/Delta
fi
COUNTER=`cat $CDIR/traf/Counter`
DELTA=`cat $CDIR/traf/Delta`
echo $TRAF > $CDIR/traf/Delta
if [ "$DELTA" -gt "$TRAF" ] ; then
  COUNTER=$((DELTA+COUNTER))
  echo "$COUNTER" > $CDIR/traf/Counter
fi
TRAF=$((TRAF+COUNTER))
COUNTER=`cat $CDIR/tot/Counter`
DELTA=`cat $CDIR/tot/Delta`
echo $TOT > $CDIR/tot/Delta
if [ "$DELTA" -gt "$TOT" ] ; then
  COUNTER=$((DELTA+COUNTER))
  echo "$COUNTER" > $CDIR/tot/Counter
fi
TOT=$((TOT+COUNTER))




echo $TRAF | awk '{printf "%d\n",$0}'
echo $TOT | awk '{printf "%d\n",$0}'
echo 100
echo NA 
