#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
STATUS="$1"
if [ "$STATUS" = up ] ; then
  [ -f /tmp/nb_autoppp ] && exit  
  logger -t NetBalancer "Trying to enable PPPoE/3G standby gateways ..."
else
  if [ -f /tmp/nb_autoppp ] ; then
    logger -t NetBalancer "Disabling PPPoE/3G standby gateways ..."
    rm /tmp/nb_autoppp
  else
    exit
  fi
fi
CONFIG="$REGISTER/system/net/nb/Gateways/"
cd "$CONFIG"
GWS=`ls -d ?? 2>/dev/null`
for GW in $GWS ; do
    I="`cat $GW/Interface 2>/dev/null`"
    if [ "${I:0:3}" = ppp ] ; then
      if [ "`cat $REGISTER/system/net/interfaces/$I/Auto 2>/dev/null`" = NB ] ; then
        DESC="`cat $REGISTER/system/net/interfaces/$I/Description 2>/dev/null`"
        if [ -f "$REGISTER/system/net/interfaces/$I/ETHERNET" ] ; then
	  TYPE=PPPoE
        else
	  TYPE=3G
        fi
        if [ "$STATUS" = up ] ; then 
 	  if [ "`cat $GW/Enabled 2>/dev/null`" = yes ] ; then
	    if [ "$TYPE" = 3G ] ; then
              $SCRIPTS/3Gconnect $I &
              touch /tmp/nb_autoppp
            else
              $SCRIPTS/pppoe_start $I 
              touch /tmp/nb_autoppp
            fi
            logger -t NetBalancer "=> $TYPE Interface $I ($DESC) enabled"
          fi
        else
       	    if [ "$TYPE" = 3G ] ; then
              $SCRIPTS/3Gconnect_stop $I &
              rm /tmp/nb_autoppp 2>/dev/null
            else
              $SCRIPTS/pppoe_stop $I 
              rm /tmp/nb_autoppp 2>/dev/null
            fi
            logger -t NetBalancer "=> $TYPE Interface $I ($DESC) disabled"
        fi
      fi
    fi
done
if [ "$STATUS" = up ] ; then
  if [ ! -f /tmp/nb_autoppp ] ; then
    logger -t NetBalancer "=> No PPPoE/3G standby gateway has been configured"
  fi
fi




