#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
CONFIG="$REGISTER/system/net/nb/Gateways/"
cd "$CONFIG"
BACKUP=no
GWS=`ls -d ?? 2>/dev/null`
for GW in $GWS ; do
  if [ "`cat $GW/Enabled 2>/dev/null`" = yes ] ; then
    if [ ! -f /tmp/nb/Gateways/$GW/Fault ] ; then
      I="`cat $GW/Interface 2>/dev/null`"
      if [ "${I:0:3}" = ppp ] ; then
        AUTO="`cat $REGISTER/system/net/interfaces/$I/Auto 2>/dev/null`"
        if [ "$AUTO" != NB ] ; then
          exit 0
        else
	  BACKUP=yes
        fi
      else
        exit 0
      fi
    fi
  fi	
done
if [ "$BACKUP" = yes ] ; then
  exit 55
else
  exit 1
fi




