#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/nb/Gateways/00"
IP=`cat $CONFIG/IP 2>/dev/null`
INTERFACE=`cat $CONFIG/Interface 2>/dev/null`
if [ -z "$IP" -a -z "$INTERFACE" ] ; then
  IP=`$SCRIPTS/getdefaultgw |awk '{print $1}'`
  echo $IP > $CONFIG/IP
fi
