#!/bin/bash
. /etc/kerbynet.conf
OPT="$1"
if [ "$OPT" = startup ] ; then
  export NBSTARTUP=yes
else
  export NBSTARTUP=no
fi
killall -w failoverd 2>/dev/null
killall -w gw_l2checkd 2>/dev/null
if [ "`cat $REGISTER/system/net/nb/FO/ICMPCheck 2>/dev/null`" = yes ] ; then
  $SCRIPTS/failoverd 2>/dev/null >/dev/null &
  #logger -t NetBalancer "[LAYER2] Gateway monitor is disabled"
else
  $SCRIPTS/gw_l2checkd 2>/dev/null >/dev/null &
  #logger -t NetBalancer "[ICMP] Failover monitor is disabled"
fi
sleep 0.5
