#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
TYPE="$1"
STk="`rand``cat /tmp/STk_Admin 2>/dev/null`"
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls -d $TYPE* |sort -f`
if ! [ -z "$TYPE" ] ; then
  export ${TYPE}SELECTED=selected
fi
cat << EOF
<html><head><link rel=stylesheet type=text/css href=/default.css><title>Net List</title>
<meta Http-Equiv="Cache-Control" Content="no-cache">
<meta Http-Equiv="Pragma" Content="no-cache">
<meta Http-Equiv="Expire" Content="0">
<style type="text/css">
.MkBT {
  font-size: 10;
}
</style>
<script>
function ddns() {
   newwin=window.open("kerbynet?Section=DNS&STk=$STk&Action=DDNS", "ddnsconfig","top=200,left=250,width=600,height=380,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
   newwin.focus();
}
function MakeVPN() {
   var newwin=window.open("kerbynet?Section=VPN&STk=$STk&Action=Create","VPNConfig","top=100,left=150,width=900,height=530,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
   newwin.focus();
}
function MakeBRIDGE() {
   var newwin=window.open("kerbynet?Section=Network&STk=$STk&Action=MakeBridge","BridgeConfig","top=100,left=200,width=700,height=450,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
   newwin.focus();
}
function MakeBOND() {
   var newwin=window.open("kerbynet?Section=Network&STk=$STk&Action=MakeBond","BondConfig","top=100,left=200,width=700,height=480,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
   newwin.focus();
}
function MakePPPoE() {
   var newwin=window.open("kerbynet?Section=Network&STk=$STk&Action=MakePPP","PPPConfig","top=200,left=300,width=650,height=400,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
   newwin.focus();
}
function Make3G() {
   var newwin=window.open("kerbynet?Section=Network&STk=$STk&Action=Make3G","3GConfig","top=200,left=300,width=650,height=400,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
   newwin.focus();
}
function SelectType() {
   location="kerbynet?Section=Network&STk=$STk&Action=List&Type="+document.data.TYPE.value;
}
function DefaultGW() {
  var newwin=window.open("kerbynet?Section=Router&STk=$STk&Action=DefaultGW","DefaultW","top=450,left=400,width=350,height=120,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
  newwin.focus();
}
function  NATConfig() {
  var newwin=window.open("kerbynet?Section=Router&STk=$STk&Action=Nat","Nat","top=250,left=300,width=570,height=380,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
  newwin.focus();
}
</script>
</head><body>
<form name=data>
<table width=100%><tr>
<td nowrap>Show 
<select name=TYPE onchange='SelectType()' style="font-size: 10;">
<option value="" $ALLSELECTED>ALL
<option value=ETH $ETHSELECTED>ETHERNET
<option value=WLAN $WLANSELECTED>Wi-Fi
<option value=VPN $VPNSELECTED>VPN
<option value=BRIDGE $BRIDGESELECTED>BRIDGE
<option value=BOND $BONDSELECTED>BOND
<option value=ppp $pppSELECTED>PPPoE/3G
</select>
&nbsp;
<input class=MkBT type=button value="GATEWAY" onclick='DefaultGW()'>
<input class=MkBT type=button value="NAT" onclick='NATConfig()'>
<input class=MkBT type=button value="DDNS" onclick='ddns()'>
<input class=MkBT type=button value="New VPN" onclick='MakeVPN()'>
<input class=MkBT type=button value="New BRIDGE" onclick='MakeBRIDGE()'>
<input class=MkBT type=button value="New BOND" onclick='MakeBOND()'>
<input class=MkBT type=button value="New PPPoE" onclick='MakePPPoE()'>
<input class=MkBT type=button value="New 3G Modem" onclick='Make3G()'>
</td>
<td align=right>
<input type=button value="Refresh" onclick='location="kerbynet?Section=Network&STk=$STk&Action=List&Type="+document.data.TYPE.value'>
</td>
</tr></table>
<table width=100%>
EOF
for i in $INTERFACES ; do
   echo "<tr><td><hr>"
   echo "<iframe width=100% border=0 frameborder=0 src='kerbynet?Section=Network&STk=$STk&Action=ShowInterface&Interface=$i'>Browser not compatible</iframe>"
   echo "</td></tr>"
done
echo "</table>"
echo "</form></body></html>"




