#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
BOND="$1"
FMT="$2"
[ -z "$BOND" ] && exit
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
CSV=""
INTERFACES=`ls | grep -v BOND |grep -v BRIDGE |grep -v ppp | grep -v VPN99`
for I in $INTERFACES ; do
   if  [ -d $I/Bond/ ] ; then
      NAME=`cat $I/Bond/Name 2>/dev/null`
      if [ "$NAME" == "$BOND" ] ; then

        if [ "$FMT" = CSV  ] ; then
          if [ -n "$CSV" ] ; then
            CSV="$CSV,\"$I\""
          else
            CSV="\"$I\""
          fi
        fi
        if [ "$FMT" = WEIGHTS ] ; then
          W="`$SCRIPTS/getInterfaceWeight $BOND $I`"
          [ -z "$W" ] && W=1
          if [ -n "$CSV" ] ; then
            CSV="$CSV,\"$I\":$W"
          else
            CSV="\"$I\":$W"
          fi
        fi
        if [ "$FMT" = combo ] ; then
           echo "<option value='$I'>$I</option>"
        fi
        if [ -z "$FMT" ] ; then
           echo $I
        fi
      fi 
   fi
done
echo -n "$CSV"



