#!/bin/bash
SUBNET="$1"
[ -z "$SUBNET" ] && exit 1
if [ "$SUBNET" = "0.0.0.0/0" -o "$SUBNET" = "0.0.0.0/0.0.0.0" ] ; then
  echo 0.0.0.0/0
else
  TMP=`ipcalc -n -b "$SUBNET" | grep Network:|awk -F":   " '{print $2}'`
  for T in $TMP ; do
    echo -n "$T"
  done
fi
