#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACE="$1"
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls |sort -f`
for I in $INTERFACES ; do
   cd $CONFIG
   if [ "$I" = "$INTERFACE" ] ; then
     SELECTED=selected
   else
     SELECTED=""
   fi
   echo "<option value='$I' $SELECTED>$I</option>"
done


