#!/bin/sh
. /etc/kerbynet.conf
if echo "$ifconfig_pool_remote_ip" |egrep -q "^.{1,3}\..{1,3}\..{1,3}\..{1,3}$" ; then
logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$common_name] Virtual IP automatically assigned: $ifconfig_pool_remote_ip"
else
  logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$common_name] No Virtual IP automatically assigned"

fi
