#!/bin/sh
. /etc/kerbynet.conf
if [ -z "$username" -o -z "$password" ] ; then
  exit 1
fi
USER="`echo $username | awk -F@ '{print $1}'`"
REALM="`echo $username | awk -F@ '{print $2}'`"
PW="$password"
if [ -z "$REALM" ] ; then
  DEFAULTDOMAIN="`cat $REGISTER/system/openvpn/DefaultDomain 2>/dev/null`"
  if [ -n "$DEFAULTDOMAIN" ] ; then
    REALM=$DEFAULTDOMAIN
  else
    REALM="`cat $REGISTER/system/k5/realm`"
  fi
fi
FULL=$USER@$REALM
UREALM=`echo $REALM | awk '{print toupper($0)}'`
LREALM=`echo $REALM | awk '{print tolower($0)}'`
if [ -f "$REGISTER/system/openvpn/Domains/$REALM/Type" -o -f "$REGISTER/system/openvpn/Domains/$UREALM/Type" -o -f "$REGISTER/system/openvpn/Domains/$LREALM/Type" ] ; then
  if [ -f "$REGISTER/system/openvpn/Domains/$REALM/Type" ] ; then  
    RT="`cat $REGISTER/system/openvpn/Domains/$REALM/Type 2>/dev/null`"
  else
    if [ -f "$REGISTER/system/openvpn/Domains/$UREALM/Type" ] ; then
      RT="`cat $REGISTER/system/openvpn/Domains/$UREALM/Type 2>/dev/null`"
      REALM=$UREALM
    else
      RT="`cat $REGISTER/system/openvpn/Domains/$LREALM/Type 2>/dev/null`"
      REALM=$LREALM
    fi
  fi
else
  if [ "`cat $REGISTER/system/openvpn/AutoProxy`" == yes ] && [ -f "$REGISTER/system/radius/proxy/realms/$REALM/Type" -o -f "$REGISTER/system/radius/proxy/realms/DEFAULT/Type" ] ; then
    RT=Radius
  else
    if [ "`cat $REGISTER/system/openvpn/AutoTrust`" == yes ] ; then
      RT=Trusted
    else
      logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Authentication failed: Domain $REALM not authorized" >&2
      exit 18
    fi
  fi
fi
FULL=$USER@$REALM
if [ "$RT" == Radius ] ; then
  RADIUSREQ="`cat $REGISTER/system/openvpn/Domains/$REALM/RadiusReq 2>/dev/null`"
  if [ -z "$RADIUSREQ" ] ; then
    RADIUSREQ="`cat $REGISTER/system/openvpn/RadiusReq 2>/dev/null`"
    [ -z "$RADIUSREQ" ] && RADIUSREQ="PAP"
  fi

  TMPERR=/tmp/radiusauth_err.$$
  logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Trying Radius authentication ($RADIUSREQ)"
  if ! $SCRIPTS/radiusauth "$USER@$REALM" "$PW" "$RADIUSREQ" 2>"$TMPERR" ; then
    logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Radius authentication ($RADIUSREQ) failed for $FULL: View Radius log for further details"
    rm -f "$TMPERR"
    exit 20
  fi
  LCODE=`cat "$TMPERR" 2>/dev/null`
  rm -f "$TMPERR"
  if [ "$LCODE" = "LCode:E" ] ; then
     logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Radius authentication ($RADIUSREQ) failed for $FULL: Account Expired"
     exit 21
  fi  
else
  REALM=$UREALM
  logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Trying Kerberos 5 ($RT KDC) authentication"
  export KRB5CCNAME="FILE:/tmp/krb5cc_${USER}_${REALM}_$$"
  kdestroy 2>/dev/null
  if ! echo "$PW" | kinit "$USER@$REALM" >/dev/null 2>/tmp/ov$$.err ; then
    kdestroy 2>/dev/null
    logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Kerberos 5 authentication failed for $FULL: `sed 's/\r//g' /tmp/ov$$.err`"
    rm -f /tmp/ov$$.err 
    exit 10
  fi
  rm -f /tmp/ov$$.err
  HOSTNAME=`cat $REGISTER/system/misc/hostname`
  if [ "$RT" != External ] ; then
    if ! kvno "host/$HOSTNAME" 2>/tmp/ov$$.err ; then
      kdestroy 2>/dev/null
      logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Kerberos 5 authentication failed: `sed 's/\r//g' /tmp/ov$$.err`"
      rm -f /tmp/ov$$.err
      exit 11
    fi
  fi
  rm -f /tmp/ov$$.err
  kdestroy 2>/dev/null
fi
logger -t VPN99_H2L "$untrusted_ip:$untrusted_port [$FULL] Successfully authenticated"
exit 0
