#!/bin/sh
. /etc/kerbynet.conf
DOMAIN="$1"
TYPE="$2"
RADIUSREQ="$3"
[ -z "$DOMAIN" -o -z "$TYPE" ] && exit 1
CONFIG=$REGISTER/system/openvpn/Domains
cd "$CONFIG" || exit 2
[ "$TYPE" == Radius ] && DOMAIN=`echo $DOMAIN | awk '{print tolower($0)}'`
if [ -d "$DOMAIN" ] ; then
  echo "the domain already exists" >&2  
  exit 10
fi
mkdir "$DOMAIN"
echo "$TYPE" > "$DOMAIN/Type"
echo "$RADIUSREQ" > "$DOMAIN/RadiusReq"


