#!/bin/sh
. /etc/kerbynet.conf
DOMAIN="$1"
[ -z "$DOMAIN" ] && exit 1
CONFIG=$REGISTER/system/openvpn/Domains
cd "$CONFIG" || exit 2
if [ -d "$DOMAIN" ] ; then
  find . -type f -name 'Default' -exec rm -f {} \;
  touch $DOMAIN/Default
  echo "$DOMAIN" > $REGISTER/system/openvpn/DefaultDomain
else
  exit 3
fi



