#!/bin/sh
. /etc/kerbynet.conf
DOMAIN="$1"
[ -z "$DOMAIN" ] && exit 1
CONFIG=$REGISTER/system/openvpn/Domains
cd "$CONFIG" || exit 2
if [ -d "$DOMAIN" ] ; then
  rm -rf "$DOMAIN"
  if [ "`cat $REGISTER/system/openvpn/DefaultDomain 2>/dev/null`" == "$DOMAIN" ] ; then
    rm -f $REGISTER/system/openvpn/DefaultDomain
  fi
else
  exit 3
fi



