#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
HOST="$1"
PACKETSIZE="$2"
[ -z "$HOST" ] && exit 1
IP="`gethostbyname $HOST`"
if ! [ -z "$IP" ] ; then 
    if ! ping -n -c3 -w10 -s$PACKETSIZE $IP ; then
      exit 2
    fi
else
    exit 5
fi
