#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
 echo "Interface $INTERFACE doesn't exist." 1>&2
 exit 2
fi
if ifconfig $INTERFACE 2>/dev/null >/dev/null ; then
  echo Already started
  exit
fi
$SCRIPTS/pppoe_config $INTERFACE
FILE="/tmp/pppoe-$INTERFACE.conf"
if ! ps -ef |grep pppoe-connect | grep -q $INTERFACE ; then
  pppoe-start $FILE
fi
