#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
 echo "Interface $INTERFACE doesn't exist." 1>&2
 exit 2
fi
FILE="/tmp/pppoe-$INTERFACE.conf"
pppoe-stop $FILE 2> /dev/null >/dev/null
while ps -ef |grep pppd |grep -q $INTERFACE ; do
  kill `ps -ef |grep pppd |grep $INTERFACE|awk '{print $2}'` 2> /dev/null
  sleep 1
done
while ps -ef |grep pppoe-connect |grep -q $INTERFACE ; do
  kill `ps -ef |grep pppoe-connect |grep $INTERFACE|awk '{print $2}'` 2>/dev/null
  sleep 1
done
exit 0
