#!/bin/sh
. /etc/kerbynet.conf
OBJECT="$1"
[ -z "$OBJECT" ] && exit 1
CONFIG=$REGISTER/system/havp/redirects
cd "$CONFIG" || exit 2
if [ -d "$OBJECT" ] ; then
  rm -rf "$OBJECT"
else
  exit 3
fi
$SCRIPTS/proxy_fw



