#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/havp/redirects
cd "$CONFIG" || exit 0

OBJECTS=`ls -d * 2>/dev/null`
for O in $OBJECTS ; do
  ACTION=`cat $O/Action`
  INTERFACE=`cat $O/Interface`
  DESTINATIONIP=`cat $O/DestinationIP`
  SOURCEIP=`cat $O/SourceIP`
  OBJECT=""
  if [ "$ACTION" != Capture ] ; then
    ACTION="Not Capture"
  fi
  if [ -n "$INTERFACE" ] ; then
    VLAN=`echo $INTERFACE | awk -F. '{print $2}'`
    if [ -n "$VLAN" ] ; then
      INTERFACE=`echo $INTERFACE | awk -F. '{printf "%s vlan %s",$1,$2}'`
    fi
    OBJECT="$INTERFACE "
  fi
  if [ -n "$SOURCEIP" ] ; then
    OBJECT="${OBJECT}src:$SOURCEIP "
  fi 
  if [ -n "$DESTINATIONIP" ] ; then
    OBJECT="${OBJECT}dst:$DESTINATIONIP"
  fi 
  echo "<tr><td align=center><input type=radio name=Sel value='$O'</td><td>&nbsp;$OBJECT</td><td align=center nowrap>$ACTION</td></tr>"
done
