#!/bin/sh
. /etc/kerbynet.conf
cd $REGISTER/system/radius/proxy/realms || exit 1
REALMS=`ls -d * 2>/dev/null`
for R in $REALMS ; do
   SERVERS=`( cd $R ; ls -d [0123456789][0123456789] 2>/dev/null )`
   if [ "`echo $SERVERS | wc -w`" -gt 1 ] ; then
     if [ "`cat $R/LB 2>/dev/null`" == yes ] ; then
       LB=" (LB)"
     else
       LB=""
     fi
   else
     LB=""
   fi
   echo "<tr align=center>"
   echo "<td>"
   for S in $SERVERS ; do
     echo "<input type=radio Name=Sel value='$R/$S'></br>"
   done
   echo "</td>"
   echo "<td>$R</td>"
   echo "<td>"
   for S in $SERVERS ; do
     SERVER=`cat $R/$S/Server 2>/dev/null`
     if [ "`cat $R/$S/NoStrip 2>/dev/null`" == yes ] ; then
       STRIP=" (NS)"
     else
       STRIP=""
     fi
     echo "$SERVER$LB$STRIP</br>"
   done
   echo "</td>"
   echo "<td>"
   for S in $SERVERS ; do
     AUTHPORT=`cat $R/$S/AuthPort 2>/dev/null`
     echo "$AUTHPORT</br>"
   done
   echo "</td>"
   echo "<td>"
   for S in $SERVERS ; do
     ACCTPORT=`cat $R/$S/AcctPort 2>/dev/null`
     echo "$ACCTPORT</br>"
   done
   echo "</td>"
   echo "<td>"
   for S in $SERVERS ; do
     SECRET=`cat $R/$S/Secret 2>/dev/null`
     echo "$SECRET</br>"
   done
   echo "</td>"
   echo "<td>"
   for S in $SERVERS ; do
     ACCT=`cat $R/$S/Acct 2>/dev/null`
     [ -z "$ACCT" ] && ACCT=no
     echo "$ACCT</br>"
   done
   echo "</td>"
   echo "</tr>"

done




