#!/bin/sh
. /etc/kerbynet.conf
ENABLED=`cat $REGISTER/system/havp/Enabled`
if [ "$ENABLED" == yes ] ; then
  if ps -e | grep -w -q proxy_start 2>/dev/null ; then
    echo "<font color=#FF6600>STARTING ...</font>"
    exit
  fi
fi
if pidof havp >/dev/null ; then  
  echo "<font color=#00b000>ACTIVE</font>"
else
  echo "<font color=#ff0000>DOWN</font>"
fi
