#!/bin/sh
. /etc/kerbynet.conf
cd $REGISTER/system/radius/proxy/realms || exit 1
REALMS=`ls -d * 2>/dev/null | grep -v DEFAULT`
[ -d DEFAULT ] && REALMS="$REALMS DEFAULT"
for R in $REALMS ; do
   SERVERS=`( cd $R ; ls -d [0123456789][0123456789] 2>/dev/null )`
   TYPE="`cat $R/Type 2>/dev/null`"
   LB="`cat $R/LB 2>/dev/null`"
   for S in $SERVERS ; do
     echo "realm $R {"
     echo "  type = radius"
     AUTHPORT=`cat $R/$S/AuthPort 2>/dev/null`
     ACCTPORT=`cat $R/$S/AcctPort 2>/dev/null`
     SECRET=`cat $R/$S/Secret 2>/dev/null`
     SERVER=`cat $R/$S/Server 2>/dev/null`
     NOSTRIP="`cat $R/$S/NoStrip 2>/dev/null`"
     ACCT="`cat $R/$S/Acct 2>/dev/null`"
     if [ "$SERVER" == LOCAL ] ; then
        echo "  authhost = LOCAL"
        echo "  accthost = LOCAL"
     else
        echo "  authhost = $SERVER:$AUTHPORT"
        if [ "$ACCT" = yes ] ; then
         echo "  accthost = $SERVER:$ACCTPORT"
   	else
          echo "  accthost = LOCAL"
	fi
     fi
     if [ "$TYPE" != Local ] ; then
       echo "  secret = $SECRET" 
       [ "$NOSTRIP" == yes ] && echo "  nostrip"
       [ "$LB" == yes ] && echo "  ldflag = round_robin"
     fi
     echo "}"
   done
done




