#!/bin/sh
. /etc/kerbynet.conf
function ResetDB {
  logger -t proxy "RESETTING VIRUS DATABASE."
  rm -rf $REGISTER/system/ClamAV/db/ 
  mkdir -p $REGISTER/system/ClamAV/db
  if ! cp /usr/local/share/clamav/main.cvd $REGISTER/system/ClamAV/db ; then
    logger -t proxy "ERROR: Virus database corrupted. Check the profile disk space."
  fi
  chown -R havp $REGISTER/system/ClamAV/db
}
ENABLED=`cat $REGISTER/system/havp/Enabled`
$SCRIPTS/proxy_fw_reset
$SCRIPTS/terminate havp
rm -rf $REGISTER/system/havp/clamav.tmp/* $REGISTER/system/havp/tmp/*
if [ "$ENABLED" == yes ] ; then
  RELEASE=`$SCRIPTS/release`
  PATCHLEVEL=`$SCRIPTS/patchlevel`
  export PATH=/Database/opt/$RELEASE/$PATCHLEVEL/packages/bin/:/Database/opt/$RELEASE/$PATCHLEVEL/packages/sbin/:$PATH
  export LD_LIBRARY_PATH=/Database/opt/$RELEASE/$PATCHLEVEL/packages/lib/:$LD_LIBRARY_PATH
  if ! mount |grep -w /DB |grep dev/ |grep -q "mand" ; then
    mount -o remount,mand /DB
  fi
  if ! mount |grep /Database |grep -q "mand" ; then
    mount -o remount,mand /Database
  fi
  export QUERY_STRING="onlyrender"
  if [ "`cat $REGISTER/system/havp/AccessLog 2>/dev/null`" == OnlyVirus ] ; then
    export LOG_OKS=false
  else
    export LOG_OKS=true
  fi 
  if [ "`cat $REGISTER/system/havp/WhiteList 2>/dev/null`" == yes ] ; then
    export WHITELIST=$REGISTER/system/havp/WhiteList.txt
  else
    export WHITELIST=/dev/null
  fi 
  if [ "`cat $REGISTER/system/havp/BlackList 2>/dev/null`" == yes ] ; then
    export BLACKLIST=$REGISTER/system/havp/BlackList.txt
  else
    export BLACKLIST=/dev/null
  fi 
  if [ "`cat $REGISTER/system/ClamAV/VirusCheck 2>/dev/null`" == Enabled ] ; then
    export MAXSCANSIZE=5000000
  else
    export MAXSCANSIZE=1
  fi
  if [ "`cat $REGISTER/system/ClamAV/CheckImages 2>/dev/null`" == yes ] ; then
    export SCANIMAGES=true
  else
    export SCANIMAGES=false
  fi
  MEMORY=`cat /proc/meminfo |grep ^MemTotal: |awk '{print $2}'`
  export SERVERNUMBER=$((MEMORY/20000))
  if [ "$SERVERNUMBER" -lt 8 ] ; then
    export SERVERNUMBER=8
  fi
  if [ "$SERVERNUMBER" -gt 120 ] ; then
    export SERVERNUMBER=120
  fi
  render $TEMPLATE/havp.config > /tmp/havp.config
  if ! ls $REGISTER/system/ClamAV/db/main.* 2>/dev/null >/dev/null ; then
    ResetDB
  fi
  if havp -c /tmp/havp.config >/dev/null 2>/dev/null ; then
    $SCRIPTS/proxy_fw
    if ! ls $REGISTER/system/havp/redirects/* 2>/dev/null >/dev/null ; then
       logger -t proxy "WARNING: No HTTP capturing rules defined."
    fi
  else
    ResetDB
    if havp -c /tmp/havp.config >/dev/null 2>/dev/null ; then
      $SCRIPTS/proxy_fw
      if ! ls $REGISTER/system/havp/redirects/* 2>/dev/null >/dev/null ; then
        logger -t proxy "WARNING: No HTTP capturing rules defined."
      fi
    fi  
  fi
fi
