#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
TYPE="$1"
STk="`rand``cat /tmp/STk_Admin 2>/dev/null`"
if [ -z "`cat /tmp/QoSNotSaved 2>/dev/null`" ] ; then
  NOTSAVED="false"
else
  NOTSAVED="true"
fi
if ! [ -d "$REGISTER/system/net/QoS/Class/" ] ; then
  mkdir -p "$REGISTER/system/net/QoS/Class/"
  $SCRIPTS/qos_cm_save 'DEFAULT' 'Default class for unclassified traffic' '' 'Mbit/s' '' 'Mbit/s' '1' >/dev/null
  echo 2000 > "$REGISTER/system/net/QoS/Quantum"
fi
mkdir -p "$QDIR/Class/" 2>/dev/null

CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG

if [ -n "$TYPE" ] ; then
  export ${TYPE}SELECTED=selected
  INTERFACES=`ls -d $TYPE* |sort -f`
else
  INTERFACES=`ls -d ETH* 2>/dev/null`
  INTERFACES="$INTERFACES `ls -d WLAN* 2>/dev/null`"
  INTERFACES="$INTERFACES `ls -d ppp* 2>/dev/null`"
  INTERFACES="$INTERFACES `ls -d BRIDGE* 2>/dev/null`"
  INTERFACES="$INTERFACES `ls -d BOND* 2>/dev/null`"
  INTERFACES="$INTERFACES `ls -d VPN* 2>/dev/null`"
fi
cat << EOF
<html><head><link rel=stylesheet type=text/css href=/default.css><title>QoS List</title>
<meta Http-Equiv="Cache-Control" Content="no-cache">
<meta Http-Equiv="Pragma" Content="no-cache">
<meta Http-Equiv="Expire" Content="0">
<style type="text/css">
.MkBT {
  width: 90;
  font-size: 10;
}
</style>
<script>
function NotSaved(Enabled) {
  X=document.data;
  X.Activate.disabled=!Enabled;
  if (Enabled) {
    document.getElementById("NotSaved").innerHTML="<b><font color=#ff0000>Warning: last changes are not active</font></b>";
  } else {
    document.getElementById("NotSaved").innerHTML="";
  }
}
function SelectType() {
   location="kerbynet?Section=QoS&STk=$STk&Action=List&Type="+document.data.TYPE.value;
}
</script>
</head><body>
<form name=data>
<table width=100%><tr>
<td nowrap>Show 
<select name=TYPE onchange='SelectType()' style="font-size: 10;">
<option value="" $ALLSELECTED>ALL
<option value=ETH $ETHSELECTED>ETHERNET
<option value=WLAN $WLANSELECTED>Wi-Fi
<option value=VPN $VPNSELECTED>VPN
<option value=BRIDGE $BRIDGESELECTED>BRIDGE
<option value=BOND $BONDSELECTED>BOND
<option value=ppp $pppSELECTED>PPPoE
</select>
</td>
<td align=right nowrap id="NotSaved"></td>
<td align=right nowrap width=1%>&nbsp;&nbsp;&nbsp;
<input type=button name=Activate value="Activate last Changes" onclick='location="kerbynet?Section=QoS&STk=$STk&Action=ActivateNewConfig&Type="+document.data.TYPE.value'>&nbsp;
<input type=button value="Refresh" onclick='location="kerbynet?Section=QoS&STk=$STk&Action=List&Type="+document.data.TYPE.value'>
</td>
</tr></table>
<script> NotSaved($NOTSAVED);</script>
<table width=100%>
EOF
for i in $INTERFACES ; do
   echo "<tr><td><hr>"
   echo "<iframe width=100% height=200 border=0 frameborder=0 src='kerbynet?Section=QoS&STk=$STk&Action=ShowInterface&Interface=$i'>Browser not compatible</iframe>"
   echo "</td></tr>"
done
echo "</table>"
echo "</form></body></html>"
