#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
CLASS="$2"
[ -z "$INTERFACE" -a -z "$CLASS" ] && exit 1
NOTSAVED="`cat /tmp/QoSNotSaved 2>/dev/null`"
if [ -n "$INTERFACE" ] ; then
   if [ "$CLASS" != check ] ; then 
     if ! echo "$NOTSAVED" | grep -w -q "$INTERFACE" ; then
       echo "$INTERFACE" >> /tmp/QoSNotSaved
     fi
   else
     if echo "$NOTSAVED" | grep -w -q "$INTERFACE" ; then
       echo "&nbsp;&nbsp;Changes not active&nbsp;&nbsp;"
     fi
   fi 
else
  DIR="$REGISTER/system/net/interfaces"
  cd "$DIR"
  INTERFACES="`ls`"
  for I in $INTERFACES ; do
    if [ -d "$DIR/$I/QoS/Class/$CLASS" ] ; then
      if ! echo "$NOTSAVED" | grep -w -q "$I" ; then
        echo "$I" >> /tmp/QoSNotSaved
      fi
    fi
  done
fi
