#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
CLASS="$2"
[ -z "$INTERFACE" -o -z "$CLASS" ] && exit 1
#DIR="$REGISTER/system/net/interfaces/$INTERFACE/QoS/Class/$CLASS"
LOCAL="`cat $DIR/Local 2>/dev/null`"
#if [ "$LOCAL" != yes ] ; then
#  DIR="$REGISTER/system/net/QoS/Class/$CLASS"
#fi
DIR="$REGISTER/system/net/QoS/Class/$CLASS"
DSCP="`cat $DIR/DSCP 2>/dev/null`"
echo "$DSCP"

