#!/bin/sh
. /etc/kerbynet.conf
NAME="$1"
STATUS="$2"
[ -z "$NAME" ] && exit 1
CDIR="$REGISTER/system/net/QoS/Class/$NAME"
if [ "$STATUS" == enable ] ; then
  echo yes > "$CDIR/Enabled"
else
  echo no > "$CDIR/Enabled"
fi
