#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
[ -z "$INTERFACENAME" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces"
INTERFACE=$INTERFACENAME
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
QDIR="$IDIR/QoS"
mkdir -p "$QDIR/Class/" 2>/dev/null
if ! [ -d "$QDIR/Class/DEFAULT/" ] ; then
  mkdir "$QDIR/Class/DEFAULT/"
  MAX=`$SCRIPTS/qos_detectSpeed $INTERFACENAME`
  echo "$MAX" > "$QDIR/Max"
  echo "Mbit/s" > "$QDIR/MaxUnit"
  echo "$MAX" > "$QDIR/Guaranteed"
  echo "Mbit/s" > "$QDIR/GuaranteedUnit"
  echo "yes" > "$QDIR/Class/DEFAULT/Enabled" 
fi

STk="`rand``cat /tmp/STk_Admin 2>/dev/null`"
echo "<html><head><link rel=stylesheet type=text/css href=/default.css><title>$INTERFACENAME</title>"
echo "<script>InterfaceName='$INTERFACENAME';STk='$STk';</script>"
cat <<EOF
<meta http-equiv="Pragma" content="no-cache">
<script language=javascript>
function OnOff() {
  X=document.data;
  if (X.Enabled.checked) {
     ACT="enable";
  } else {
     ACT="disable";
  }
  if (confirm("Are you sure you want to "+ACT+" the QoS for the interface "+InterfaceName+"?")) {
    location="kerbynet?Section=QoS&STk="+STk+"&Action=InterfaceChangeStatus&Interface="+InterfaceName+"&Status="+ACT;
  } else {
    X.Enabled.checked=!X.Enabled.checked;
  }

}
function ClassOnOff(obj) {
  if (obj.value=="DEFAULT") {
    obj.checked=true;
    alert("You cannot disable the DEFAULT QoS Class.");
    return;
  }
  if (obj.checked) {
     ACT="enable";
  } else {
     ACT="disable";
  }
  if (confirm("Are you sure you want to "+ACT+" the QoS class "+obj.value+" for the interface "+InterfaceName+"?")) {
    location="kerbynet?Section=QoS&STk="+STk+"&Action=ClassChangeStatus&Interface="+InterfaceName+"&QoSClass="+obj.value+"&Status="+ACT;
  } else {
    obj.checked=!obj.checked;
  }

}
function GlobalBW() {
  newwin=open("kerbynet?Section=QoS&STk="+STk+"&Action=GlobalBW&Interface="+InterfaceName,"QoSGBW","top=350,left=500,width=350,height=200,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
  newwin.focus();
}
function SelectedClass() {
   var i;
   X=document.data;
   if (X.QoSClass.length!=undefined) {
      for (i=0; i<X.QoSClass.length; i++)  {
         if (X.QoSClass[i].checked=="1") {
            return X.QoSClass[i].value;
         }
      }
   }
   if (X.QoSClass!=undefined) {
     if (X.QoSClass.checked=="1") {
       return X.QoSClass.value;
     }
   }
   return "";
}
function AddClass() {
  newwin=open("kerbynet?Section=QoS&STk="+STk+"&Action=AddClass&Interface="+InterfaceName,"QoSClassAdd","top=350,left=500,width=450,height=300,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
  newwin.focus();
}
function ChangeClass() {
  QosClass=SelectedClass();
  if (QosClass=="") {
    alert("You should select a Qos Class to modify.");
    return;
  }
  newwin=open("kerbynet?Section=QoS&STk="+STk+"&Action=ChangeClass&Interface="+InterfaceName+"&QoSClass="+QosClass,"QoSChangeClass","top=350,left=450,width=450,height=300,scrollbars=no,menubar=no,toolbar=no,statusbar=no");
  newwin.focus();
}
function DeleteClass() {
  QosClass=SelectedClass();
  if (QosClass=="") {
    alert("You should select a Qos Class to remove.");
    return;
  }
  if (QosClass=="DEFAULT") {
    alert("You cannot remove the DEFAULT QoS Class.");
    return;
  }
  if (confirm("Are you sure you want to remove the selected Class?")) {
    location="kerbynet?Section=QoS&STk="+STk+"&Action=DeleteClass&Interface="+InterfaceName+"&QoSClass="+QosClass;
  }
}
</script>
EOF
echo "</head><body><form name=data method=post action=kerbynet>"
echo "<table width=100%><tr><td valign=top>"
echo '<table width=100% border=1 style="border-collapse: collapse;" cellspacing=0 cellpadding=0><tr>'
echo "<td>&nbsp;"
if [ "${INTERFACE:0:6}" == BRIDGE ] ; then
   COMPONENTS="<font class=Smaller1>(`ext_bridgename $INTERFACE`)</font>"
fi
if [ "${INTERFACE:0:4}" == BOND ] ; then
   COMPONENTS="<font class=Smaller1>(`ext_bondname $INTERFACE`)</font>"
fi
echo "<font color=#2020c0><b>`echo $INTERFACE |awk '{print toupper($0)}'` $COMPONENTS</b></font>"
echo "<font color=#00b000>&nbsp;&nbsp;"
$SCRIPTS/getlinkstatus $INTERFACE
echo "</font>"
echo "<br><font color=#0000d0>&nbsp;"
cat $IDIR/Description
echo "</font></td><td align=right width=1%>"
ENABLED=`cat $QDIR/Enabled 2>/dev/null`
if [ "$ENABLED" == yes ] ; then
   CHECKED=checked
   ST="Enabled"
else
   CHECKED=""
   ST="<font color=#ff0000>Disabled</font>"
fi
echo "<center><font color=#00A000><b>On</b></font><br><input type=checkbox name=Enabled value=yes $CHECKED onclick='OnOff()'></center>"
echo "</td></tr></table>"
if ! [ -r $IDIR/Bridge/Name -o -r $IDIR/Bond/Name ] ; then
  :
else
  if  [ -r $IDIR/Bond/Name ] ; then
    BOND=`cat $IDIR/Bond/Name`
    echo "<table width=100%><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color=#707070>This device is member of $BOND <font class=Smaller1>(`ext_bondname $BOND`)</font></font></td><td align=right><font color=#707070></td></tr></table>"
    BONDED=true
  else
    BRIDGE=`cat $IDIR/Bridge/Name`
    echo "<table width=100%><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color=#707070>This device is member of $BRIDGE <font class=Smaller1>(`ext_bridgename $BRIDGE`)</font></font></td><td align=right><font color=#707070></td></tr></table>"
    BRIDGED=true
  fi
fi
MAX="`cat $QDIR/Max 2>/dev/null`"
MAXUNIT="`cat $QDIR/MaxUnit 2>/dev/null`"
GUARANTEED="`cat $QDIR/Guaranteed 2>/dev/null`"
GUARANTEEDUNIT="`cat $QDIR/GuaranteedUnit 2>/dev/null`"
if [ "$GUARANTEEDUNIT" == "Mbit/s" ] ; then
  GK=`echo $GUARANTEED | awk '{print $0 * 1024}'`
else
  GK="$GUARANTEED"
fi
ASSIGNED="`$SCRIPTS/qos_tot_guaranteed $INTERFACE`"
PERC_ASSIGNED=`echo $GK $ASSIGNED | awk '{printf("%d",$2/$1*100)}'`
if [ "$PERC_ASSIGNED" -gt 100 ] ; then
  PERC_ASSIGNED="<font color=#FF0000><b>${PERC_ASSIGNED}%</b></font>"
else
  PERC_ASSIGNED="${PERC_ASSIGNED}%"

fi

echo "<font color=#808080>&nbsp;&nbsp;QoS Status:$ST&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max:$MAX$MAXUNIT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Guaranteed:$GUARANTEED$GUARANTEEDUNIT&nbsp;&nbsp;(Assigned:$PERC_ASSIGNED)</font>"



echo "<table width=100% bordercolor=#FFFFFF border=1 cellspacing=0 cellpadding=0>"
echo "<tr bgcolor=#f0f0f0 style='color: #1010c0'><td nowrap width=1%>&nbsp;</td><td nowrap width=1%>&nbsp;<b>Class</b>&nbsp;</td><td>&nbsp;<b>Description</b></td><td nowrap width=1%>&nbsp;<b>Priority</b>&nbsp;</td><td nowrap width=1%>&nbsp;<b>DSCP</b>&nbsp;</td><td nowrap width=1%>&nbsp;<b>Max Bandwidth</b>&nbsp;</td><td nowrap width=1%>&nbsp;<b>Guaranteed</b>&nbsp;</td><td nowrap width=1%><b>On</b></td></tr>"
cd "$QDIR/Class"
CMDIR="$REGISTER/system/net/QoS/Class"
CLASSES=`ls`
for C in $CLASSES ; do
  NAME="$C"
  DESC="`cat $CMDIR/$C/Description`"
  MAX="`$SCRIPTS/qos_getbw "$INTERFACE" "$C" Max F`"
  GUARANTEED="`$SCRIPTS/qos_getbw "$INTERFACE" "$C" Guaranteed F`"  
  if [ -z "$MAX" ] ; then
    MAX="&nbsp;"
  fi
  if [ -z "$GUARANTEED" ] ; then
    GUARANTEED="&nbsp;"
  fi
  PRIORITY="`$SCRIPTS/qos_getpriority "$INTERFACE" "$C"`"  
  PRIORITY="`$SCRIPTS/qos_printpriority $PRIORITY`"
  DSCP="`$SCRIPTS/qos_getdscp "$INTERFACE" "$C"`"  
  ENABLED="`cat $C/Enabled`"
  if [ "$ENABLED" == yes ] ; then
     CHECKED=checked
  else
     CHECKED=""
  fi
  if [ "`$SCRIPTS/qos_ison $INTERFACE $C`" == yes ] ; then
    BGC="#f0f0f0"
  else
    BGC="#ffd0d0"
  fi
  echo "<tr bgcolor=$BGC><td width=1%><input type=radio name='QoSClass' value='$C'></td><td>&nbsp;$NAME&nbsp;</td><td>&nbsp;$DESC</td><td align=center>$PRIORITY</td><td align=center>$DSCP</td><td align=center>$MAX</td><td align=center>$GUARANTEED</td><td width=1%><input type=checkbox name=Enabled$C value=$C $CHECKED onclick='ClassOnOff(this)'></td></tr>"
done
cd $QDIR
echo "</table>"
echo "</td><td align=right valign=top><span style='background-color: #ff2020; color: #ffffff'><b>"
$SCRIPTS/qos_notsaved "$INTERFACE" check


echo "<b></span><br><br><input type=button value='Global Bandwidth' onclick='GlobalBW()'><br>"
echo "<br>"
echo "<input type=button value='Add Class' style='width: 100; font-size:10' onclick='AddClass()'><br>"
echo "<input type=button value='Modify Class' style='width: 100; font-size:10' onclick='ChangeClass()'><br>"
echo "<input type=button value='Remove Class' style='width: 100; font-size:10' onclick='DeleteClass()'><br>"
echo "</td></tr></table>"
echo "</form></body></html>"
