#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
CLASSNAME="$2"
LOCAL="$3"
PRIORITY="$4"
MAX="$5"
MAXUNIT="$6"
GUARANTEED="$7"
GUARANTEEDUNIT="$8"
DSCP="$9"
[ -z "$INTERFACE" -o -z "$CLASSNAME" ] && exit 1
CDIR="$REGISTER/system/net/interfaces/$INTERFACE/QoS/Class/$CLASSNAME"
echo "$LOCAL" > "$CDIR/Local"
if [ "$LOCAL" == yes ] ; then
  echo "$PRIORITY" > "$CDIR/Priority"
  echo "$MAX" > "$CDIR/Max"
  echo "$MAXUNIT" > "$CDIR/MaxUnit"
  echo "$GUARANTEED" > "$CDIR/Guaranteed"
  echo "$GUARANTEEDUNIT" > "$CDIR/GuaranteedUnit"
  echo "$DSCP" > "$CDIR/DSCP"
fi
