#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
CLASS="$2"
[ -z "$INTERFACE" ] && exit 1
if [ -z "$CLASS" ] ; then
  INDEX=1
else
  INDEX="`cat $REGISTER/system/net/QoS/Class/$CLASS/Index 2>/dev/null`"
fi
[ -z "$INDEX" ] && exit 2
TMP=/tmp/qos_stats_${INTERFACE}_$CLASS
tc -s class show dev $INTERFACE | grep -A4 "class htb 1:$INDEX " > $TMP
SENT="`grep "^ Sent " $TMP | awk '{print $2}'`"
RATE="`grep "^ rate " $TMP | awk '{print $2}'`"
echo $SENT:$RATE
rm -f $TMP
