#!/bin/sh
. /etc/kerbynet.conf
[ "`cat $REGISTER/system/acct/Enabled 2>/dev/null`" = yes ] || exit 0
USER_NAME=`echo $USER_NAME | sed -r 's/\"//g'`
REALM=`echo $REALM | sed -r 's/\"//g'|awk '{print toupper($0)}`
if [ -n "$REALM" -a "$REALM" != "`cat $REGISTER/system/k5/realm`" ] ; then
 exit 0
fi
if [ -z "$STRIPPED_USER_NAME" ] ; then
  export STRIPPED_USER_NAME=`echo "$USER_NAME" | cut -d@ -f1`
fi
STRIPPED_USER_NAME=`echo $STRIPPED_USER_NAME | sed -r 's/\"//g' | tr '[:upper:]' '[:lower:]'`
LIMITS=`$SCRIPTS/acct_userlimits "$STRIPPED_USER_NAME"`
LHOURS=`echo $LIMITS | cut -d: -f3`
LMB=`echo "$LIMITS" | cut -d: -f4`
LEXPIRE=`echo $LIMITS | cut -d: -f8`
LCREDIT=`echo "$LIMITS" | cut -d: -f9`
TO=""
TO1=""
if [ -n "$LHOURS" ] ; then 
  TIME=`cat "$REGISTER/system/acct/entries/$STRIPPED_USER_NAME/Time" 2>/dev/null`
  [ -z "$TIME" ] && TIME=0
  TO=`echo "$LHOURS" "$TIME" | awk '{printf "%d",3600*$1-$2}'`
fi
if [ "$LEXPIRE" != 24836 -a -n "$LEXPIRE" ] ; then
  TMP="`date +'%F %X'`"
  NOW=`date -u +%s -d "$TMP"`
  TO1=$((LEXPIRE*86400-NOW+86400))
fi
if [ -n "$TO1" ] ; then
  if [ -n "$TO" ] ; then
     [ $TO1 -lt $TO ] && TO="$TO1"
  else
     TO="$TO1"
  fi
fi
TRAFFIC=`cat "$REGISTER/system/acct/entries/$STRIPPED_USER_NAME/MB" 2>/dev/null`
LIMITSOK=`$SCRIPTS/acct_isLimitsOK "$LHOURS" "$LMB" "$LEXPIRE" "$LCREDIT" "$TRAFFIC" "$TIME" "$NOW"`
if [ -n "$LIMITSOK" ] ; then 
  TO=0
  logger -t Accounting "Connection limit reached by the user $USER_NAME (`$SCRIPTS/acct_limit_msg $LIMITSOK`)"
fi
if [ -n "$TO" ] ; then
    [ "$TO" -lt 0 ] && TO=1
    echo "Reply-Message = $LIMITS:$LIMITSOK , Session-Timeout = $TO"
else
    echo "Reply-Message = $LIMITS:$LIMITSOK"
fi
