#!/bin/sh
. /etc/kerbynet.conf
REALM="$1"
NUMSERVER="$2"
[ -z "$REALM" ] && exit 1
[ -z "$NUMSERVER" ] && exit 2
cd $REGISTER/system/radius/proxy/realms || exit 1
rm -rf "$REALM/$NUMSERVER"
cd $REALM 
if [ -z "`ls -d [0123456789][0123456789] 2>/dev/null`" ] ; then
  cd ..
  rm -rf "$REALM"
fi
$SCRIPTS/radius_start
