#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
NAME="$1"
[ -z "$NAME" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
if [ -f "$CONFIG/$NAME/Bridge/Name" ] ; then
  BRIDGE=`cat $CONFIG/$NAME/Bridge/Name`
  BRIDGEDLIST=`cat  $CONFIG/$BRIDGE/BridgeList 2>/dev/null`
  EBRIDGEDLIST=""
  if echo $BRIDGEDLIST | grep -q -w $NAME ; then
    for B in $BRIDGEDLIST ; do
      if [ "$B" != "$NAME" ] ; then
        EBRIDGEDLIST="$EBRIDGEDLIST $B"
      fi
    done
    echo $EBRIDGEDLIST > $CONFIG/$BRIDGE/BridgeList
  fi
fi
if [ -f "$CONFIG/$NAME/Bond/Name" ] ; then
  BOND=`cat $CONFIG/$NAME/Bond/Name`
  BONDLIST=`cat  $CONFIG/$BOND/BondList 2>/dev/null`
  EBONDLIST=""
  if echo $BONDLIST | grep -q -w $NAME ; then
    for B in $BONDLIST ; do
      if [ "$B" != "$NAME" ] ; then
        EBONDLIST="$EBONDLIST $B"
      fi
    done
    echo $EBONDLIST > $CONFIG/$BOND/BondList
  fi
fi
rm -rf "$CONFIG/$NAME"
