#!/bin/sh
. /etc/kerbynet.conf
function getconf() {
  CONF="$1"
  if [ -r $2/RIP/Enabled ] ; then
    CONF="$CONF~yes"
  else
    CONF="$CONF~no"
  fi
  if [ -r $2/RIP/SplitHorizon ] ; then
    CONF="$CONF~`cat $2/RIP/SplitHorizon`"
  else
    CONF="$CONF~no"
  fi
  if [ -r $2/RIP/PoisonedReverse ] ; then
    CONF="$CONF~`cat $2/RIP/PoisonedReverse`"
  else
    CONF="$CONF~no"
  fi
  if [ -r $2/RIP/PassiveMode ] ; then
    CONF="$CONF~`cat $2/RIP/PassiveMode`"
  else
    CONF="$CONF~no"
  fi
  if [ -r $2/RIP/Authentication ] ; then
    CONF="$CONF~`cat $2/RIP/Authentication`"
  else
    CONF="$CONF~no"
  fi
  if [ -r $2/RIP/Secret ] ; then
    CONF="$CONF~`cat $2/RIP/Secret`"
  else
    CONF="$CONF~"
  fi
  echo $CONF
}
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls`
for I in $INTERFACES ; do
   cd $CONFIG
   if ! [ -d $I/Bridge/ -o -d $I/Bond/ ] ; then
     ALL="$ALL|`getconf $I $I`"
   fi
   if [ -d "$I/VLAN" ] ; then
      cd $I/VLAN
      VLANS=`ls`
      for V in $VLANS ; do
        ALL="$ALL|`getconf $I.$V $V`"
      done
   fi
done
if [ "${ALL:0:1}" == "|" ] ; then
  ALL="${ALL:1}"
fi
echo $ALL


