#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/router/PAT"
if ! [ -d "$CONFIG" ] ; then
   mkdir "$CONFIG"
fi 
cd $CONFIG
ENTRIES=`ls 2>/dev/null`
for E in $ENTRIES ; do
  INTERFACE="`cat $E/Interface`"
  [ "$INTERFACE" = ALL ] && INTERFACE=ANY 
  VIRTUALIP="`cat $E/VirtualIP 2>/dev/null`" 
  [ -z "$VIRTUALIP" ] && VIRTUALIP=ANY 
  PROT="`cat $E/Protocol`" 
  LOCALPORT="`cat $E/LocalPort`" 
  REMOTEIP="`cat $E/RemoteIP`" 
  REMOTEPORT="`cat $E/RemotePort`" 
  echo "<tr><td align=center><input type=radio name=Entry value='$E'></td><td align=center>`echo $INTERFACE | sed 's/\./ vlan /'` / $VIRTUALIP</td><td align=center>`echo $PROT|awk '{print toupper($1)}'`</td><td align=center>$LOCALPORT</td><td align=center>$REMOTEIP:$REMOTEPORT</td></tr>"
done

