#!/bin/sh
. /etc/kerbynet.conf
RouteType="${1}"
Dest="${2}"
Netmask="${3}"
Via="${4}"
Gateway="${5}"
Metric="${6}"
Interface="${7}"
Entry="${8}"
CONFIG="$REGISTER/system/net/router"
[ -z "$Entry" ] && exit 1
if ! [ -d "$CONFIG/Statics/$Entry" ] ; then
  echo "No entry to change" 1>&2
  exit 21
fi
rm -rf "/tmp/$Entry"
cp -a "$CONFIG/Statics/$Entry" /tmp
$SCRIPTS/router_deletestatic "$Entry"
if ! $SCRIPTS/router_addstatic "$RouteType" "$Dest" "$Netmask" "$Via" "$Gateway" "$Metric" "$Interface" ; then
  mv "/tmp/$Entry" $CONFIG/Statics
  $SCRIPTS/routerconfig 2>/dev/null
  exit 20
fi
