#!/bin/bash
. /etc/kerbynet.conf
GW="$1"
OPT="$2"
CONFIG=$REGISTER/system/net/nb
cd $CONFIG/Gateways
if [ -z "$GW" ] ; then
  GW=`ls -d ?? 2>/dev/null`
  ANY=yes
else
  [ -d "$GW" ] || exit 1
  ANY=""
fi
[ -z "$GW" ] && exit 2
if [ "$OPT" == flush ] ; then
  for G in $GW ; do
    ip ro flush table 1$G 2>/dev/null
    ip ro flush table 2$G 2>/dev/null
    if ! ip ru show | grep -q "lookup 2$G" ; then
      ip rule add fwmark 2$G ta 2$G 
    fi
  done
fi
while read LINE ; do
  if echo "$LINE" | grep -w peer ; then
    if echo "$LINE" | grep -q ^Deleted ; then
      DEV=`echo "$LINE"|sed -r 's/.*global (.*)/\1/'`
      INET=`echo "$LINE"|sed -r 's/.*inet (.*) peer .*/\1/'`
      PEER=`echo "$LINE"|sed -r 's/.*peer (.*) scope .*/\1/'|awk -F / '{print $1}'`
      LINE="Deleted $PEER dev $DEV  proto kernel  scope link  src $INET"  
    fi
  fi
  if echo "$LINE" | egrep -q -v "Unknown|default|nexthop|table|lladdr|FAILED|tos|cache|_lft|link/ppp|:|127.0.0." ; then
    if echo "$LINE" | grep -i -w -q ^deleted ; then
      OP=del
      LINE=`echo $LINE | sed -r 's/.eleted//'`
    else
      OP=add
      ip ro sh | grep -q "^$LINE" || OP=noop
    fi
    if [ "$OP" == del ] || echo $LINE | egrep -q "^[0123456789]{1,3}\.[0123456789]{1,3}\.[0123456789]{1,3}\.[0123456789]{1,3}" && [ "$OP" != noop ] ; then
      if [ -n "$ANY" ] ; then
        GW=`ls -d ?? 2>/dev/null`
      fi
      SRC=`echo "$LINE" |grep -w "src"|sed -r 's/.* src (.*)$/\1/'` 
      DEV=`echo "$LINE" |grep -w "dev"|sed -r 's/.* dev (.*) proto .*/\1/'|sed 's/ //g'` 
      NET=`echo "$LINE" |grep  "/"|sed -r 's/^(.*) dev .*/\1/'|sed 's/ //g'`
      MASK=`echo "$NET" |awk -F / '{print $2}'`
      NET=`echo "$NET" |awk -F / '{print $1}'`
      
      for G in $GW ; do
        ip ro $OP $LINE ta 1$G 2>/dev/null
        ip ro $OP $LINE ta 2$G 2>/dev/null
        INTERFACE=`cat $G/Interface 2>/dev/null`
        IP=`cat $G/IP 2>/dev/null`
        ip ro del default ta 1$G 2>/dev/null
        ip ro del default ta 2$G 2>/dev/null
        if [ -n "$IP" ] ; then
          if ip ro add 127.0.0.99 via $IP metric 10 2>/dev/null ; then
            ip ro del 127.0.0.99 via $IP metric 10
            ip ro add default via $IP ta 1$G 2>/dev/null
            ip ro add default via $IP ta 2$G 2>/dev/null
          fi
	  if [ -n "$NET" ] ; then
            GWNET=`ipcalc -n $IP/$MASK | grep ^Network: |awk '{print $2}'`
            if [ "$GWNET" = "$NET/$MASK" ] ; then
              $SCRIPTS/nb_ct_pre $OP $G $SRC $DEV
            fi
          fi
        else
          ip ro add default dev $INTERFACE ta 1$G 2>/dev/null
          ip ro add default dev $INTERFACE ta 2$G 2>/dev/null
	  if [ -z "$NET" ] ; then
	    if [ "$DEV" = "$INTERFACE" ] ; then
                $SCRIPTS/nb_ct_pre $OP $G $SRC $DEV
            fi
	  fi
        fi
        ip ro add unreachable default metric 99 ta 1$G 2>/dev/null
        ip ro add unreachable default metric 99 ta 2$G 2>/dev/null
      done

    fi
    if [ "`cat $REGISTER/system/net/nb/Enabled 2>/dev/null`" == yes ] ; then
      $SCRIPTS/nb_setnexthop
    fi
  fi
done
exit 0
