#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
VIRTUALIP="$2"
PROTOCOL="$3"
LOCALPORT="$4"
REMOTEIP="$5"
REMOTEPORT="$6"
CONFIG="$REGISTER/system/net/router/PAT"
if ! [ -d "$CONFIG" ] ; then
   mkdir "$CONFIG"
fi
cd $CONFIG
E=`ls |sort|tail -1`
if [ -z "$E" ] ; then
  E=01
else
  if [ "${E:0:1}" == 0 ] ; then
     E=${E:1:1}
  fi
  E=`echo $((E+1)) | awk '{printf "%02s",$0 }'`
fi
mkdir "$CONFIG/$E"
echo $INTERFACE > $E/Interface
echo $VIRTUALIP > $E/VirtualIP
echo $PROTOCOL > $E/Protocol
echo $LOCALPORT > $E/LocalPort
echo $REMOTEIP > $E/RemoteIP
echo $REMOTEPORT > $E/RemotePort
if ! $SCRIPTS/router_patconfig $E ; then
  rm -rf "$CONFIG/$E"
  exit 1
fi
