#!/bin/sh
. /etc/kerbynet.conf
LOCALREALM=`cat $REGISTER/system/k5/realm`
kadmin.local -q listprincs | egrep "^krbtgt/" |egrep -v  "^krbtgt/$LOCALREALM@$LOCALREALM$" | sed -r "s/^krbtgt\/(.*)@(.*)$/\1:\2/" > /tmp/k5_trust_list
for T in `cat /tmp/k5_trust_list` ; do
  FIRST=`echo $T | awk -F: '{print $1}'`
  SECOND=`echo $T | awk -F: '{print $2}'`
  if [ "$FIRST" == "$LOCALREALM" -o "$SECOND" == "$LOCALREALM" ] ; then
    DIRECTION=""
    if [ "$FIRST" == "$LOCALREALM" ] ; then
      if ! egrep -q "^$SECOND:$FIRST$" < /tmp/k5_trust_list ; then
        DIRECTION=Outgoing
      fi
    fi
    if [ "$SECOND" == "$LOCALREALM" ] ; then
      if egrep -q  "^$SECOND:$FIRST$" < /tmp/k5_trust_list ; then
        DIRECTION=Bidirectional
      else
        DIRECTION=Incoming
      fi
    fi



    if [ "$DIRECTION" == Outgoing ] ; then 
      echo "<option value='$SECOND'>$LOCALREALM --> $SECOND [Outgoing]</option>"
    fi
    if [ "$DIRECTION" == Incoming ] ; then 
      echo "<option value='$FIRST'>$FIRST --> $LOCALREALM [Incoming]</option>"
    fi
    if [ "$DIRECTION" == Bidirectional ] ; then 
      echo "<option value='$FIRST'>$FIRST <--> $LOCALREALM [Bidirectional]</option>"
    fi



  fi
done

