#!/bin/sh
. /etc/kerbynet.conf
A=""
for A in `cat $REGISTER/system/openvpn/Nets 2>/dev/null` ; do
  TXT=""
  if ! [ -z "$A" ] ; then
     if echo "$A" | grep -q "/" ; then
       TXT="Subnet $A"
     else
       TXT="IP $A"
     fi
  fi
  echo "<option value='$A'>$TXT</option>"
done
if [ -z "$A" ] ; then
  echo "<option value='any'>Any IP address (use this VPN box as default gateway)</option>"
fi
