#!/bin/bash
. /etc/kerbynet.conf
RECIPIENT="$1"
SUBJECT="$2"
[ -z "$RECIPIENT" ] && exit 1
CONFIG="$REGISTER/system/alerts/EMAIL"
SMTPSENDER="`cat $CONFIG/SMTPSender 2>/dev/null`"
SMTPSERVER="`cat $CONFIG/SMTPServer 2>/dev/null`"
SMTPPORT="`cat $CONFIG/SMTPPort 2>/dev/null`"
SMTPUSERNAME="`cat $CONFIG/SMTPUsername 2>/dev/null`"
SMTPPASSWORD="`cat $CONFIG/SMTPPassword 2>/dev/null`"
SMTPSECURITY="`cat $CONFIG/SMTPSecurity 2>/dev/null`"
if ! echo "$SMTPSENDER" |grep -q @ ; then 
  if echo "$SMTPUSERNAME" |grep -q @ ; then
    SMTPSENDER="$SMTPSENDER <$SMTPUSERNAME>"
  else
    DOMAIN=`hostname|sed -r 's/[^\.]*.(.*)/\1/'`
    [ -z "$DOMAIN" ] && DOMAIN=example.com
    SMTPSENDER="$SMTPSENDER <noreply@$DOMAIN>"
  fi
fi
if [ -n "$SMTPUSERNAME" ] ; then
   AUTHSTRING="--user=$SMTPUSERNAME --pass=$SMTPPASSWORD"
else 
   AUTHSTRING=""
fi
SECURITYSTRING="--disable-starttls --disable-ssl"
case $SMTPSECURITY in
     STARTTLS)
       SECURITYSTRING="" ;;
     SSL)
       SECURITYSTRING="--ssl" ;;
esac 
BODY=/tmp/sendmail-body.$$
echo > $BODY
[ ! -t 0 ] && cat > $BODY
smtp-cli --subject="$SUBJECT" --from="$SMTPSENDER" --to="$RECIPIENT" --server="$SMTPSERVER" --port="$SMTPPORT" $SECURITYSTRING $AUTHSTRING --body-plain=$BODY
EXIT=$?
rm -f $BODY
exit $EXIT
