#!/bin/bash
. /etc/kerbynet.conf
ALIASNAME="$1"
DBM="$2"
[ -z "$ALIASNAME" ] && exit 1
. $SCRIPTS/wifi.inc

if [ -z "$DBM" ] ; then
  INTERFACE=`wifi-getdev $ALIASNAME`
  DBM=`cat $REGISTER/system/net/WiFi/DEVS/$INTERFACE/TXPOWER 2>/dev/null`
fi
[ -z "$DBM" ] && DBM=auto
iwconfig $ALIASNAME txpower $DBM 2>/dev/null
TXPW=`iwconfig $ALIASNAME |grep Tx-Power= | sed -r 's/.*Tx-Power=(.*) dBm.*/\1/'`
if [ "$DBM" != auto ] ; then
  if [ "$TXPW" != "$DBM" ] ; then
    #iwconfig $ALIASNAME txpower auto
    echo "WARNING: +++++ TX POWER setting error +++++"
    echo "Configured Tx-Power: $DBM dBm   Assigned Tx-Power: $TXPW dBm" 
    logger -t "WiFi_txpower" "WARNING: Tx Power setting error for the interface $ALIASNAME($INTERFACE)"
  else
    logger -t "WiFi_txpower" "The TX Power of the interface $ALIASNAME($INTERFACE) has been set to $DBM (dBm)"
  fi
fi
