#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
OP="$2"
OPT="$3"
[ -z "$INTERFACE" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/$INTERFACE/dhclient/"
if [ -z "$OP" ] ; then
  OP="`cat $CONFIG/Status 2>/dev/null`"
  [ -z "$OP" ] && exit
fi
if [ "$OP" == Enabled ] ; then
  kill  `cat $CONFIG/pid 2>/dev/null` 2>/dev/null
  dhclient -q -lf "$CONFIG/leases" -pf "$CONFIG/pid" "$INTERFACE" 2>/dev/null >/dev/null &
  echo "$INTERFACE: Dynamic IP configuration enabled"
fi
if [ "$OP" == Disabled -o "$OP" == Release ] ; then
  dhclient -lf "$CONFIG/leases" -pf "$CONFIG/pid" -r "$INTERFACE" 2>/dev/null >/dev/null
fi
if [ "$OP" == Renew ] ; then
  dhclient -lf "$CONFIG/leases" -pf "$CONFIG/pid" -r "$INTERFACE" 2>/dev/null >/dev/null
  sleep 1 
  dhclient -q -lf "$CONFIG/leases" -pf "$CONFIG/pid" "$INTERFACE" 2>/dev/null >/dev/null &
fi



ifconfig $INTERFACE `cat $REGISTER/system/net/interfaces/$INTERFACE/STATUS 2>/dev/null` 2>/dev/null
N=0
if [ "$OPT" == Wait ] ; then
  sleep 2
  if [ "$OP" == Enabled -o "$OP" == Renew ] ; then

    while [ "`$SCRIPTS/show_dhclientip $INTERFACE`" == 0.0.0.0 -a $N -lt 25 ] ; do

      sleep 1
      N=$((N+1))
    done
  else
    sleep 4
  fi
fi
