#!/bin/sh
. /etc/kerbynet.conf
PPP="$1"
[ -z "$PPP" ] && exit
if [ "$PPP" == any ] ; then
  cd $REGISTER/system/net/interfaces/
  PPPS=`ls -d ppp?`
  for P in $PPPS ; do
    $SCRIPTS/setpppgw $P
  done
  exit
fi 
[ "`cat $REGISTER/system/net/interfaces/$PPP/DEFAULTROUTE 2>/dev/null`" == yes ] || exit
[ "`cat $REGISTER/system/net/nb/Enabled 2>/dev/null`" == yes ] && exit
# [ -d /proc/sys/net/ipv4/conf/$PPP/ ] || exit
ifconfig $PPP 2>/dev/null |grep -q "inet addr:" || exit
if route -n | grep -w ^0.0.0.0 | grep -w -q $PPP ; then
  exit
fi
if route -n |grep ^0.0.0.0 |grep -v  ppp | awk '{print $5}' | grep -q -w 0 ; then
  ip ro del default metric 0
fi
LASTMETRIC="`route -n |grep ^0.0.0.0 |awk '{print $5}' | tail -1`"
if [ -z "$LASTMETRIC" ] ; then
  METRIC=0
else
  METRIC=$((LASTMETRIC+1))
fi

ip ro add default metric $METRIC dev $PPP
