#!/bin/bash
TMP="/tmp/createfilter.$$"
TMP2="/tmp/createfilter_.$$"
echo -n "if (" >> "$TMP"

sed 's/(#D)/$/g' |sed 's/(#N)/\n/g' |grep -v "^#" |sed 's/\n/ /g' |sed 's/@/\\@/g' >> "$TMP"
echo  ') {print "Ok"}' >> "$TMP"

echo "#!/usr/bin/perl" > "$TMP2"
tr '\n' ' ' < "$TMP" >> "$TMP2"
if perl < "$TMP2" ; then
 /etc/sudo /bin/mv "$TMP2" /var/register/system/cp/Auth/Shibboleth/authz.pl
 /etc/sudo /bin/chmod 755 /var/register/system/cp/Auth/Shibboleth/authz.pl
 rm -f "$TMP"
 exit 0
else
 rm -f "$TMP" "$TMP2"
 exit 1
fi

