#!/bin/bash
. /etc/kerbynet.conf

if [ "`cat $REGISTER/system/cp/Auth/Shibboleth/AuthzMode 2>/dev/null`" = Filter ] ; then
  if $REGISTER/system/cp/Auth/Shibboleth/authz.pl  >/dev/null 2>/dev/null ; then
     if [ "`$REGISTER/system/cp/Auth/Shibboleth/authz.pl`" = Ok ] ; then
       echo "<font color=#40f040>PASSED</font>"
     else
       echo "<font color=#f08040>NOT PASSED</font>"
     fi
  else
    echo "<font color=#f08080>SYNTAX ERROR</font>"
  fi  
else
  echo "<font color=#f08040>OFF</font>"
fi
