#!/bin/bash
. /etc/kerbynet.conf
TMP="/tmp/shib_checkconfig.$$"
/opt/shibboleth-sp/sbin/shibd -t > "$TMP"
FATAL="`grep -w FATAL $TMP|wc -l`"
CRITICAL="`grep -w CRIT $TMP|wc -l`"
ERROR="`grep -w ERROR $TMP|wc -l`"
WARN="`grep -w WARN $TMP|wc -l`"
echo "FATAL      :          $FATAL"
echo "CRITICAL   :          $CRITICAL"
echo "ERROR      :          $ERROR"
echo "WARNING    :          $WARN"
echo
echo "<hr>"
echo

cat "$TMP"
if [ $FATAL -gt 0 ] ; then
   MSG="<font color=#ff2020><b><blink>UNLOADABLE</blink></b></font>"
else
  if [ $CRITICAL -gt 0 -o $ERROR -gt 0 ] ; then
    MSG="<font color=#ff8040><b>LOADABLE</b></font>"
  else
    MSG="<font color=#20e020><b>LOADABLE</b></font>"
  fi
fi
echo "<script>document.getElementById('Msg').innerHTML='$MSG';</script>"
rm -f "$TMP"
exit 0
