#!/bin/sh
. /etc/kerbynet.conf
OPT="$1"
$SCRIPTS/umountstorage
rm -rf /storage/INFO
echo 0 > /tmp/DBTIMESTAMP
echo > /tmp/LASTACTIVEDB
DEVICES=`awk ' BEGIN { DISK="----";getline;getline} ;substr($4,0,length(DISK)) != DISK  {DISK=$4 ; print "/dev/" $4}' < /proc/partitions |egrep -v ^/dev/loop |grep -v ^/dev/ram | grep -v ^/dev/sr`
for DEV in $DEVICES ; do 
  if [ ${DEV:0:7} != /dev/fd ] ; then
    if fdisk -s $DEV 2>/dev/null >/dev/null ; then
        SIZE=`fdisk -s $DEV 2>/dev/null`;
        if sg_inq $DEV 2>/dev/null >/dev/null; then  
           sg_inq $DEV 2>/dev/null >/tmp/disk_info
           MODEL="`grep 'Vendor identification:' /tmp/disk_info |cut -f2 -d:` `grep 'Product identification:' /tmp/disk_info |cut -f2 -d:`"
        else  
           hdparm -I $DEV 2>/dev/null >/tmp/disk_info         
           MODEL="`grep 'Model Number:' /tmp/disk_info |cut -f2 -d:`"
        fi
        W=`echo $DEV | sed -e "s/\//_/g"`;
        mkdir -p /storage/INFO/DISK/$W
        echo "$MODEL" > /storage/INFO/DISK/$W/Model
        echo "$SIZE" > /storage/INFO/DISK/$W/Size
        $SCRIPTS/mountstorage "$DEV"
    fi 
  fi
done
if [ "`cat /tmp/LASTACTIVEDB`" != "" ] ; then
  if [ "`$SCRIPTS/getactivedb`" == No -a "$OPT" != nomount ] ; then
     $SCRIPTS/umountdb
     DI=`awk -F: '{print $1}' < /tmp/LASTACTIVEDB`
     P=`awk -F: '{print $2}' < /tmp/LASTACTIVEDB`
     D=`awk -F: '{print $3}' < /tmp/LASTACTIVEDB`
     if $SCRIPTS/activatedb $P $D ; then 
       ## && echo "Profile $D ($P) <`cat /Database/.settings/Description`> successfully activated."
       DISKDIR=`echo $DI | sed -e "s/\//_/g"`;
       DISKINFO=`sed -r 's/^ *(.*) /\1/g' < /storage/INFO/DISK/$DISKDIR/Model 2>/dev/null`
       echo "--------------------------------------------------------------------"
       echo "PROFILE   : `cat /Database/.settings/Description`"
       echo "Disk      : $DISKINFO"
       echo "Partition : ${P:5}"
       echo "Alias     : $D"
       echo "--------------------------------------------------------------------"
     fi

  fi
fi
if ! df |grep -w -q /Database$ ; then 
   if $SCRIPTS/mountdefaultdb ; then
       echo "--------------------------------------------------------------------"
       echo "PROFILE   : `cat /Database/.settings/Description 2>/dev/null`"
       echo "Disk      : RAMDISK (size: `df -h /dev/ram1 |awk '{print $2}'|tail -1`)"
       echo "Partition : ram1"
       echo "Alias     : N/A"
       echo "--------------------------------------------------------------------"
   fi
   $SCRIPTS/startservices
fi

