#!/bin/sh
. /etc/kerbynet.conf
SHOWTYPE="$1"
export RELEASE=`$SCRIPTS/release`
export PATCHLEVEL=`$SCRIPTS/patchlevel`
LIST="$REGISTER/system/AutoUpdate/Releases/$RELEASE.$PATCHLEVEL/UpdateList"
NO=/tmp/tableFixesA.NO.$$
N=0
echo $N > $NO
if [ -n "$SHOWTYPE" ] ; then
  SHOWTYPE_=";$SHOWTYPE;"
else
  SHOWTYPE_=""
fi
grep "$SHOWTYPE_" $LIST | while read LINE  ;  do  
  ID=`echo "$LINE" | awk -F";" '{print $1}'` 
  if [ ! -f "$REGISTER/system/AutoUpdate/pkgs/$ID/pkg/Installed" ] ; then
    TYPE=`echo "$LINE" | awk -F";" '{print $2}'` 
    DESCRIPTION=`echo "$LINE" | awk -F";" '{print $3}'` 
    DATE=`echo "$LINE" | awk -F";" '{print $4}'` 
    VERS=`echo "$LINE" | awk -F";" '{print $7}'` 
    N=$((N + 1))
    echo $N > $NO
    echo "<tr><td nowrap>&nbsp;<input type=radio name='Available' value='$ID:$TYPE'>&nbsp;</td><td nowrap class=Smaller1>&nbsp;<a href="#$ID" onclick=\"ShowInfo('$ID:$TYPE')\">$ID</a>&nbsp;</td><td nowrap  class=Smaller1>&nbsp;$DESCRIPTION&nbsp;$VERS&nbsp;</td><td nowrap  class=Smaller1>&nbsp;$DATE&nbsp;</td><td nowrap  class=Smaller1>&nbsp;$TYPE&nbsp;</td></tr>"
  fi
done
N=`cat $NO`
rm $NO
echo "</table>"
if [ $N -eq 0 ] ; then
  echo "<br>"
  echo "<font color=#404040>&nbsp;&nbsp;&nbsp;&nbsp;No <i>`$SCRIPTS/autoupdateTypeDesc $SHOWTYPE`</i> available to be installed on the release $RELEASE.$PATCHLEVEL</font>"
  echo "<br>"
fi

