#!/bin/sh
source /etc/kerbynet.conf
if $SCRIPTS/stopservices ; then
  ACTIVE=`$SCRIPTS/getactivedb`
  if [ "$ACTIVE" != No ] ; then
    P=`echo $ACTIVE | awk -F: '{print $1}'`
    D=`echo $ACTIVE | awk -F: '{print $2}'`
    touch /Database/.settings/LastActivation
    DESCRIPTION=`cat /Database/.settings/Description`
    umount /Database 2>/dev/null && echo "Profile $D ($P) <$DESCRIPTION> successfully deactivated." || exit 1
  fi
  umount /Database 2>/dev/null
  umount /Database 2>/dev/null  
  umount /Database 2>/dev/null
  umount /DB 2>/dev/null
  umount /DB 2>/dev/null
  umount /DB 2>/dev/null
  if df |grep -q -w /Database$ ; then
     sync
     exit 3
  fi
else
   sync 
   exit 2
fi
