#!/bin/sh
. /etc/kerbynet.conf
IMAGEPATH="$1"
[ -z "$IMAGEPATH" ] && exit 1
LINE=""
while [ "${LINE:0:9}" != "StartHere" ] ; do
  read LINE
done
read
read
read LINE
if echo "$LINE" | grep -q "^Content-Type: image" ; then
  read
  cat - > "$REGISTER/$IMAGEPATH/File"
fi
