#!/bin/bash
. /etc/kerbynet.conf
while true ; do
  echo
  echo "-------------------------------------"
  echo "  C O N S O L E   U T I L I T I E S"
  echo "-------------------------------------"
  echo
  echo "  <C> Connection Top (cntop)"
  echo "  <B> Make a Bridge"
  echo "  <Q> Quit"
  echo
  echo -n ">> "
  read -n1  X
  X=`echo $X | awk '{print toupper($0)}'`
  echo
  echo
  case "$X" in
    Q)
      exit
    ;;
    B)
      $SCRIPTS/localman_bridge
    ;;
    C)
      $SCRIPTS/cntop 
    ;;
  esac

done

