#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
OPT="$2"
[ -z "$INTERFACE" ] && exit 1
cd "$REGISTER/system/net/interfaces/$INTERFACE/VLAN" 2>/dev/null || exit 0
VLANS="`ls`"

if [ "$OPT" == options ] ; then

  for V in $VLANS ; do
    echo "<option value='$V'>$V</option>"
  done
else
  for V in $VLANS ; do
    echo "$V"
  done
fi
