#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
if cd "$CONFIG" 2> /dev/null ; then
  if [ -f $INTERFACE/cert ] ; then 
     X="`file $INTERFACE/cert`"
     X="`basename "$X"`"
     X=${X%\'}
     if [ "${X:0:4}" == cert ] ; then
        echo imported
     else
        echo $X
     fi
  else
     echo "None"
  fi 
fi






