#!/bin/sh
. /etc/kerbynet.conf
PORT="$1"
PROTO="`echo $2 | awk '{print toupper(substr($0,0,3))}'`"
VPN="$3"
[ -z "$PORT" ] && exit
cd "$REGISTER/system/net/interfaces/"
VPNs=`ls -d VPN[0123456789][0123456789] 2> /dev/null |grep -v VPN99`
for V in $VPNs ; do
  if [ "`cat $V/TUNNEL/Port`" == "$PORT" -a "`cat $V/TUNNEL/Proto`" == "$PROTO"  -a "$V" != "$VPN" ] ; then
    echo "$VPN uses the port $PORT/$PROTO already used by $V"
    exit 0
  fi 
done
if [ "$VPN" != VPN99 ] ; then
  if [ "$PORT" == "`cat $REGISTER/system/openvpn/Port 2>/dev/null`" ] && grep -q -i $PROTO $REGISTER/system/openvpn/Proto ; then
     echo "$VPN uses the port $PORT/$PROTO already used by VPN99 for Host-to-LAN VPN"
     exit 0
  fi
fi
