#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
cd /sys/class/net
INTERFACES=`ls`
CONFIG="$REGISTER/system/net/interfaces"
for i in $INTERFACES ; do
   NAME=$i
   if echo $i | egrep -q ^eth[0123456789]+$ ; then
      echo $i `getmac $i`
      MAC=`getmac $i`
      if [ "$MAC" != 000000000000 -a "$MAC" != "" ] ; then 
         if ls $CONFIG/*/MAC/$MAC 2>/dev/null >/dev/null ; then
            NAME=`echo $CONFIG/*/MAC/$MAC |cut -d/ -f7`
         else
            if [ "${i:0:3}" == eth ] ; then
               LASTETHER=`ls -d $CONFIG/ETH[0123456789][0123456789] 2>/dev/null | sort | tail -1`
               if [ -z "$LASTETHER" ] ; then
                  NAME=ETH00 
               else 
                  NUM=`basename $LASTETHER | sed -r "s/ETH([01234567890][01234567890])/\1/"`
                  if [ "${NUM:0:1}" == 0 ] ; then
                     NUM=${NUM:1:1}
                  fi
                  NUM=`echo $((NUM+1)) | awk '{printf "%02s",$0 }'`
                  NAME="ETH$NUM"
                  echo $NAME
               fi
            fi
            mkdir -p $CONFIG/$NAME/MAC
            touch $CONFIG/$NAME/MAC/$MAC
            echo up >$CONFIG/$NAME/STATUS
         fi
         DESCRIPTION=`cat $CONFIG/$NAME/Description 2>/dev/null`
         if [ -z "$DESCRIPTION" ] ; then
            $SCRIPTS/getintdesc $i > $CONFIG/$NAME/Description
         fi
      fi
   fi
   if [ "$NAME" != "$i" ] ; then
      echo "$i" --\> "$NAME"
      ip link set down dev $i
      ip link set name $NAME dev $i
   fi
done 
cd $CONFIG
INTERFACES=`ls`
for i in $INTERFACES ; do
   echo $i
   DESCRIPTION=`cat $CONFIG/$i/Description 2>/dev/null`
   if [ -z "$DESCRIPTION" ] ; then
      $SCRIPTS/getintdesc $i > $CONFIG/$i/Description
   fi
   $SCRIPTS/setinterface $i

   if cd "$CONFIG/$i/VLAN" 2>/dev/null ; then
      VLANS=`ls`
      for VLAN in $VLANS ; do
         $SCRIPTS/setinterface $i.$VLAN
      done
      cd $CONFIG
   fi
done





