#!/bin/sh
. /etc/kerbynet.conf
WEBEXPORT="`cat $REGISTER/system/ssl/ca/WebExport 2>/dev/null`"
if [ "$WEBEXPORT" != yes ] ; then
  echo "<tr><td>Option disabled</td></tr>"
  exit
fi
TYPE="$1"
cd "$SSLDIR/certs" || exit 1
ls *_${TYPE}.pem |awk -F"_$TYPE.pem" -v"TYPE=$TYPE" '{ 
  printf "<tr><td><a href=\"kerbynet?Section=NoAuthREQ&Action=x509view&User=%s&x509type=" TYPE "\" >%s</a> </td><td>",$1,$1;
  system("openssl x509 -in \"" $0 "\" -text -noout|grep Subject:|cut -d: -f2");
  printf "</td></tr>\n";
} '
