#!/bin/sh
. /etc/kerbynet.conf
export PATH=$PATH:/usr/local/ssl/bin
NBIT=`cat $REGISTER/system/ssl/ca/keysize 2>/dev/null`
DAYS=`cat $REGISTER/system/ssl/ca/days 2>/dev/null`
[ -z "$NBIT" ] && NBIT=1024
[ -z "$DAYS" ] && DAYS=365
openssl req -new -batch -newkey rsa:$NBIT -nodes -out /tmp/x509default.req -keyout /tmp/x509default.key -days $DAYS -subj "/OU=users/CN=admin"
openssl ca -batch -days $DAYS -in /tmp/x509default.req -out /tmp/x509default.cert -extfile $SSLDIR/extensions -extensions user
openssl x509 -in /tmp/x509default.cert -out "$SSLDIR/certs/admin_user.pem"
mv /tmp/x509default.key "$SSLDIR/private/admin_user.pem"
$SCRIPTS/onlyRootRW "$SSLDIR/private/admin_user.pem"
rm -f /tmp/x509default.req /tmp/x509default.cert





