
[Boot]
Sysctl = [
  "fs.file-max=1024000",
  "net.bridge.bridge-nf-call-arptables=0",
  "net.bridge.bridge-nf-call-ip6tables=0",
  "net.bridge.bridge-nf-call-iptables=0",
  "net.bridge.bridge-nf-filter-pppoe-tagged=0",
  "net.bridge.bridge-nf-filter-vlan-tagged=0",
  "net.core.netdev_max_backlog=300000",
  "net.core.optmem_max=40960",
  "net.core.rmem_max=268435456",
  "net.core.somaxconn=65536",
  "net.core.wmem_max=268435456",
  "net.ipv4.conf.all.accept_local=1",
  "net.ipv4.conf.all.accept_redirects=1",
  "net.ipv4.conf.all.accept_source_route=1",
  "net.ipv4.conf.all.rp_filter=0",
  "net.ipv4.conf.all.forwarding=1",
  "net.ipv4.conf.default.rp_filter=0",
  "net.ipv4.ip_forward=1",
  "net.ipv4.ip_local_port_range=1024 65000",
  "net.ipv4.ip_no_pmtu_disc=1",
  "net.ipv4.tcp_congestion_control=htcp",
  "net.ipv4.tcp_fin_timeout=40",
  "net.ipv4.tcp_max_syn_backlog=3240000",
  "net.ipv4.tcp_max_tw_buckets=1440000",
  "net.ipv4.tcp_moderate_rcvbuf=1",
  "net.ipv4.tcp_mtu_probing=1",
  "net.ipv4.tcp_rmem=4096 87380 134217728",
  "net.ipv4.tcp_slow_start_after_idle=1",
  "net.ipv4.tcp_tw_recycle=0",
  "net.ipv4.tcp_tw_reuse=1",
  "net.ipv4.tcp_window_scaling=1",
  "net.ipv4.tcp_wmem=4096 65536 134217728",
  "net.ipv6.conf.all.disable_ipv6=1",
  "vm.swappiness=0"
]
ActiveModules = [
  "tun",
  "br_netfilter"
]
InactiveModules = [
  "ip_tables"
]
ActiveServices = [
  "systemd-journald.service"
]
InactiveServices = [
  "systemd-networkd.service"
]

[Time]
Timezone = "Europe/Rome"
EnableNtpSync = true
NtpServer = [
  "ntp1.ien.it"
]

[Host]
Name = "deb01"
Chassis = "vm"
Deployment = "developement"
Location = "onEarth"

[Network.Dns]
Nameserver = [
  "8.8.8.8",
  "8.8.4.4"
]
Search = "search"
Domain = "domain"

[[Network.Interfaces]]
Auto = "on"
Iface = "eth1"
Address = "192.168.1.1/24"
Conf = [
  "ip addr add 192.168.2.1/24 dev eth1",
  "ip addr add 192.168.3.1/24 dev eth1",  
  "ip link set down eth1",
]

[[Network.Routing]]
Destination = "default"
Gateway = "123.456.78.99"
Device = "eth1"

[Commands]
Run = [
  "mkdir -p /Data/Data01",
  "touch /Data/Data01/test.txt",
  "echo 3 >> /Data/Data01/test.txt",
]
