#!/bin/bash
. /etc/kerbynet.conf
BOND="$1"
SLAVE="$2"
[ -z "$BOND" ] && exit 1

if [ -z "$SLAVE" ] ; then
  SLAVES=$(cat $REGISTER/system/net/interfaces/$BOND/BondList 2>/dev/null)
else
  SLAVES=$SLAVE
fi

for S in $SLAVES ; do
  if grep -A3 -w "Slave Interface: $S" /proc/net/bonding/$BOND |grep "MII Status:" |grep -q -w up ; then
    exit 0
  fi
done
exit 55
