#!/bin/bash
. /etc/kerbynet.conf
ENABLED=`cat $REGISTER/system/acct/Enabled 2>/dev/null`
if ! [ "$ENABLED" = yes ] ; then
   exit 0
fi
[ "`echo $REALM |awk '{print toupper($0)}'`" = "\"`cat /var/register/system/k5/realm`\"" ] && export USER_NAME="$STRIPPED_USER_NAME"
export USER_NAME=`echo "$USER_NAME" | tr '[:upper:]' '[:lower:]'`



case "$ACCT_STATUS_TYPE" in
Interim-Update)
	$SCRIPTS/acct_interim_update
	;;
Start)
	$SCRIPTS/acct_start
	;;
Stop)
	$SCRIPTS/acct_stop
	;;
esac
