#!/bin/bash
. /etc/kerbynet.conf
LIMIT="$1"
[ -z "$LIMIT" ] && exit 0
case "$LIMIT" in
	E)
		$SCRIPTS/cp_msg Expired ;;
	T)
		$SCRIPTS/cp_msg NoTime ;;
	M)
		$SCRIPTS/cp_msg NoTraffic ;;
	C)
		$SCRIPTS/cp_msg NoCredit ;;
esac



