#!/bin/sh
. /etc/kerbynet.conf
CLASSNAME="$1"
[ -z "$CLASSNAME" ] && exit 2
MB="$2"
HOURS="$3"
MBITS="$4"
COSTM="$5"
COSTH="$6"
CHARGETYPE="$7"
CONFIG="$REGISTER/system/acct/classes/$CLASSNAME"
if [ -d "$CONFIG" ] ; then
  echo "$CLASSNAME already exists" >&2 
  exit 3
fi
mkdir "$CONFIG" || exit 1
cd "$CONFIG"
echo "$MB" > MB 
echo "$HOURS" > Hours 
echo "$MBITS" > Mbits 
echo "$COSTM" > CostM 
echo "$COSTH" > CostH 
echo "$CHARGETYPE" > ChargeType 
