#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/acct
if ! [ -d $CONFIG/classes ] ; then
   mkdir -p $CONFIG/classes
fi
cd $CONFIG/classes
CLASSES=`ls -d *`
for C in $CLASSES ; do
  echo "<option value='$C'>$C</option>"

done
