#!/bin/bash
. /etc/kerbynet.conf
ENTRY="$1"
LIMITS="$2"
IP="$3"
[ -z "$ENTRY" ] && exit 1
D="$REGISTER/system/cp/Limits/$ENTRY/"
[ -d "$D" ] || mkdir "$D"
echo "$LIMITS" | cut -d: -f1 > "$D/Class"
echo "$LIMITS" | cut -d: -f2 > "$D/Hours"
echo "$LIMITS" | cut -d: -f3 > "$D/MB"
echo "$LIMITS" | cut -d: -f4 > "$D/Mbits"
echo "$LIMITS" | cut -d: -f5 > "$D/CostH"
echo "$LIMITS" | cut -d: -f6 > "$D/CostM"
echo "$LIMITS" | cut -d: -f7 > "$D/Expire"
echo "$LIMITS" | cut -d: -f8 > "$D/Credit"
echo "$LIMITS" | cut -d: -f9 > "$D/LCode"
