#!/bin/sh
. /etc/kerbynet.conf
USER="$1"
[ -z "$USER" ] && exit 1
cd "$REGISTER/system/acct/entries/$USER/sessions" || exit 2
CURRENCY=`cat $REGISTER/system/acct/Currency`
DECIMALS=`cat $REGISTER/system/acct/Decimals`
SESSIONS=`ls -dt *`
NUMCONN=0
#SUMTRAFFIC=0
#SUMTIME=0
#SUMCOST=0
SUMTRAFFIC=`cat "../MB" 2>/dev/null`
SUMTIME=`cat "../Time" 2>/dev/null`
SUMCOST=`cat "../Cost" 2>/dev/null`
for S in $SESSIONS ; do
  IP=`cat $S/IP 2>/dev/null`
  MAC=`cat $S/MAC 2>/dev/null`
  if [ -z "$IP" ] ; then
    CLIENT=$MAC
  else
    CLIENT=$IP 
    [ -n "$MAC" ] && CLIENT="$IP / $MAC"
  fi
  NAS=`cat $S/NAS 2>/dev/null`
  START=`cat $S/start 2>/dev/null`
  START=`date  --date="1970-01-01 $START sec GMT" +"%D %T" 2>/dev/null`
  STOP=`cat $S/stop 2>/dev/null`
  
  [ -n "$STOP" ] && STOP=`date  --date="1970-01-01 $STOP sec GMT" +"%D %T" 2>/dev/null`
  LAST=`cat $S/Last 2>/dev/null`
  [ -n "$LAST" ] && LAST=`date  --date="1970-01-01 $LAST sec GMT" +"%D %H:%M" 2>/dev/null`
  RX=`cat $S/RX 2>/dev/null`
  [ -z "$RX" ] && RX=0
  TX=`cat $S/TX 2>/dev/null`
  [ -z "$TX" ] && TX=0
  TRAFFIC=`cat $S/Traffic 2>/dev/null`
  [ -z "$TRAFFIC" ] && TRAFFIC=0
  TIME=`cat $S/Time 2>/dev/null`
  [ -z "$TIME" ] && TIME=0
  COST=`cat $S/Cost 2>/dev/null`
  COST=`printf "%.${DECIMALS}f" $COST`
  #SUMTRAFFIC=$((SUMTRAFFIC+TRAFFIC))
  #SUMTIME=$((SUMTIME+TIME))
  #SUMCOST=`echo "$SUMCOST" "$COST" | awk '{print $1+$2}'`
  TX=`echo "$TX" |awk '{printf "%.2f",$1/1048576}'`
  RX=`echo "$RX" |awk '{printf "%.2f",$1/1048576}'`
  TRAFFIC=`echo "$TRAFFIC" |awk '{printf "%.2f",$1/1048576}'`
  TIME=`echo "$((TIME/60)) $TIME" | awk '{printf "%2d:%02d:%02d",$1/60,$1%60,$2%60}'`
  echo "<tr align=center style='color: #404040;'><td><input type=radio name=CLT value='$S'></td><td class=Smaller1>$CLIENT</td><td class=Smaller1>$NAS</td><td class=Smaller1>$START</td><td class=Smaller1>$STOP</td><td class=Smaller1>$RX</td><td class=Smaller1>$TX</td><td class=Smaller1>$TRAFFIC</td><td class=Smaller1>$TIME</td><td class=Smaller1>$COST</td><td class=Smaller1>$LAST</td></tr>"
  NUMCONN=$((NUMCONN+1))
done
SUMTIME=`echo "$((SUMTIME/60))" | awk '{printf "%2d:%02d",$0/60,$0%60}'`
SUMTRAFFIC=`echo "$SUMTRAFFIC" |awk '{printf "%.2f",$1/1048576}'`
SUMCOST=`printf "%.${DECIMALS}f" $SUMCOST`
echo "<script>document.getElementById('nSession').innerHTML='$NUMCONN';document.getElementById('SumTraffic').innerHTML='$SUMTRAFFIC';document.getElementById('SumTime').innerHTML='$SUMTIME';document.getElementById('SumCost').innerHTML='$SUMCOST';document.getElementById('CurrencySymbol').innerHTML='$CURRENCY';</script>"
