#!/bin/sh
. /etc/kerbynet.conf
ENABLED="$1"
CURRENCY="$2"
DECIMALS="$3"
CONFIG="$REGISTER/system/acct/"
if ! [ -d "$CONFIG" ] ; then
  echo "Configuration not found" >&2 
  exit 3
fi
cd "$CONFIG"
CURRENCY=$(echo "$CURRENCY" | sed 's/_/\$/g')
echo "$ENABLED" > Enabled
echo "$CURRENCY" > Currency 
echo "$DECIMALS" > Decimals 

$SCRIPTS/accounting_start
