#!/bin/sh
. /etc/kerbynet.conf
FEATURE="$1"
KEY="$2"
if [ -z "$FEATURE" -o -z "$KEY" ] ; then
  exit 1
fi
$SCRIPTS/setfeature "$FEATURE" "$KEY"
$SCRIPTS/mrtg_reload
if ! checkfeature $FEATURE ; then
  echo "<script>parent.SubmitData();</script>"
else
  echo "<script>parent.Feature='$FEATURE';parent.Activated();</script>"
fi
