#!/bin/bash
. /etc/kerbynet.conf
EVENT="$1"
NAME="$2"
DIR="$REGISTER/system/alerts/Events/$EVENT"
[ -d "$DIR" ] || exit 1
[ -z "$NAME" ] && exit 2
VALUE="`cat $DIR/State/$NAME 2>/dev/null`"
[ "$NAME" = Status -a -z "$VALUE" ] && VALUE=NOTIFY
echo "$VALUE"
