#!/bin/sh
. /etc/kerbynet.conf
ITEM="$1"
[ -z "$ITEM" ] && exit 0
[ ! -d "$REGISTER/system/alerts/Recipients/$ITEM/" ] && exit 0
DESCRIPTION=`cat $REGISTER/system/alerts/Recipients/$ITEM/Description 2>/dev/null`
TYPE=`cat $REGISTER/system/alerts/Recipients/$ITEM/Type 2>/dev/null`
ENABLED=`cat $REGISTER/system/alerts/Recipients/$ITEM/Enabled 2>/dev/null`
RECIPIENT=`cat $REGISTER/system/alerts/Recipients/$ITEM/Recipient 2>/dev/null`
if [ "$ENABLED" = yes ] ; then

  echo "<font color=#00a060>[ENABLED] $DESCRIPTION ($RECIPIENT)</font>"
else
  echo "<font color=#f03030>[DISABLED] $DESCRIPTION ($RECIPIENT)</font>"
fi



