#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
OP="$2"
[ -z "$ID" ] && exit 1
[ -z "$OP" ] && exit 2
TYPE=`echo "$ID" |awk -F: '{print $2}'`
ID=`echo "$ID" |awk -F: '{print $1}'`
FILE="/tmp/installer-elapsed-$ID"
if [ -f "$FILE" ] ; then
  S=`cat "$FILE"`
  NOW=`date +%s`
  S=$((NOW-S))
  H=$((S/3600))
  S=$((S-H*3600))
  M=$((S/60))
  S=$((S-M*60))
  printf "%02d:%02d:%02d" $H $M $S
fi
