#!/bin/sh
. /etc/kerbynet.conf
FLAGS="$1"
FEATURE="`$SCRIPTS/getfeature LU`"
if checkfeature $FEATURE ; then
  if [ "$FLAGS" = Expiration ] ; then
    CODE="`cat $REGISTER/system/keys/$FEATURE/code`"
    if [ "$CODE" = "${CODE:0:32}" ] ; then
      EXPIRE="PERMANENT"
    else
      TS="0x${CODE:32:8}"
      TS="$((TS))"
      EXPIRE="`$SCRIPTS/ts2date $TS| awk '{printf (\"Until %s %s, %s (%s)\",$2,$3,$5,$4)}'`"
    fi 
    echo "<font color=#30b030>$EXPIRE</font>"
  else
    echo "<font color=#30b030>ACTIVE</font>"
    
  fi
else
  EXITCODE=$?
  if [ $EXITCODE -eq 55 ] ; then
    if [ "$FLAGS" = Expiration ] ; then
      CODE="`cat $REGISTER/system/keys/$FEATURE/code`"
      TS="0x${CODE:32:8}"
      TS="$((TS))"
      EXPIRE="`$SCRIPTS/ts2date $TS| awk '{printf (\"Until %s %s, %s (%s)\",$2,$3,$5,$4)}'`"
      echo "<font color=#f03030>$EXPIRE</font>"
    else 
      echo "<font color=#f03030>EXPIRED</font>"
    fi
  else
    if [ "$FLAGS" = Expiration ] ; then
      echo "<font color=#f03030>N/A</font>"
    else
      echo "<font color=#f03030>NO VALID SUBSCRIPTION FOUND</font>"
    fi
  fi
fi
