#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
TYPE=`echo "$ID" |awk -F: '{print $2}'`
ID=`echo "$ID" |awk -F: '{print $1}'`
INCOMPATIBLES="`$SCRIPTS/autoupdateGetField "$ID" INCOMPATIBLE |tr , ' '`"
ERROR=0
for I in $INCOMPATIBLES ; do
  if [ -f "$REGISTER/system/AutoUpdate/pkgs/$I/pkg/Installed" ] ; then
    ERROR=$((ERROR+1))
    $SCRIPTS/autoupdate-error "$ID:$TYPE" "INSTALL" "ERROR: the package $I is not compatible with the package $ID"
  fi  
done
if [ $ERROR -gt 0 ] ; then
  exit 5
fi
