#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
#OP="$2"
[ -z "$ID" ] && exit 1
#[ -z "$OP" ] && exit 2
TYPE=`echo "$ID" |awk -F: '{print $2}'`
ID=`echo "$ID" |awk -F: '{print $1}'`
#ps -ef | grep -w autoupdate-installer-bg |grep -w "$ID:$TYPE" |grep -w -q "$OP"
ps -ef | grep -w autoupdate-installer-bg |grep -w -q "$ID:$TYPE" 
