#!/bin/sh
. /etc/kerbynet.conf
ID="$1"
FIELD="$2"
ID=`echo "$ID" |awk -F: '{print $1}'`
case "$FIELD" in
  ID)
	F=1
	;;
  TYPE)
	F=2
	;;
  DESCRIPTION)
	F=3
	;;
  DATE)
	F=4
	;;
  SIZE)
	F=5
	;;
  DEPS)
	F=6
	;;
  VERSION)
	F=7
	;;
  FLAGS)
	F=8
	;;
  INCOMPATIBLE)
	F=9
	;;
  *)
	F=1
	;;
esac
export RELEASE=`$SCRIPTS/release`
export PATCHLEVEL=`$SCRIPTS/patchlevel`
LIST="$REGISTER/system/AutoUpdate/Releases/$RELEASE.$PATCHLEVEL/UpdateList"
LINE=`grep  "^$ID;" $LIST`
echo  "$LINE" | cut -d';' -f $F
