#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc

function FIND() {
   if cd "$IPPATH" 2>/dev/null ; then
      ADDRESSES=`ls`
      for A in $ADDRESSES ; do
        IP_=`cat $A/IP`
        NETMASK_=`cat $A/Netmask 2>/dev/null`
        NETWORK_=`ipcalc -b -n ${IP_}/${NETMASK_} |grep Network: |awk '{print $2}' | awk -F/ '{print $1}'`
        if ! [ -z "$VLAN_" ] ; then
           vlan_=" vlan $VLAN_"
        else 
           vlan_=""
        fi
        echo "<option value='$NETWORK_/$NETMASK_'>$NETWORK_/$NETMASK_ ($I$vlan_)</option>"
      done
   fi
}

CONFIG="$REGISTER/system/net/interfaces/"
cd $CONFIG
INTERFACES=`ls`
for I in $INTERFACES ; do
  if ! [ -f $CONFIG/$I/Bond/Name -o -f $CONFIG/$I/Bridge/Name ] ; then
    VLAN_=""
    IPPATH=$CONFIG/$I/IP
    FIND
    if cd $CONFIG/$I/VLAN 2>  /dev/null ; then
      VLANS=`ls`
      for VLAN_ in $VLANS ; do
         IPPATH=$CONFIG/$I/VLAN/$VLAN_/IP
         FIND
      done
    fi
  fi
done
