#!/bin/bash
. /etc/kerbynet.conf
function  UMOUNT () {
  cd /
  umount $MP/$DB.AUX 2> /dev/null 
  if [ "$ALREADYMOUNTED" == No ] ; then
     umount "$MP" && rmdir "$MP"
  fi
}
DEV="$1"
DB="$2"
[ -z "$DEV" -o -z "$DB" ] && exit 1
$SCRIPTS/umountstorage >/dev/null
NODEV=${DEV:2}
LINE=`df -T -P | grep "$NODEV "`
if [ -z "$LINE" ] ; then 
   MP=/storage/`echo $DEV | sed -e "s/\//_/g"`;
   mkdir -p "$MP"
   mount -o rw "$DEV" "$MP" || exit 1
   if [ -r /$MP/$DB.AUX ] ; then
      if ! mount -oloop $MP/$DB.AUX /$MP/$DB ; then
         UMOUNT
         exit 2 
      fi
   fi
   ALREADYMOUNTED=No
else 
   MP=`echo $LINE | cut -f7 -d' '`
   mount -oremount,rw "$MP" || exit 1
   ALREADYMOUNTED=Yes
   if [ -r /$MP/$DB.AUX ] ; then   
     if ! mount -oloop $MP/$DB.AUX /$MP/$DB ; then
       UMOUNT
       exit 2 
     fi
   fi
fi
UMOUNT
DESCRIPTION=`sed 's/ /_/g' < "$MP/$DB/.settings/Description"`
DATE=`date +"%Y%m%d_%k%M"`
echo "ZS_${DESCRIPTION}_${DATE}.bck"

