#!/bin/sh
BASE="$1"
[ -z "$BASE" ] && exit 1
cat > /tmp/slapdtest.conf << EOF
include         /etc/openldap/schema/core.schema
database        bdb
suffix          "$BASE"
EOF
slaptest -f /tmp/slapdtest.conf

