#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc

function FIND() {
   if cd "$IPPATH" 2>/dev/null ; then
      ADDRESSES=`ls`
      for A in $ADDRESSES ; do
        IP_=`cat $A/IP`
        NETMASK_=`cat $A/Netmask 2>/dev/null`
        if $SCRIPTS/ip_belongs_network "$IP" "$IP_" "$NETMASK_" || $SCRIPTS/ip_belongs_network "$IP_" "$IP" "$NETMASK"; then
          if [ "$I" != "$INTERFACE" -o "$VLAN_" != "$VLAN" ] ; then 
            NETWORK_=`ipcalc -b -n ${IP_}/${NETMASK_} |grep Network: |awk '{print $2}'`
            if ! [ -z "$VLAN" ] ; then
              vlan=" vlan $VLAN"
            fi
            if ! [ -z "$VLAN_" ] ; then
              vlan_=" vlan $VLAN_"
            fi
            echo "$NETWORK overlaps $NETWORK_ ($I$vlan_)" 1>&2
            exit
          fi
        fi
      done
   fi
}


IP="$1"
NETMASK="$2"
INTERFACE="$3"
VLAN="$4"
[ -z "$NETMASK" -o -z "$IP" -o -z "$INTERFACE" ] && exit 1
NETWORK=`ipcalc -b -n $IP/$NETMASK |grep Network: |awk '{print $2}'`
CONFIG="$REGISTER/system/net/interfaces/"
cd $CONFIG
INTERFACES=`ls`
for I in $INTERFACES ; do
   if ! [ -r "$CONFIG/$I/Bridge/Name" -o -r "$CONFIG/$I/Bond/Name" ] ; then
     VLAN_=""
     IPPATH=$CONFIG/$I/IP
     FIND
     if cd $CONFIG/$I/VLAN 2>  /dev/null ; then
        VLANS=`ls`
        for VLAN_ in $VLANS ; do
          if ! [ -r "$CONFIG/$I/VLAN/$VLAN_/Bridge/Name" -o -r "$CONFIG/$I/VLAN/$VLAN_/Bond/Name" ] ; then
            IPPATH=$CONFIG/$I/VLAN/$VLAN_/IP
            FIND
          fi
        done
     fi
   fi
done
exit 5
