#!/bin/bash
. /etc/kerbynet.conf
$SCRIPTS/terminate freshclam
$SCRIPTS/terminate clamav_resetdb
ENABLED=`cat $REGISTER/system/havp/Enabled`
AUTOUPDATE=`cat $REGISTER/system/ClamAV/AutoUpdate 2>/dev/null`
if [ "$ENABLED" == yes -a "$AUTOUPDATE" == yes ] ; then
  RELEASE=`$SCRIPTS/release`
  PATCHLEVEL=`$SCRIPTS/patchlevel`
  export PATH=/Database/opt/$RELEASE/$PATCHLEVEL/packages/bin/:/Database/opt/$RELEASE/$PATCHLEVEL/packages/sbin/:$PATH
  export LD_LIBRARY_PATH=/Database/opt/$RELEASE/$PATCHLEVEL/packages/lib/:$LD_LIBRARY_PATH
 
  export QUERY_STRING="onlyrender"
  render $TEMPLATE/freshclam.conf > /tmp/freshclam.conf
  if [ -f /tmp/havp.pid ] ; then
    freshclam --config-file=/tmp/freshclam.conf --daemon
  fi
fi
