#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
NAME="$1"
DESCRIPTION="$2"
REMOTEIP="$3"
PORT="$4"
PROTO="$5"
TLSROLE="$6"
REMOTECN="$7"
COMPRESSION="$8"
CRYPTO="$9"
PARAMETERS="${10}"
AUTHENTICATION="${11}"
PSK="${12}"
GATEWAY="${13}"
LOCALIP="${14}"
[ -z "$NAME" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
VPNDIR="$CONFIG/$NAME"
if ! [ -d "$VPNDIR" ] ; then
   echo "VPN $NAME doesn't exist." 1>&2
   exit 3
fi
echo "$DESCRIPTION" > $VPNDIR/Description
echo "$REMOTEIP" > $VPNDIR/TUNNEL/RemoteIP
echo "$LOCALIP" > $VPNDIR/TUNNEL/LocalIP
echo "$PORT" > $VPNDIR/TUNNEL/Port
echo "$PROTO" > $VPNDIR/TUNNEL/Proto
echo "$TLSROLE" > $VPNDIR/TUNNEL/TLSRole
echo "$COMPRESSION" > $VPNDIR/TUNNEL/Compression
echo "$CRYPTO" > $VPNDIR/TUNNEL/Crypto
echo "$PARAMETERS" > $VPNDIR/TUNNEL/Parameters
echo "$AUTHENTICATION" > $VPNDIR/TUNNEL/Authentication
if [ "$AUTHENTICATION" = X509 ] ; then
  echo "$REMOTECN" > $VPNDIR/TUNNEL/RemoteCN
else
  echo "$PSK" > $VPNDIR/TUNNEL/PSK
fi
echo "$GATEWAY" > $VPNDIR/Gateway
if [ "`cat $VPNDIR/STATUS`" == up ] ; then
  $SCRIPTS/vpn_ctl $NAME down  
  $SCRIPTS/vpn_ctl $NAME up  
fi


