#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/cp"
cd "$CONFIG"
ENABLED=`cat Enabled 2>/dev/null`
iptables -w -D FORWARD -j CapPort 2>/dev/null
iptables -w -t nat -D PREROUTING -j CapPort 2>/dev/null

if [ "$ENABLED" == yes ] ; then
  iptables -w -A FORWARD -j CapPort 2>/dev/null
  iptables -w -t nat -I PREROUTING 1 -j CapPort 2>/dev/null
fi
