#!/bin/bash
ID="$1"
USERNAME="$2"
CLIENTIP="$3"
#cat <<EOF
radclient 127.0.0.1 acct ZeroShell <<EOF
Acct-Status-Type = Start
Service-Type = Framed-User
User-Name = $USERNAME
Acct-Session-Id = $ID
Framed-IP-Address = $CLIENTIP
Nas-IP-Address = 10.0.0.1
EOF
