#!/bin/sh
. /etc/kerbynet.conf
touch /tmp/cp_auto_starting
CONFIG=$REGISTER/system/cp
TIMEOUT=`cat "$CONFIG/Timeout" 2>/dev/null`
[ -z "$TIMEOUT"  ] && TIMEOUT=2
SLEEPTIME=$((TIMEOUT*30))
[ -d "$CONFIG/Connected" ] || mkdir -p "$CONFIG/Connected/"
cd "$CONFIG"
while true; do
  find "Connected" -type f -name User -cmin +$TIMEOUT -exec $SCRIPTS/cpAutoDisconnect "{}" \;
  rm -f /tmp/cp_auto_starting
  sleep $SLEEPTIME
done
