#!/bin/sh
. /etc/kerbynet.conf
IP="$1"
LCODE="$2"
[ -z "$IP" ] && exit 1
ACCT="`cat $REGISTER/system/acct/Enabled 2>/dev/null`"
CONFIG=$REGISTER/system/cp
CONFIG=$REGISTER/system/cp/Connected
cd $REGISTER/system/cp/Connected || exit 2
if ! [ -d "$IP" ] ; then
  logger -t "CaptivePortal" "GW: Warning: the client $IP is already disconnected"
  exit 10
else
  USER=`cat $IP/User 2>/dev/null`
  MAC=`cat $IP/MAC 2>/dev/null`
  mkdir -p "$REGISTER/system/cp/Disconnected/$IP"
  $SCRIPTS/cp_getaccounting "$USER" "" "$IP" noupdates > "$REGISTER/system/cp/Disconnected/$IP/Accounting"
  echo "$LCODE" > "$REGISTER/system/cp/Disconnected/$IP/LCode"
  RXP=`$SCRIPTS/cp_getRXTX "$IP"|cut -d ' ' -f 1`
  RX=`$SCRIPTS/cp_getRXTX "$IP"|cut -d ' ' -f 2`
  TXP=`$SCRIPTS/cp_getRXTX "$IP"|cut -d ' ' -f 3`
  TX=`$SCRIPTS/cp_getRXTX "$IP"|cut -d ' ' -f 4`
  UUID=`cat $IP/UUID 2>/dev/null`
  NOW=`date +%s`
  STARTED=`cat $IP/Started 2>/dev/null`
  UPDATED=`cat $IP/Updated 2>/dev/null`
  TIMEOUT=`cat $REGISTER/system/cp/Timeout 2>/dev/null`
  TIMEOUT=$((TIMEOUT*60))
  if [ "$((NOW-UPDATED))" -gt "$TIMEOUT" ] ; then
    NOW=$((UPDATED+TIMEOUT))
  fi
  TIME=$((NOW-STARTED-1))
  [ "$ACCT" = yes ] && $SCRIPTS/acct_enqueue_stop "$UUID" "$USER" "$MAC" "$TX" "$RX" "$TXP" "$RXP" "$TIME" "NAS-Request"
  $SCRIPTS/cp_authorize_client no $IP $MAC
  rm -rf "$IP"
  logger -t "CaptivePortal" "GW: Success: user $USER (IP: $IP MAC: $MAC) disconnected"
fi
 
