#!/bin/bash
function IPT {
  IP="$1"
  PORT="$2"
  if [ -z "$OFFLINE" ] ; then
    if iptables -w -L CapPortCRL -n |grep -w $IP |grep -q -w dpt:$PORT ; then
      :
    else
      iptables -w -A CapPortCRL -d $IP -p tcp --dport $PORT -j ACCEPT
      [ "$PORT" = 80 ] && iptables -w -t nat -A CapPortCRL80 -d $IP -j ACCEPT 
#      [ "$PORT" = 443 ] && iptables -w -t nat -A CapPortCRL443 -d $IP -j ACCEPT 
    fi
  else
    if grep -e " -d $IP " "$OFFLINE" 2>/dev/null | grep -q -e " --dport $PORT " ; then
      :
    else
      logger -t CaptivePortal "CRL/OCSP: Success: $IDP ($IP:$PORT) successfully unlocked"
      echo "iptables -w -A CapPortCRL -d $IP -p tcp --dport $PORT -j ACCEPT" >> "$OFFLINE"
      [ "$PORT" = 80 ] && echo "iptables -w -t nat -A CapPortCRL80 -d $IP -j ACCEPT" >> "$OFFLINE"
      # [ "$PORT" = 443 ] && echo "iptables -w -t nat -A CapPortCRL443 -d $IP -j ACCEPT" >> "$OFFLINE" 
    fi
  fi
}
IDPURL="$1"
OFFLINE="$2"
[ -z "$IDPURL" ] && exit 1
IDPURL="$IDPURL/"
IDP=`echo "$IDPURL" | sed -r 's/.*:\/\/([^/?]+)[/?].*/\1/'` 
[ -z "$IDP" ] && exit 2

PORT=`echo "$IDP" | awk -F: '{print $2}'`
PORT=`echo "$PORT" | awk -F/ '{print $1}'`
IDP=`echo "$IDP" | awk -F: '{print $1}'`
IDP=`echo "$IDP" | awk -F/ '{print $1}'`
echo "$PORT" | grep  -q -E '^[0123456789]+$' || PORT=100000
if [ "$PORT" -gt 65535 ] ; then
    PORT=80
fi


ERROR=true
if ipcalc -n "$IDP" |grep -q "INVALID ADDRESS" ; then
  for I in  `host $IDP 2>/dev/null | awk -F'has address ' '{print $2}'` ; do
    ERROR=false
    IPT $I $PORT
  done
else
  ERROR=false
  IP=$IDP
  IPT $IP $PORT
fi
if [ "$ERROR" = true ] ; then
  logger -t CaptivePortal "CRL/OCSP: Warning: $IDP NOT unlocked: address resolution error"
  exit 10
else
  exit 0
fi

