#!/bin/sh
. /etc/kerbynet.conf
LANG="$1"
CONFIG=$REGISTER/system/cp/msg
mkdir -p $CONFIG/custom
cd $CONFIG
if [ -z "$LANG" ] ; then
  LANG=`cat $CONFIG/Lang 2>/dev/null`
  if [ -z "$LANG" ] ; then
    LANG=ENG
  fi
fi
for MSG in `$SCRIPTS/cp_msg MsgList` ; do
  echo "<script>function hint$MSG () { alert(\"`$SCRIPTS/cp_msg $MSG ENG`\");  };</script>"
  echo "<tr><td width=1% style='color:#808080'>&nbsp;&nbsp;$MSG&nbsp;&nbsp;&nbsp;</td><td><input type=text name=$MSG value=\"`$SCRIPTS/cp_msg $MSG $LANG`\" style='width:600' onchange=\"changed()\"></td><td align=center><input type=button name=Hint$MSG value=Hint onclick='hint$MSG()' style=\"font-size: 10\"></td></tr>"
  echo "<script>if (\"$LANG\"!=\"Custom\") {document.data.$MSG.disabled=true;};</script>"

done
