#!/bin/bash
. /etc/kerbynet.conf
IP="$1"
[ -z "$IP" ] && exit 
if [ "`cat $REGISTER/system/acct/Enabled 2>/dev/null`" = yes ] ; then
  [ -d "$REGISTER/system/cp/Connected/$IP" ] && exit
  LCODE=`cat "$REGISTER/system/cp/Disconnected/$IP/LCode" 2>/dev/null`
  if [ -n "$LCODE" ] ; then
    LMSG=`$SCRIPTS/acct_limit_msg $LCODE`
    echo "$LMSG"
  fi

fi

