#!/bin/sh
. /etc/kerbynet.conf
MSG="$1"
LANG="$2"
[ -z "$MSG" ] && exit 1
MSGLIST="USER USERNAME PASSWORD DOMAIN UserNameNoEmpty PwNoEmpty NetworkAccess Disconnect SuccessAuth Connecting Connected NotConnected UserUnknown AccountInfo AccessDenied SystemError NoSimultaneous Time Traffic Cost Credit CLOSE DisconnectionAlert RenewAuth DoNotClose NoValidCertificate PleaseWaitAuth Expired NoCredit NoTraffic NoTime"
if [ "$MSG" == MsgList ] ; then
  echo "$MSGLIST"
  exit 0
fi
CONFIG=$REGISTER/system/cp/msg
mkdir -p $CONFIG/custom
cd $CONFIG
if [ -z "$LANG" ] ; then
  LANG=`cat $CONFIG/Lang 2>/dev/null`
  if [ -z "$LANG" ] ; then
    LANG=ENG
  fi
fi
if [ "$LANG" == Custom -a -r "$CONFIG/custom/$MSG" ] ; then
  cat "$CONFIG/custom/$MSG"
  echo
  exit 0
fi
if [ "$LANG" == ENG -o "$LANG" == Custom ] ; then
  case "$MSG" in
  USER)
    echo "User"
  ;;
  USERNAME)
    echo "Username"
  ;;
  PASSWORD)
    echo "Password"
  ;;
  DOMAIN)
    echo "Domain"
  ;;
  UserNameNoEmpty)
    echo "The Username cannot be empty."
  ;;
  PwNoEmpty)
    echo "The Password cannot be empty."
  ;;
  NetworkAccess)
    echo "Network Access"
  ;;
  Disconnect)
    echo "Disconnect"
  ;;
  SuccessAuth)
    echo "successfully authenticated"
  ;;
  Connecting)
    echo "Connecting to the Network..."
  ;;
  Connected)
    echo "connected"
  ;;
  NotConnected)
    echo "not connected"
  ;;
  UserUnknown)
    echo "User unknown or invalid password."
  ;;
  AccountInfo)
    echo "If you do not have an account, read the instructions by clicking on the follow link to obtain one."
  ;;
  AccessDenied)
    echo "Access Denied !!!"
  ;;
  SystemError)
    echo "SYSTEM ERROR:<br>contact the system Administrator to know more details"
  ;;
  NoSimultaneous)
    echo "Simultaneous connections are not allowed."
  ;;
  Time)
    echo "Time"
  ;;
  Traffic)
    echo "Traffic"
  ;;
  Cost)
    echo "Cost"
  ;;
  Credit)
    echo "Credit"
  ;;
  CLOSE)
    echo "Close"
  ;;
  DisconnectionAlert)
    echo "Warning: you will be disconnected from the network."
  ;;
  DoNotClose)
    echo "Do not close this window to stay connected."
  ;;
  RenewAuth)
    echo "Renewing Authentication ..."
  ;;
  NoValidCertificate)
    echo "No valid X.509 certificate was found in the browser."
  ;;
  PleaseWaitAuth)
    echo "Please wait, authenticating"
  ;;
  Expired)
    echo "Account Expired"
  ;;
  NoCredit)
    echo "No credit available"
  ;;
  NoTraffic)
    echo "Traffic limit reached"
  ;;
  NoTime)
    echo "Time limit reached"
  ;;
  esac
  exit 0
fi
 
if [ "$LANG" == ITA ] ; then
  case "$MSG" in
  USER)
    echo "Utente"
  ;;
  USERNAME)
    echo "Nome Utente"
  ;;
  PASSWORD)
    echo "Password"
  ;;
  DOMAIN)
    echo "Dominio"
  ;;
  UserNameNoEmpty)
    echo "Nome Utente vuoto"
  ;;
  PwNoEmpty)
    echo "Password vuota"
  ;;
  SuccessAuth)
    echo "autenticato con successo"
  ;;
  NetworkAccess)
    echo "Accesso alla Rete"
  ;;
  Disconnect)
    echo "Disconnetti"
  ;;
  Connecting)
    echo "Connessione alla Rete in corso..."
  ;;
  CLOSE)
    echo "Chiudi"
  ;;
  DisconnectionAlert)
    echo "Attenzione: sarai disconnesso dalla rete."
  ;;
  DoNotClose)
    echo "Non chiudere questa finestra per rimanere connesso."
  ;;
  RenewAuth)
    echo "Rinnovo Autenticazione ..."
  ;;
  Connected)
    echo "connesso"
  ;;
  NotConnected)
    echo "non connesso"
  ;;
  UserUnknown)
    echo "Utente sconosciuto o password non corretta."
  ;;
  AccountInfo)
    echo "Se non hai un account, leggi le istruzioni cliccando sul seguente link per ottenerne uno."
  ;;
  AccessDenied)
    echo "Accesso Negato !!!"
  ;;
  SystemError)
    echo "ERRORE DI SISTEMA:<br>contatta l'amministratore per maggiori dettagli"
  ;;
  NoSimultaneous)
    echo "Connessioni simultanee non permesse."
  ;;
  Time)
    echo "Tempo"
  ;;
  Traffic)
    echo "Traffico"
  ;;
  Cost)
    echo "Costo"
  ;;
  Credit)
    echo "Credito"
  ;;
  NoValidCertificate)
    echo "Nessun certificato X.509 valido e' stato trovato nel browser."
  ;;
  PleaseWaitAuth)
    echo "Prego attendere, autenticazione di"
  ;;
  Expired)
    echo "Account Scaduto"
  ;;
  NoCredit)
    echo "Credito non disponibile"
  ;;
  NoTraffic)
    echo "Limite di traffico raggiunto"
  ;;
  NoTime)
    echo "Limite di tempo raggiunto"
  ;;
  esac
  exit 0
fi
 
