#!/bin/sh
. /etc/kerbynet.conf


if cd "$REGISTER/system/cp/Auth/X509/CAs" ; then
  CAs=`ls *.0 2>/dev/null`
  for CA in $CAs ; do
    HASH=${CA%.0}
    if ! [ -r "$CA" ] ; then
       rm -f "$CA" "${HASH}.r0"
    fi
  done
fi
cd "/etc/ssl/certs/trusted_CAs/" || exit 1
CAs=`ls *.0 2>/dev/null`
I=0
for CA in $CAs ; do
  HASH=${CA%.0}
  if [ -f "$REGISTER/system/cp/Auth/X509/CAs/$CA" ] ; then
     CHECKED=checked
  else
     CHECKED=""
  fi
  CN=`/usr/local/ssl/bin/openssl x509 -in "$CA" -text -noout |grep Subject: |awk -F'Subject: ' '{print $2}'| awk -F'CN=' '{print $2}' |sed -r 's/(.*).*, [A-Z]{1,2}=.*/\1/'`
  if [ -z "$CN" ] ; then
    CN=`/usr/local/ssl/bin/openssl x509 -in "$CA" -text -noout |grep Subject: |awk -F'Subject: ' '{print $2}'`
  fi
  I=$((I+1))
  echo "<tr><td><input type=checkbox name='CA$I' value='$HASH' onclick='changed()' $CHECKED>&nbsp;$CN</td></tr>"
done
