#!/bin/sh
. /etc/kerbynet.conf
IP="$1"
[ "$IP" == Any ] && IP=""
MAC="$2"
[ "$MAC" == Any ] && MAC=""
if ! [ -z "$IP" ] ; then
  SOURCE="-s $IP"
fi
if ! [ -z "$MAC" ] ; then
  SOURCE="$SOURCE -m mac --mac-source $MAC"
fi
iptables -w -A CapPortFC $SOURCE -j ACCEPT
iptables -w -t nat -D CapPortHTTP $SOURCE -j CapPortProxy 2>/dev/null
iptables -w -t nat -D CapPortHTTPS $SOURCE -j ACCEPT 2>/dev/null
iptables -w -t nat -D CapPortGW $SOURCE -j ACCEPT 2>/dev/null
iptables -w -t nat -I CapPortHTTP 1 $SOURCE -j CapPortProxy
iptables -w -t nat -I CapPortHTTPS 1 $SOURCE -j ACCEPT
iptables -w -t nat -I CapPortGW 1 $SOURCE -j ACCEPT


