#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/cp
cd $CONFIG/Connected || mkdir -p $CONFIG/Connected
CLIENTS=`ls -d * 2>/dev/null`
iptables -w -F CapPortWL
iptables -w -F CapPortOut
NCLIENTS=0
for IP in $CLIENTS ; do
  MAC=`cat $IP/MAC 2>/dev/null`
  TXP=`cat $IP/TX-Packets 2>/dev/null`
  RXP=`cat $IP/RX-Packets 2>/dev/null`
  TXO=`cat $IP/TX-Octets 2>/dev/null`
  RXO=`cat $IP/RX-Octets 2>/dev/null`
  $SCRIPTS/cp_authorize_client yes "$IP" "$MAC" "$TXP" "$TXO" "$RXP" "$RXO" && NCLIENTS=$((NCLIENTS+1))
done
echo $NCLIENTS
