#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/cp
cd $CONFIG/FreeServices
SERVICES=`ls -d * 2>/dev/null`
iptables -w -F CapPortFS
for S in $SERVICES ; do
  IP=`cat $S/IP`
  Port=`cat $S/Port`
  Proto=`cat $S/Proto`
  $SCRIPTS/cpAddServiceIPT "$IP" "$Port" "$Proto" 
done
