#!/bin/sh
. /etc/kerbynet.conf
IP="$1"
[ "$IP" == Any ] && IP=""
PORT="$2"
PROTO="$3"
if [ -z "$IP" ] ; then
  DEST=""
else
  DEST="-d $IP"
fi
iptables -w -D CapPortFS $DEST -p $PROTO --dport $PORT -j ACCEPT
if [ "$PROTO" == "tcp" ] ; then
  if [ "$PORT" == 80 ] ; then
    iptables -w -t nat -D CapPortHTTP $DEST -p $PROTO --dport $PORT -j CapPortProxy
  fi
  if [ "$PORT" == 443 ] ; then
    iptables -w -t nat -D CapPortHTTPS $DEST -p $PROTO --dport $PORT -j ACCEPT
  fi
fi
