#!/bin/sh
. /etc/kerbynet.conf
CLT="$1"
[ -z "$CLT" ] && exit 1
CONFIG=$REGISTER/system/cp/FreeClients

IP=`cat $CONFIG/$CLT/IP`
MAC=`cat $CONFIG/$CLT/MAC`
$SCRIPTS/cpRemoveClientIPT "$IP" "$MAC"

rm -rf "$CONFIG/$CLT"

