#!/bin/sh
. /etc/kerbynet.conf
SRV="$1"
[ -z "$SRV" ] && exit 1
CONFIG=$REGISTER/system/cp/FreeServices
IP=`cat $CONFIG/$SRV/IP`
PORT=`cat $CONFIG/$SRV/Port`
PROTO=`cat $CONFIG/$SRV/Proto`
$SCRIPTS/cpRemoveServiceIPT "$IP" "$PORT" "$PROTO"
rm -rf "$CONFIG/$SRV"

