#!/bin/sh
. /etc/kerbynet.conf
USER="$1"
CPW="$2"
PW="$3"
MODE="$4"
if [ -z "$PW" ] ; then
  echo "Password cannot be empty." >&2
  exit 1
fi
if [ "`echo "$USER" | awk '{print tolower($0)}'`" == admin ] ; then
   ADMIN=yes
   USER=admin
fi
if [ "$MODE" != NOCHECKPW ] ; then 
  if [ "$ADMIN" == yes ] ; then
    if [ "$CPW" != "`cat $REGISTER/system/ldap/rootpw 2>/dev/null`" ] ; then
      echo "Current password incorrect." >&2     
      exit 2
    fi  
  else
    if ! echo "$CPW" | kinit "$USER" >/dev/null 2>/dev/null ; then
      echo "Current password incorrect." >&2
      exit 2
    fi
    kdestroy
  fi
fi
CHANGED=no
if [ "$MODE" != NOCHECKPW ] ; then
  if echo -e "$CPW\n$PW\n$PW" | kpasswd "$USER"  >/tmp/kpasswd.error ; then
    CHANGED=yes
  else
    grep -v "^Password for" /tmp/kpasswd.error |grep -v "^Enter new password:" |grep -v "^Enter it again:" >&2
  fi
else
  ENCLIST="`$SCRIPTS/k5enclist \"$USER\"`"
  if kadmin.local -q "cpw -e \"$ENCLIST\" -pw \"$PW\" \"$USER\"" | grep -q " changed."  ; then
    CHANGED=yes
  fi
fi
ENCLIST="`$SCRIPTS/k5enclist \"$USER\"`"
if [ "$CHANGED" == yes ] ; then
  $SCRIPTS/cpwldap "$USER" "$PW"
else
  exit 3
fi
