#!/bin/sh
. /etc/kerbynet.conf
DIRECTORY="$1"
BASE="$2"
PW="$3"
HOSTNAME="$4"
ACTION="$5"
IP="$6"
[ -z "$DIRECTORY" ] && exit 1
[ -z "$BASE" ] && exit 1

TMP=`echo $BASE |awk -F"," '{print $1}'`
TYPE=`echo $TMP |awk -F"=" '{print $1}'`
CONTAINER=`echo $TMP |awk -F"=" '{print $2}'`
Host=`echo $HOSTNAME |awk -vRS=. '{print $1}'|head -1`
Domain=`echo $HOSTNAME | awk -vRS=. 'BEGIN {getline};{printf ".%s",$0}'`
Domain=${Domain:1}
if echo $TYPE | egrep -w -i -q 'o' ; then
cat <<EOF >/tmp/template.ldif
dn: $BASE 
o: $CONTAINER
objectclass: top
objectclass: organization
EOF
fi
if echo $TYPE | egrep -w -i -q 'dc' ; then
cat <<EOF >/tmp/template.ldif
dn: $BASE
dc: $CONTAINER
objectclass: top
objectClass: domain
EOF
fi
egrep "^include" /etc/openldap/slapd.conf |egrep ".schema$" > /tmp/slapadd.conf
cat <<EOF >> /tmp/slapadd.conf
database        bdb
suffix          "$BASE"
directory       "$DIRECTORY"
EOF
egrep "^index " /etc/openldap/slapd.conf >> /tmp/slapadd.conf
mkdir $DIRECTORY 2>/dev/null
rm -f $DIRECTORY/*
SED="s/xvar/$BASE/g"
sed -e "$SED" < $TEMPLATE/template.ldif >> /tmp/template.ldif

cat <<EOF >> /tmp/template.ldif
dn: uid=admin,ou=People,$BASE
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: top
objectClass: shadowAccount
objectClass: organizationalPerson
uid: admin
cn: System Administrator
uidNumber: 0
gidNumber: 0
gecos: System Administrator
homeDirectory: /root
loginShell: /bin/sh
sn: Administrator
givenName: System

dn: cn=nobody,ou=Group,$BASE
objectClass: posixGroup
objectClass: top
cn: nobody
gidNumber: 65534

dn: cn=admin,ou=Radius,$BASE
objectClass: organizationalPerson
objectClass: top
objectClass: radiusprofile
cn: admin
dialupAccess: yes
sn: $PW

dn: cn=$HOSTNAME,ou=Computers,$BASE
objectClass: Computers
objectClass: top
cn: $HOSTNAME
hostname: $Host
domain: $Domain
descr: ZeroShell Net Services Server

EOF

if true ; then
  HN=$Host.example.com
  #ETH00IP="`cat /var/register/system/net/interfaces/ETH00/IP/00/IP 2>/dev/null`"
  
  cat <<EOF >> /tmp/template.ldif
dn: dc=com,ou=DNS,$BASE
objectClass: top
objectClass: domain
dc: com

dn: dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: domain
dc: example

dn: relativeDomainName=@,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: @
zoneName: example.com
nSRecord: ${HN}.
sOARecord: ${HN}. hostmaster.${HN}. 2006062400 86400 7200 3600000 172800

dn: relativeDomainName=$Host,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: $Host
zoneName: example.com
aRecord: $IP
hInfoRecord: "x86  Box" "ZeroShell - Net Services"

dn: relativeDomainName=kerberos,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: kerberos
zoneName: example.com
cNAMERecord: $Host

dn: relativeDomainName=_kerberos,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: _kerberos
zoneName: example.com
tXTRecord: "EXAMPLE.COM"

dn: relativeDomainName=_kerberos._udp,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: _kerberos._udp
zoneName: example.com
sRVRecord: 0 0 88 kerberos

dn: relativeDomainName=_kerberos-adm._tcp,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: _kerberos-adm._tcp
zoneName: example.com
sRVRecord: 0 0 749 kerberos

dn: relativeDomainName=_kpasswd._udp,dc=example,dc=com,ou=DNS,$BASE
objectClass: top
objectClass: dNSZone
relativeDomainName: _kpasswd._udp
zoneName: example.com
sRVRecord: 0 0 464 kerberos

EOF
fi

if slapadd -f /tmp/slapadd.conf < /tmp/template.ldif  ; then
  slapindex -f /tmp/slapadd.conf
else
  exit 1
fi
 
