#!/bin/sh
. /etc/kerbynet.conf
killall -w ctwatcher 2>/dev/null
killall -w conntrack 2>/dev/null
ENABLED="`cat $REGISTER/system/net/FW/ConnTrackLog/Enabled 2>/dev/null`"
if [ "$ENABLED" == yes ] ; then
  $SCRIPTS/ctwatcher &
else
  logger -t ConnTrack "Connection Tracking Logger: DISABLED"
fi
