#!/bin/sh
. /etc/kerbynet.conf
NEW="`cat $REGISTER/system/net/FW/ConnTrackLog/NewConnection 2>/dev/null`"
DESTROY="`cat $REGISTER/system/net/FW/ConnTrackLog/DestroyConnection 2>/dev/null`"
UPDATES="`cat $REGISTER/system/net/FW/ConnTrackLog/UpdatesConnection 2>/dev/null`"
EMASK=''
if [ "$NEW" == yes ] ; then
  EMASK="$EMASK,NEW"
fi 
if [ "$DESTROY" == yes ] ; then
  EMASK="$EMASK,DESTROY"
fi 
if [ "$UPDATES" == yes ] ; then
  EMASK="$EMASK,UPDATES"
fi
EMASK=${EMASK:1}
if [ -z "$EMASK" ] ; then
  EMASK=ALL
fi
logger -t ConnTrack "Connection Tracking Logger: ENABLED"
logger -t ConnTrack "Events to log: $EMASK"
while true ; do
  conntrack -E -e $EMASK | $SCRIPTS/ctfilter | logger -t ConnTrack
  logger -t Administration "Connection Tracking system automatically restarted"
done
