#!/bin/sh
. /etc/kerbynet.conf

function STATUS {
  logger -t DaemonWatcher "++++++++++++++++++++++++++++++++++++"
  logger -t DaemonWatcher "## SERVICE STATUS                 ##"
  logger -t DaemonWatcher "++++++++++++++++++++++++++++++++++++"
  if ! ldapsearch -h 127.0.0.1 -x -b "`cat $REGISTER/system/ldap/base`" -s base dn 2>/dev/null >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "LDAP : $STATUS"
  if ! pidof named >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "DNS : $STATUS"
  if ! pidof krb5kdc >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "Kerberos 5 : $STATUS"
  if ! pidof dhcpd >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "DHCP : $STATUS"
  if ! pidof radiusd >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "RADIUS : $STATUS"
  if ! pidof sshd >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "SSH : $STATUS"
  if ! pidof havp >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "HTTP PROXY : $STATUS"
  if $SCRIPTS/proxy_status |grep -q ACTIVE ; then
    if ! pidof freshclam >/dev/null ; then
      STATUS=DOWN
    else
      STATUS=UP
    fi
  fi
  logger -t DaemonWatcher "CLAMAV-UPDATE : $STATUS"
  if ! ps -e | grep -w -q 'ipmonitor$' >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "NetBalancer Routing Monitor : $STATUS"
  if ! ps -e | grep -w -q failoverd >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "NetBalancer ICMP Failover monitor : $STATUS"
  if ! ps -e | grep -w -q gw_l2checkd >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "NetBalancer Layer 2 Gateway monitor : $STATUS"
  if ! ps -e | grep -w -q bandwidthd >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "Bandwidthd Daemon : $STATUS"
  if ! ps -e | grep -w -q 'mrtg$' >/dev/null ; then
     STATUS=DOWN
  else
     STATUS=UP
  fi
  logger -t DaemonWatcher "MRTG Daemon : $STATUS"
  logger -t DaemonWatcher "++++++++++++++++++++++++++++++++++++"
}
logger -t DaemonWatcher "Daemon Watcher has started"
STATUS
while true; do
  sleep 57
  if [ "`date +%H%M`" == 0002 ] ; then
    STATUS
  fi
  #VPNFAIL=`$SCRIPTS/checkvpn`
  #if [ $? -ne 0 ] ; then
  #  logger -t DaemonWatcher "VPN ($VPNFAIL) restarted"
  #fi
  if ! ldapsearch -h 127.0.0.1 -x -b "`cat $REGISTER/system/ldap/base`" -s base dn 2>/dev/null >/dev/null ; then
    /etc/init.d/ldap restart >/dev/null 2>/dev/null
    logger -t DaemonWatcher "LDAP service restarted"
    sleep 5
  fi
  if ! pidof named >/dev/null ; then
    /etc/init.d/dns restart >/dev/null 2>/dev/null
    logger -t DaemonWatcher "DNS service restarted"
    sleep 5
  fi
  if ! pidof krb5kdc >/dev/null ; then
    /etc/init.d/kerberos5 restart >/dev/null 2>/dev/null
    logger -t DaemonWatcher "Kerberos 5 service restarted"
    sleep 5
  fi
  if [ -r /tmp/dhcpd_started ] ; then 
    if ! pidof dhcpd >/dev/null ; then
       $SCRIPTS/dhcp_start noconfig 
       logger -t DaemonWatcher "DHCP service restarted"
       sleep 5
    fi
  fi
  if [ "`cat $REGISTER/system/radius/Enabled 2>/dev/null`" == checked ] ; then 
    if ! pidof radiusd >/dev/null ; then
       /etc/init.d/radius restart >/dev/null 2>/dev/null
       logger -t DaemonWatcher "RADIUS service restarted"
       sleep 5
    fi
  fi
  if [ "`cat $REGISTER/system/ssh/Enabled 2>/dev/null`" == yes ] ; then 
    if ! pidof sshd >/dev/null ; then
       /etc/init.d/sshd restart >/dev/null 2>/dev/null
       logger -t DaemonWatcher "SSH service restarted"
       sleep 5
    fi
  fi
  if [ "`cat $REGISTER/system/havp/Enabled 2>/dev/null`" == yes ] ; then 
    if ! pidof havp >/dev/null ; then
       /etc/init.d/proxy start >/dev/null 2>/dev/null
       logger -t DaemonWatcher "HTTP PROXY service restarted"
       sleep 5
    fi
    if $SCRIPTS/proxy_status |grep -q ACTIVE ; then
      if ! pidof freshclam >/dev/null ; then
	 $SCRIPTS/ClamAV-Update
         logger -t DaemonWatcher "CLAMAV-UPDATE service restarted"
         sleep 5
      fi
    fi 
  fi
  if [ "`cat $REGISTER/system/net/nb/Enabled 2>/dev/null`" == yes ] ; then
    
 
    if [ "`cat $REGISTER/system/net/nb/FO/ICMPCheck 2>/dev/null`" == yes ] ; then 
      if ! ps -e | grep -w -q 'ipmonitor$' >/dev/null ; then
        $SCRIPTS/routeupd_start >/dev/null 2>/dev/null
        logger -t DaemonWatcher "NetBalancer Routing Monitor restarted" 
      fi
      if [ "`cat $REGISTER/system/net/nb/FO/EnabledIP1 2>/dev/null`" == yes -o "`cat $REGISTER/system/net/nb/FO/EnabledIP2 2>/dev/null`" == yes -o "`cat $REGISTER/system/net/nb/FO/EnabledIP3 2>/dev/null`" == yes ] ; then 
        if ! ps -e | grep -w -q failoverd ; then
          if ! ps -e | grep -w -q nb_testfo ; then 
            $SCRIPTS/nb_startfo >/dev/null 2>/dev/null
            logger -t DaemonWatcher "NetBalancer ICMP Failover Monitor restarted"
            sleep 5
          fi
        fi 
      fi
    else
      if ! ps -e | grep -w -q gw_l2checkd ; then
        if ! ps -e | grep -w -q nb_testfo ; then
          $SCRIPTS/nb_startfo >/dev/null 2>/dev/null
          logger -t DaemonWatcher "NetBalancer Layer 2 Gateway Monitor restarted"
          sleep 5
        fi  
      fi
    fi
  fi
  if [ "`cat $REGISTER/system/bandwidthd/Enabled 2>/dev/null`" == yes ] ; then 
    if ! pidof bandwidthd >/dev/null ; then
       /etc/init.d/bandwidthD restart >/dev/null 2>/dev/null
       logger -t DaemonWatcher "Bandwidthd service restarted"
       sleep 5
    fi
  fi
  if ! ps -e | grep -w -q 'mrtg$' 2>/dev/null ; then
    /etc/init.d/mrtg restart >/dev/null 2>/dev/null
    logger -t DaemonWatcher "MRTG service restarted"
    sleep 5
  fi
  #if [ -d  /sys/class/net/wlan0/ ] ; then
  #  $SCRIPTS/wifi-checkpower
  #fi
done
