#!/bin/sh
. /etc/kerbynet.conf
SUBNET="$1"
ENTRY="$2"
[ -z "$SUBNET" -o -z "$ENTRY" ] && exit 1
CONFIG="$REGISTER/system/dhcp"

if ! [ -d $CONFIG/subnets/$SUBNET ] ; then
  echo "Subnet does not exist." 1>&2
  exit 3
fi
echo $CONFIG/subnets/$SUBNET/Statics/$ENTRY
if ! [ -d $CONFIG/subnets/$SUBNET/Statics/$ENTRY ] ; then
  echo "Entry does not exist." 1>&2
  exit 5
fi
rm -rf "$CONFIG/subnets/$SUBNET/Statics/$ENTRY"
$SCRIPTS/dhcp_start
exit 0
