#!/bin/sh
. /etc/kerbynet.conf
function GOOD {
  if [ "$DHCPD" != ACTIVE ] ; then
    killall dhcpd 2> /dev/null
  fi
  cp $TMP $REGISTER/system/dhcp/dhcpd.conf
  exit 0
}
CONFIG="$REGISTER/system/dhcp"
TMP=/tmp/dhcpd.conf
TMPSUBNETS=/tmp/subnets
OUTPUT=/tmp/dhcpd_tmp
rm -rf $TMPSUBNETS
mkdir $TMPSUBNETS

if ps -e |grep -q -w dhcpd ; then
  DHCPD=ACTIVE
fi

cd $CONFIG/subnets
SUBNETS=`ls -d [0123456789][0123456789] 2>/dev/null`
if ! [ -z "$SUBNETS" ] ; then
  for S in $SUBNETS ; do
    ln -s $CONFIG/subnets/$S $TMPSUBNETS
  done
  for N in `seq 1 20` ; do
    $SCRIPTS/dhcp_configfile > $TMP
    if ! grep -q subnet $TMP ; then
       GOOD
    fi
    if ! dhcpd -t -cf $TMP 2> $OUTPUT ; then
      exit 2
    fi
    if ! dhcpd -T -cf $TMP -lf $REGISTER/system/dhcp/dhcpd.leases 2> $OUTPUT ; then
      rm -f $REGISTER/system/dhcp/dhcpd.leases
      touch $REGISTER/system/dhcp/dhcpd.leases
      if ! dhcpd -T -cf $TMP -lf $REGISTER/system/dhcp/dhcpd.leases 2> $OUTPUT ; then
        exit 3
      fi
    fi
    if dhcpd -cf $TMP -lf $REGISTER/system/dhcp/dhcpd.leases 2> $OUTPUT ; then
      GOOD
    else
      if grep -q "matches multiple shared networks" $OUTPUT ; then
        IF=`grep "matches multiple shared networks" $OUTPUT |awk '{print $2}'`
        IPS=`ip addr show dev $IF |grep inet |awk '{print $2}' |awk -F"/" '{print $1}'`
        cd $TMPSUBNETS
        rm -rf shared
        mkdir shared
        SHARED=""
        for IP in $IPS ; do
          SUBNETS=`ls -d [0123456789][0123456789] 2>/dev/null`
          for S in $SUBNETS ; do
            NW=`cat $S/Network`
            NM=`cat $S/Netmask`
            if $SCRIPTS/ip_belongs_network $IP $NW $NM ; then
              mv $S shared
              SHARED="${SHARED}_${NW}M${NM}"
            fi            
          done
        done
        if ! [ -z "$SHARED" ] ; then
          mv shared "SN$SHARED"
        fi
      fi    
    fi
  done
  exit 1
else
  echo > $REGISTER/system/dhcp/dhcpd.conf 
fi
