#!/bin/awk -f
BEGIN {
   ONLYACTIVE=ENVIRON["ONLYACTIVE"];
}
/^lease .* {/ {
  IP=$2
  getline;
  NLINE=0
  HOSTNAME="";
  STARTS="";
  ENDS="";
  MAC="";
  STATE="";
  while ($0!="}" && NLINE<20) {
    if ($1=="starts") {
      STARTS=$3 " " $4 ;
      STARTS=substr(STARTS,1,length(STARTS)-1);
    }
    if ($1=="ends") {
      ENDS=$3 " " $4 ;
      ENDS=substr(ENDS,1,length(ENDS)-1);
    }
    if ($1=="hardware" && $2=="ethernet") {
      MAC=$3;
      MAC=substr(MAC,1,length(MAC)-1);
    }
    if ($1=="binding" && $2=="state") {
      STATE=$3;
      STATE=substr(STATE,1,length(STATE)-1);
    }
    if ($1=="client-hostname") {
      HOSTNAME=substr($2$3$4$5$6$7,2);
      HOSTNAME=substr(HOSTNAME,1,length(HOSTNAME)-2);
    } 
    
   
    getline;
    NLINE++;
  }
  if (ONLYACTIVE!="yes" || STATE=="active") {
    printf "%s!%s!%s!%s!%s!%s\n", IP,MAC,HOSTNAME,STATE,STARTS,ENDS;
  }
}





