#!/bin/sh
. /etc/kerbynet.conf
SUBNET="$1"
PARAMETERS="$2"
[ -z "$SUBNET" ] && exit 1
CONFIG="$REGISTER/system/dhcp"
if ! [ -d $CONFIG/subnets/$SUBNET ] ; then
  echo "Subnet does not exist." 1>&2
  exit 3
fi
echo "$PARAMETERS" > $CONFIG/subnets/$SUBNET/Parameters
$SCRIPTS/dhcp_start
