#!/bin/sh
. /etc/kerbynet.conf
DNS="$1"
WHAT="$2"
TYPE="$3"
ERROR="$4"

[ -z "$WHAT" ] && exit 0
[ -z "$TYPE" ] && TYPE=any
[ -z "$DNS" ] && DNS=localhost
if ! host -v -t $TYPE "$WHAT" $DNS > /tmp/dns_query.out ; then
  echo "<font color=#F00000 class=Bigger1><b>RESOLVER ERROR:</b></font>"
  echo
  cat /tmp/dns_query.out
  echo
  if [ "$ERROR" == BINDERROR ] ; then
    if grep -q "(NXDOMAIN)" /tmp/dns_query.out ; then
      $SCRIPTS/getbinderror 
    fi 
    if grep -q "(SERVFAIL)" /tmp/dns_query.out ; then
      $SCRIPTS/getbinderror
    fi
  fi
else
  cat /tmp/dns_query.out
fi



