#!/bin/sh
. /etc/kerbynet.conf
ZONE="$1"
[ -z "$ZONE" ] && exit 1
BASE=`cat $REGISTER/system/ldap/base`
DCZ=`echo "$ZONE" | awk -vRS=. '{printf "dc=%s,",$1}'`
ldapsearch -LLL -x -b"${DCZ}ou=DNS,$BASE" zoneName=$ZONE dn |egrep ^dn: |awk -F"dn: " '{print $2}' | ldapdelete -r -x -D"cn=Manager,`$SCRIPTS/getkey /system/ldap/base`" -w "`$SCRIPTS/getkey /system/ldap/rootpw`"
SEP=`echo "$DCZ" | awk -F"," '{print $1}'`
while ! [ -z "$SEP" ] ; do
  echo "${DCZ}ou=DNS,$BASE" | ldapdelete -x -D"cn=Manager,`$SCRIPTS/getkey /system/ldap/base`" -w "`$SCRIPTS/getkey /system/ldap/rootpw`"
  DCZ=`echo "$DCZ" | awk -F"$SEP," '{print $2}'`
  SEP=`echo "$DCZ" | awk -F"," '{print $1}'`
done
$SCRIPTS/dns_start

