#!/bin/sh
. /etc/kerbynet.conf
LOCAL="$1"
ACLs="$2"
REJECT="$3"
[ -f "$REGISTER/system/dns/Clients/Reject" ] || echo Any > $REGISTER/system/dns/Clients/Reject
cp $REGISTER/system/dns/Clients/Local  /tmp/Local.1
cp $REGISTER/system/dns/Clients/ACL  /tmp/ACL.1
cp $REGISTER/system/dns/Clients/Reject  /tmp/Reject.1
echo "$LOCAL" > $REGISTER/system/dns/Clients/Local
if ! [ -z "$ACLs" ] ; then
  echo "$ACLs" | tr " " "\n" >$REGISTER/system/dns/Clients/ACL
else
  echo -n > $REGISTER/system/dns/Clients/ACL
fi

echo "$REJECT" > $REGISTER/system/dns/Clients/Reject
if $SCRIPTS/dns_hup 2>/dev/null ; then
    rm -f /tmp/Local.1 /tmp/ACL.1 /tmp/Reject.1
else
  mv /tmp/Local.1 $REGISTER/system/dns/Clients/Local
  mv /tmp/ACL.1 $REGISTER/system/dns/Clients/ACL    
  mv /tmp/Reject.1 $REGISTER/system/dns/Clients/Reject
  exit 1
fi


