#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
TAG="$2"
DESCRIPTION="$3"
[ -z "$INTERFACENAME" -o -z "$TAG" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
INTERFACE=`echo $INTERFACENAME |cut -d. -f1`
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
VLANDIR="$IDIR/VLAN/$TAG"
if ! [ -d "$VLANDIR" ] ; then
   echo "VLAN $TAG doesn't exist." 1>&2
   exit 3
fi
echo $DESCRIPTION > $VLANDIR/Description
setallbridgedinterface $INTERFACE
