#!/bin/sh
. /etc/kerbynet.conf
DEV="$1"
FS="$2"
LABEL="$3"
COD="$4"
if echo $DEV | egrep -q "/c[0123456789]d[0123456789]p[123456789]+" ; then
  DISK=`echo "$DEV" | sed -r 's/(.*\/c[0123456789]d[0123456789])p[0123456789]+/\1/'`
else
  DISK=`echo "$DEV" | sed -r 's/(.*[^0123456789])[0123456789]+/\1/'`
fi
ID=`fdisk -l "$DISK"  |grep -w ^$DEV | sed 's/*/ /' | awk '{print $2 $3}'`
[ "$COD" != "$ID" ] && exit 1

if [ "$FS" == "ext3" -o "$FS" == "ext2" -o "$FS" == ext4 ] ; then
    mkfs -t $FS ${DEV} 2> /dev/null > /dev/null || exit 1
    e2label ${DEV} "$LABEL"
fi
if [ "$FS" == "reiserfs" ] ; then
    mkfs -t $FS -q -l "$LABEL" ${DEV}

fi

