#!/bin/sh
. /etc/kerbynet.conf
CHAIN="$1"
[ -z "$CHAIN" ] && exit 1
CONFIG="$REGISTER/system/net/FW"
if ! [ -r "$CONFIG/tmp/Chains/$CHAIN/NotSaved" ] ; then
  echo "chain not updated." >&2
  exit 2
fi
rm -rf  "$CONFIG/tmp/Chains/$CHAIN/"

