#!/bin/sh
. /etc/kerbynet.conf
CHAIN="$1"
RULE="$2"
[ -z "$CHAIN" -a -z "$RULE" ] && exit 1
CONFIG="$REGISTER/system/net/FW/tmp"
if [ -d "$CONFIG/Chains/$CHAIN/Rules/$RULE" ] ; then
  rm -rf "$CONFIG/Chains/$CHAIN/Rules/$RULE"
  echo yes > "$CONFIG/Chains/$CHAIN/NotSaved"
  $SCRIPTS/fw_reorder $CHAIN
else
  echo "Rule does not exist" >&2
  exit 2
fi
