#!/bin/sh
. /etc/kerbynet.conf
CHAIN="$1"
[ -z "$CHAIN" ] && exit 1
NUM=0
CONFIG="$REGISTER/system/net/FW/tmp/Chains/"
if [ -d $CONFIG/$CHAIN/Rules ] ; then
  cd $CONFIG/$CHAIN/Rules
  RULES=`ls`
  for RULE in $RULES ; do
    NUM=$RULE
    if [ "${NUM:0:1}" == 0 ] ; then
      NUM=${NUM:1:2}
    fi
    if [ "${NUM:0:1}" == 0 ] ; then
      NUM=${NUM:1:1}
    fi
    DESCRIPTION="`cat $RULE/Description 2>/dev/null`"
    IPT="`cat $RULE/IPT 2>/dev/null`"
    INPUT="`cat $RULE/Input 2>/dev/null`"
    if [ -z "$INPUT" ] ; then
      INPUT='*'
    else
      if [ "`cat $RULE/NotInput 2>/dev/null`" == checked ] ; then
        NOTINPUT='! '
      else
        NOTINPUT=''
      fi
    fi
    OUTPUT="`cat $RULE/Output 2>/dev/null`"
    if [ -z "$OUTPUT" ] ; then
      OUTPUT='*'
    else
      if [ "`cat $RULE/NotOutput 2>/dev/null`" == checked ] ; then
        NOTOUTPUT='! '
      else
        NOTOUTPUT=''
      fi
    fi
    TARGET="`cat $RULE/Target 2>/dev/null`"
    if [ "`cat $RULE/LogEnabled 2>/dev/null`" == checked ] ; then
        LOGENABLED='yes'
    else
        LOGENABLED='no'
    fi
    ENABLED="`cat $RULE/Enabled 2>/dev/null`"
    if [ "`cat $RULE/NotSaved 2>/dev/null`" == yes ] ; then
      BG="bgcolor=#e0e0ff"
    else
      BG=""
    fi
    echo "<tr $BG>"
    echo "<td align=center><input type=Radio name=Rule value=$RULE></td>"
    echo "<td align=center>$NUM</td>"
    echo "<td align=center>$NOTINPUT$INPUT</td>"
    echo "<td align=center>$NOTOUTPUT$OUTPUT</td>"
    echo "<td>$IPT</td>"
    if [ "$CHAIN" == QoS -o "$CHAIN" == NetBalancer ] ; then
      if [ "$CHAIN" == NetBalancer ] ; then
        if [ "$TARGET" != Auto ] ; then
          nbIP="`cat $REGISTER/system/net/nb/Gateways/$TARGET/IP 2>/dev/null`" 
          nbINTERFACE="`cat $REGISTER/system/net/nb/Gateways/$TARGET/Interface 2>/dev/null`"
          TARGET="`cat $REGISTER/system/net/nb/Gateways/$TARGET/Description 2>/dev/null`"
          if [ -n "$nbIP" ] ; then
            TARGET="$TARGET ($nbIP)"
          else
            TARGET="$TARGET ($nbINTERFACE)"
          fi
        fi
      fi
      echo "<td nowrap align=center>$TARGET</td>"
    fi
    echo "<td align=center>$LOGENABLED</td>"
    if [ "$ENABLED" == yes ] ; then
      CHECKED=checked
    else
      CHECKED=""
    fi
    echo "<td align=center><input type=Checkbox name=Active$NUM value='$RULE' $CHECKED onclick='ActivateRule(this)'></td>"
    echo "</tr>"
  done
fi
echo "<input type=hidden name=maxSequence value=$((NUM+1))>"
