#!/bin/sh
. /etc/kerbynet.conf
PROTOCOLS="/etc/protocols"
grep -v ^# /etc/protocols  |sed -r 's/[^ ]+[ ]+([^ ]+)[ ]+[^ ]+[ ]+#[ ]+(.*)[\[].*/\1:\2/' | awk -F: '{printf "ProtoDes[%s]=\"%s\";\n",$1,$2}'

