#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
BOND="$1"
INTERFACE="$2"
[ -z "$BOND" -o -z "$INTERFACE" ] && exit 1
BONDDIR="$REGISTER/system/net/interfaces/$CONFIG/$BOND"
cd "$BONDDIR" || exit 5
BONDLIST="`cat BondList 2>/dev/null`"
N=0
FOUND=no
WT=1
for I in $BONDLIST ; do
  N=$((N+1))
  if [ "$I" = "$INTERFACE" ] ; then
     FOUND=yes
     break
  fi
done
if [ "$FOUND" = yes ] ; then
  WEIGHTS="`cat Weights 2>/dev/null`"  
  for W in $WEIGHTS ; do
    N=$((N-1))
    if [ $N -eq 0 ] ; then
       WT=$W
    fi
  done 
fi
echo $WT
