#!/bin/bash
. /etc/kerbynet.conf
function pingDOWN {
  GW=$1
  echo PROBEDOWN
  TC=`cat $GW/TC 2>/dev/null`
  [ -z "$TC" ] && TC=1
  TO=$((Timeout*TC))
  WX=`cat $GW/IP 2>/dev/null`
  if [ -n "$WX" ] ; then
    SRC="`ip route get $WX | grep ^$WX |sed -r 's/.* dev (.*) src (.*)/\1/'`"
    if [ -n "$SRC" ] ; then
       SRC="-I $SRC"
    fi
    for R in `seq 1 $ProbesDOWN` ; do
      if arping $SRC -c 1 -w $TO $WX   ; then
        return 0
      fi
      sleep $TO
    done
  else
    WX=`cat $GW/Interface 2>/dev/null`
    for R in `seq 1 $ProbesDOWN` ; do
      if ifconfig $WX 2>/dev/null |grep -w -q RUNNING   ; then
        return 0
      fi
      sleep $TO
    done
  fi
  return 1
}
function pingUP {
  GW=$1
  echo PROBEUP
  SRC=""
  WX=`cat $GW/IP 2>/dev/null`
  if [ -n "$WX" ] ; then
    SRC="`ip route get $WX | grep ^$WX |sed -r 's/.* dev (.*) src (.*)/\1/'`"
    if [ -n "$SRC" ] ; then
       SRC="-I $SRC"
    fi
    R=0
    ERROR=""
    while [ $R -lt $ProbesUP -a -z "$ERROR" ] ; do
      if ! arping $SRC -c 1 $WX  ; then
        ERROR=yes
      else
        R=$((R+1))
      fi
    done
  else
    WX=`cat $GW/Interface 2>/dev/null`
    R=0
    ERROR=""
    while [ $R -lt $ProbesUP -a -z "$ERROR" ] ; do
      if ! ifconfig $WX 2>/dev/null |grep -w -q RUNNING  ; then
        ERROR=yes
      else
        R=$((R+1))
        sleep 1
      fi
    done
  fi
  if [ -z "$ERROR" ] ; then
    return 0
  fi
  return 1
}
function SetTime {
  NOW=`date +%s`
  TIME=`cat $STATUSDIR/$G/Time 2>/dev/null`
  echo $NOW > $STATUSDIR/$G/Time
  if [ -n "$TIME" ] ; then
     TIME=$((NOW-TIME))
  else
     TIME=0
  fi
  [ -r $STATUSDIR/Outage ] || echo 0 > $STATUSDIR/Outage
  [ -r $STATUSDIR/UpTime ] || echo 0 > $STATUSDIR/UpTime
}
function SetFailure {
  SetTime
  UPTIME=`cat $STATUSDIR/$G/UpTime 2>/dev/null`
  [ -z "$UPTIME" ] && UPTIME=0
  UPTIME=$((UPTIME+TIME))
  echo $UPTIME > $STATUSDIR/$G/UpTime
  FAILURE=`cat $STATUSDIR/$G/Failure 2>/dev/null`
  [ -z "$FAILURE" ] && FAILURE=0
  FAILURE=$((FAILURE+1))
  echo $FAILURE > $STATUSDIR/$G/Failure
  W=`cat $G/IP 2>/dev/null`
  if [ -z "$W" ] ; then
    W="Interface: `cat $G/Interface 2>/dev/null`"
  else
    W="Gateway: $W"
  fi
  DESCRIPTION="`cat $G/Description 2>/dev/null` ($W) [Last Uptime: `$SCRIPTS/tick2time $TIME`]"
  echo "DOWN: $DESCRIPTION"
  logger -t NetBalancer "[LAYER2] FAULT: $DESCRIPTION"
  $SCRIPTS/nb_setnexthop
  $SCRIPTS/alert GWFAULT $G DOWN &
}
PIDS=`ps -e |egrep -w 'failoverd|gw_l2checkd' |awk '{print $1}'`
for P in $PIDS ; do
  if [ "$P" != "$$" ] ; then
    kill $P 2>/dev/null 
  fi
done
while ps -e | grep -w -v $$ | egrep -q -w 'failoverd|gw_l2checkd' ; do
  sleep 0.5
done

[ "$NBSTARTUP" = yes ] && sleep 30


CONFIG=$REGISTER/system/net/nb
STATUSDIR=/tmp/nb/Gateways
if [ "`cat $CONFIG/Enabled 2>/dev/null`" != yes ] ; then
  exit
fi
if [ "`cat $CONFIG/FO/ICMPCheck 2>/dev/null`" = yes ] ; then
  logger -t NetBalancer "[LAYER2] Gateway monitor is disabled"
  exit
else
  logger -t NetBalancer "[LAYER2] Gateway monitor has started"
fi

ProbesDOWN="`cat $CONFIG/FO/ProbesDOWN 2>/dev/null`"
ProbesUP="`cat $CONFIG/FO/ProbesUP 2>/dev/null`"
Timeout="`cat $CONFIG/FO/Timeout 2>/dev/null`"
Pause="`cat $CONFIG/FO/Pause 2>/dev/null`"
PPPDRestart="`cat $CONFIG/FO/PPPDRestart 2>/dev/null`"
cd $CONFIG/Gateways
GWS=""
for G in `ls -d *` ; do
  if [ "`cat $G/Enabled 2>/dev/null`" = yes ] ; then
    GWS="$GWS $G"
  else
    rm -f $STATUSDIR/$G/{Fault,Time,Outage,UpTime}
  fi
done
while true ; do
  for G in $GWS ; do
      echo "++++++++ TESTING `cat $G/Description 2>/dev/null`"
      if [ -r $STATUSDIR/$G/Fault ] ; then
         if pingUP $G ; then
           rm -f $STATUSDIR/$G/Fault
           W=`cat $G/IP 2>/dev/null`
           if [ -z "$W" ] ; then
             W="Interface: `cat $G/Interface 2>/dev/null`"
           else
             W="Gateway: $W"
           fi
           SetTime
           OUTAGE=`cat $STATUSDIR/$G/Outage 2>/dev/null`
           [ -z "$OUTAGE" ] && OUTAGE=0
           OUTAGE=$((OUTAGE+TIME))
           echo $OUTAGE > $STATUSDIR/$G/Outage
           DESCRIPTION="`cat $G/Description 2>/dev/null` ($W) [Last Downtime: `$SCRIPTS/tick2time $TIME`]"
           echo "UP: $DESCRIPTION"
           logger -t NetBalancer "[LAYER2] RECOVERED: $DESCRIPTION"
           $SCRIPTS/nb_setnexthop
           $SCRIPTS/alert GWFAULT $G UP &
           $SCRIPTS/alert CONNECTIVITY UP &
         fi
      else
         if ! pingDOWN $G ; then
           touch $STATUSDIR/$G/Fault
           SetFailure 
         else
           [ -r "$STATUSDIR/$G/Time" ] || SetTime 
         fi
      fi
  done
  sleep $Pause
done
