#!/bin/sh
. /etc/kerbynet.conf
function TERML2TP () {
    killall -w -TERM l2tpd 2>/dev/null >/dev/null
}
function TERMRACOON () {
    killall -w -TERM racoon 2>/dev/null >/dev/null
    setkey -F
    setkey -P -F
}
logger -t VPN "Stopping: `$SCRIPTS/vpn_count` connections L2TP/IPsec dropped"
TERML2TP || ERROR=true
TERMRACOON || ERROR=true
MAXIP=`cat $REGISTER/system/l2tp/MaxIP 2>/dev/null`
MINIP=`cat $REGISTER/system/l2tp/MinIP 2>/dev/null`
if ! [ -r "$REGISTER/system/pptp/Enabled" ] ; then
  iptables -t nat -D SNATVS -m iprange --src-range $MINIP-$MAXIP -j MASQUERADE
fi
if [ "$ERROR" == "true" ] ; then
  exit 1
else
  exit 0
fi

