#!/bin/sh
. /etc/kerbynet.conf
PATH="$PATH:/usr/local/ssl/bin"
function TERML2TP () {
  I=0
  ps -e |grep -w -q  l2tpd || return 0
  while [ $I -lt 30 ] ; do
    if ps -e |grep -w -q  l2tpd ; then
      killall -TERM l2tpd 2>/dev/null >/dev/null
    else 
       return 0
    fi
    I=$((I+1))
  done
  return 1
}
function TERMRACOON () {
  I=0
  ps -e |grep -w -q  racoon || return 0
  while [ $I -lt 30 ] ; do
    if ps -e |grep -w -q  racoon ; then
      killall -TERM racoon 2>/dev/null >/dev/null
    else 
       setkey -F
       setkey -P -F
       return 0
    fi
    I=$((I+1))
  done
  return 1
}
logger -t VPN "Starting: `$SCRIPTS/vpn_count` connections L2TP/IPsec dropped"
TERML2TP
TERMRACOON
MAXIP=`cat $REGISTER/system/l2tp/MaxIP 2>/dev/null`
MINIP=`cat $REGISTER/system/l2tp/MinIP 2>/dev/null`
iptables -t nat -D SNATVS -m iprange --src-range $MINIP-$MAXIP -j MASQUERADE 2>/dev/null
if [ -r "$REGISTER/system/pptp/Enabled" -o -r "$REGISTER/system/ipsec/Enabled" ] ; then
  if [ "`cat $REGISTER/system/l2tp/Routing`" == NAT ] ; then
    iptables -t nat -A SNATVS -m iprange --src-range $MINIP-$MAXIP -j MASQUERADE
  fi
fi

if [ -r "$REGISTER/system/ipsec/Enabled" ] ; then
  $SCRIPTS/rendertemplate racoon.conf
  $SCRIPTS/rendertemplate options.l2tpd
  if [ "`cat $REGISTER/system/ipsec/CheckCRL`" == yes ] ; then
    ln -sf /etc/ssl/certs/crl.pem "$REGISTER/system/ipsec/TLS/"
  else
    rm -f "$REGISTER/system/ipsec/TLS/crl.pem"    
  fi
  c_rehash $REGISTER/system/ipsec/TLS/ >/dev/null 2>/dev/null
  racoon -f /etc/racoon.conf
  if [ "`cat $REGISTER/system/l2tp/Routing`" == ProxyARP ] ; then
    echo proxyarp >> /etc/ppp/options.l2tpd 
  fi
  l2tpd
fi
