#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/L7"
L7="/tmp/L7"
if ! [ -d "$L7/Groups" ] ; then
  exit
fi
cd "$L7/Groups"
GRPS=`ls`
for G in $GRPS ; do
  echo echo "<option value='$G'>`echo $G |sed 's/_/ /g'`</option>"
done


