#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/L7"
mkdir  "$CONFIG" 2>/dev/null
rm -rf "$CONFIG/l7-protocols"
if [ -r "$CONFIG/l7-protocols.tgz" ] ; then
  TGZ="$CONFIG/l7-protocols.tgz"
else
  TGZ="/usr/local/share/l7-protocols.tar.gz"
fi
rm -rf "$CONFIG/protocols-tmp"
mkdir "$CONFIG/protocols-tmp"
cd "$CONFIG/protocols-tmp"
if ! tar xfz "$TGZ" 2>/dev/null >/dev/null ; then
  cd ..
  rm -rf "$CONFIG/protocols-tmp"
  mkdir "$CONFIG/protocols-tmp"
  cd "$CONFIG/protocols-tmp"
  tar xfz /usr/local/share/l7-protocols.tar.gz 2>/dev/null >/dev/null
fi
ls -d * > "$CONFIG/Version"
mv $CONFIG/protocols-tmp/* "$CONFIG/l7-protocols"
rm -rf "$CONFIG/protocols-tmp"
######
TMP="/tmp/L7"
rm -rf "$TMP/Groups"
mkdir -p "$TMP/Groups/all"
rm -rf "$TMP/Data"
mkdir -p "$TMP/Data"
cd "$REGISTER/system/net/L7/l7-protocols"
for PAT in */*.pat ; do
  NAME=`basename $PAT .pat`
  DESC=`head -1 $PAT`
  DESC=${DESC:2}
  touch "$TMP/Groups/all/$NAME"
  mkdir "$TMP/Data/$NAME"
  echo "$DESC" > "$TMP/Data/$NAME/Description"
  GRPS=`grep -i "Protocol Groups" $PAT| cut -d\  -f 4-`
  for G in $GRPS ; do
    mkdir "$TMP/Groups/$G" 2>/dev/null
    touch "$TMP/Groups/$G/$NAME"
  done
done



