#!/bin/bash
. /etc/kerbynet.conf
function IPLIST {
  if [ "`cat STATUS 2>/dev/null`" = up ] ; then
     if cd IP 2>/dev/null ; then
       IPS="`ls -d ?? 2>/dev/null`"       
       for A in $IPS ; do
          if [ "`cat $A/STATUS 2>/dev/null`" = up ] ; then
              IP="`cat $A/IP 2>/dev/null`"
	      NETMASK="`cat $A/Netmask 2>/dev/null`"
	      echo $IP/$NETMASK
	  fi
       done
     fi
  fi
}
CONF=$REGISTER/system/net/interfaces
cd $CONF
INTERFACES="`ls -d * 2>/dev/null |grep -v ppp`"
for I in $INTERFACES ; do
  cd $CONF/$I
  IPLIST
  cd $CONF/$I
  if cd VLAN 2>/dev/null ; then
     VLANS="`ls -d * 2>/dev/null`"
     for V in $VLANS ; do
       cd $CONF/$I/VLAN/$V
       IPLIST
     done  
  fi
done



