#!/bin/sh
. /etc/kerbynet.conf
INFO="/storage/INFO"
DISKS=`cd $INFO/DISK/ 2>/dev/null && ls 2>/dev/null`
DISK="$1"
PARTITION="$2"
DATABASE="$3"
DBDIR="$INFO/DISK/$DISK/PART/$PARTITION/DB/$DATABASE" 
Description=`cat $DBDIR/Description 2>/dev/null`
LastActivation=`cat $DBDIR/LastActivation 2>/dev/null`
if echo "$LastActivation" | grep -i -q active ; then
   LastActivation="Already Active"
fi
if echo "$LastActivation" | grep -i -q never ; then
    LastActivation="Never"
fi
hostname=`cat $DBDIR/hostname 2>/dev/null`
K5REALM=`cat $DBDIR/K5REALM 2>/dev/null`
LDAPBASE=`cat $DBDIR/LDAPBASE 2>/dev/null`
LastBackup=`cat $DBDIR/LastBackup 2>/dev/null`
cat << EOF

PROFILE INFO
  Description      : $Description
  Last Activation  : $LastActivation
  Hostname         : $hostname
  Kerberos 5 Realm : $K5REALM
  LDAP Base        : $LDAPBASE
  Last Backup      : $LastBackup
NETWORK CONFIGURATION
EOF
$SCRIPTS/storage_netDB $DISK $PARTITION $DATABASE TXT
echo
