#!/bin/sh
. /etc/kerbynet.conf
function COMPRESS {
  DAY="$1"
  [ -z "$DAY" ] && return
  FILES="$(ls $DAY/*/* |grep -v '.gz$')"
  if [ -n "$FILES" ] ; then
    for F in $FILES ; do
       SIZE=$(du "$F"|awk '{print $1}')
       [ -z "$SIZE" ] && SIZE=0
       if [ $SIZE -gt 20 ] ; then
         mv $F $F.tmp
         if [ -r "$F.gz" ] ; then
           if zcat "$F.gz" | cat - "$F.tmp" | gzip -c > "$F.tmp.gz" ; then
             mv "$F.tmp.gz" "$F.gz"
             rm -f "$F.tmp"
           else
             rm -f "$F.tmp.gz"
           fi
         else
           gzip "$F.tmp"
           mv "$F.tmp.gz" "$F.gz"
         fi
         logger -t syslogd "Reducer: $F compressed"
       fi
    done
  fi
}
function DELETE {
  DAY="$1"
  [ -z "$DAY" ] && return
  logger -t syslogd "Reducer: Deleting logs ($DAY)"
  rm -rf "$DAY"
}
function STOPPING () {
  USED=`df "$LOGDIR" |tail -1 |awk '{print $5}'`
  USED=${USED%\%}
  logger -t syslogd "Log reducer process completed (${USED}% used)"
  exit
}
OP="$1"
cd "$LOGDIR" || exit 1

USED=`df "$LOGDIR" |tail -1 |awk '{print $5}'`
USED=${USED%\%}
logger -t syslogd "Log reducer process ($OP mode) started (${USED}% used)"
COMPRESSTS="`cat $REGISTER/system/logs/Auto/CompressTS 2>/dev/null`"
DELETETS="`cat $REGISTER/system/logs/Auto/DeleteTS 2>/dev/null`"
YEARS="`ls -d ???? 2>/dev/null`"
[ -z "$YEARS" ] && exit 2
for Y in $YEARS ; do
  for M in Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ; do
    if [ -d "$Y/$M" ] ; then
       DAYS="`ls -d "$Y/$M"/?? 2>/dev/null`"
       for D in $DAYS ; do
         USED=`df "$LOGDIR" |tail -1 |awk '{print $5}'`
         USED=${USED%\%}
         if [ "$OP" == Delete ] ; then
           if [ "$USED" -gt "$DELETETS" ] ; then
             DELETE "$D"
	   else
             STOPPING
           fi
         else
           if [ "$USED" -gt "$COMPRESSTS" ] ; then
             COMPRESS "$D"
	   else
             STOPPING
           fi
         fi
       done
    fi
  done
done
STOPPING
