#!/bin/bash
PAGE="$1"
SECTION="$2"
if [ "$PAGE" = "" ] ; then
  exit 0
fi
FILE=`man -w $SECTION "$PAGE" 2>/dev/null`

if [ -n "$FILE" ] ; then
  groff -mandoc "$FILE" -T html
else
  echo "<br>&nbsp;&nbsp;&nbsp;<font color=#f03030><b>Manual page not found</b></font>"
fi
