#!/bin/bash
. /etc/kerbynet.conf
OP="$1"
GW="$2"
LOCALIP="$3"
DEV="$4"
CHANGED=no
N=`iptables -t mangle -L NB_CT_PRE -n --line-numbers |grep -w $LOCALIP|tac| awk '{print $1}'`
for L in $N ; do
  iptables -t mangle -D NB_CT_PRE $L
  CHANGED=yes
done
if [ "$OP" = add ] ; then
    iptables -t mangle -I NB_CT_PRE 1 -i $DEV -d $LOCALIP -j MARK --set-mark 1$GW
    CHANGED=yes
fi
if [ "$CHANGED" = yes ] ; then
  VPNS="`cd $REGISTER/system/net/interfaces/ ; ls -d VPN?? 2>/dev/null |grep -v VPN99`"
  for VPN in $VPNS ; do
    GWVPN="`cat $REGISTER/system/net/interfaces/$VPN/Gateway 2>/dev/null`"
    if [ "$GWVPN" = "$GW" ] ; then
      if [ -d $REGISTER/system/net/nb/Gateways/$GWVPN/ ] ; then
        ENABLEDGW="`cat $REGISTER/system/net/nb/Gateways/$GWVPN/Enabled 2>/dev/null`"
        if [ "$ENABLEDGW" = yes ] ; then
          if ps -ef | grep openvpn | grep -w -q $VPN ; then
            logger -t ${VPN}_L2L "Restarting by Net Balancer"
	    $SCRIPTS/alert VPNFAULT $VPN DOWN
          else
            logger -t ${VPN}_L2L "Starting by Net Balancer"
          fi
          $SCRIPTS/vpn_ctl $VPN    
        fi
      fi
    fi
  done 
fi
