#!/bin/sh
. /etc/kerbynet.conf
GW="$1"
DESCRIPTION="$2"
ENABLED="$3"
WEIGHT="$4"
IP="$5"
INTERFACE="$6"
TC="$7"
[ -z "$GW" ] && exit 1
CONFIG="$REGISTER/system/net/nb/Gateways"
cd $CONFIG/$GW || exit 1
echo "$DESCRIPTION" > Description
echo "$ENABLED" > Enabled
echo "$WEIGHT" > Weight
echo "$IP" > IP
echo "$INTERFACE" > Interface
echo "$TC" > TC
echo 0 > Failure
$SCRIPTS/nb_vpn
$SCRIPTS/nb_setautomarking $GW
ip ro sh | $SCRIPTS/routeupd $GW flush
$SCRIPTS/nb_startfo
