#!/bin/sh
. /etc/kerbynet.conf
GW="$1"
ENABLED="$2"
[ -z "$GW" ] && exit 1
CONFIG="$REGISTER/system/net/nb/Gateways"
cd $CONFIG/$GW || exit 1
if [ "$ENABLED" = yes -a -z "`cat IP 2>/dev/null`" -a -z "`cat Interface 2>/dev/null`" ] ; then
  exit 1
fi
echo "$ENABLED" > Enabled
$SCRIPTS/nb_vpn
$SCRIPTS/nb_setautomarking $GW
ip ro sh | $SCRIPTS/routeupd $GW flush
$SCRIPTS/nb_startfo
