#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/net/nb
STATUSDIR=/tmp/nb/Gateways
cd $CONFIG/Gateways || exit 1
GWS=`ls -d *`
NUMCONN=0
for G in $GWS ; do
  

  DESCRIPTION=`cat $G/Description 2>/dev/null`
  ENABLED=`cat $G/Enabled 2>/dev/null`
  if [ "$ENABLED" = yes ] ; then
    CHECKED=checked
  else
    CHECKED=""
  fi
  IP=`cat $G/IP 2>/dev/null`
  INTERFACE=`cat $G/Interface 2>/dev/null`
  WEIGHT=`cat $G/Weight 2>/dev/null`
  FAILURE=`cat $STATUSDIR/$G/Failure 2>/dev/null`
  [ -z "$FAILURE" ] && FAILURE=0
  STATUS=`$SCRIPTS/nb_statusgw $G`
  echo "<tr align=center style='color: #404040;'><td><input type=radio name=GW value=$G></td><td class=Smaller1>$DESCRIPTION</td><td>$IP</td><td>$INTERFACE</td><td>$WEIGHT</td><td>$STATUS</td><td>$FAILURE</td><td><input type=checkbox name=Up$G value="yes" $CHECKED onclick='UpGW(this)'></td></tr>"
  NUMCONN=$((NUMCONN+1))
done
echo "<script>parent.document.getElementById('NumConn').innerHTML=$NUMCONN;</script>"
