#!/bin/bash
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/nb"
if ! ip ro sh |grep -q -w default ; then
   exit
fi
IP[1]="`cat $CONFIG/FO/IP1 2>/dev/null`"
IP[2]="`cat $CONFIG/FO/IP2 2>/dev/null`"
IP[3]="`cat $CONFIG/FO/IP3 2>/dev/null`"
IPS=""
for I in 1 2 3 ; do
  X="${IP[$I]}"
  if [ -n "$X" ] ; then
    if ! ip ro get $X 2>/dev/null| egrep -q  'ppp|via' ; then
      IPS="$IPS IP($I)"
    fi
  fi
done
if [ -n "$IPS" ] ; then
  echo "<font color='#ff4500' class=Smaller1><b>WARNING</b>: $IPS should belong to an external network</font>"
fi


