#!/bin/sh
. /etc/kerbynet.conf
GW="$1"
[ -z "$GW" ] && exit 1
CONFIG="$REGISTER/system/net/nb/Gateways"
echo no > $CONFIG/$GW/Enabled
$SCRIPTS/nb_setautomarking $GW
rm -rf "$CONFIG/$GW" "/tmp/nb/Gateways/$GW"
ip ro flush ta 1$GW
$SCRIPTS/nb_vpn
$SCRIPTS/nb_setnexthop
$SCRIPTS/nb_startfo
