#!/bin/sh
. /etc/kerbynet.conf
ENABLED="$1"
MODE="$2"
ICMPCheck="$3"
ProbesDOWN="$4"
ProbesUP="$5"
Timeout="$6"
Pause="$7"
PPPDRestart="$8"
IP1="$9"
EnabledIP1="${10}"
IP2="${11}"
EnabledIP2="${12}"
IP3="${13}"
EnabledIP3="${14}"
CONFIG="$REGISTER/system/net/nb"
echo "$ENABLED" > $CONFIG/Enabled
echo "$MODE" > $CONFIG/Mode
echo "$ICMPCheck" > $CONFIG/FO/ICMPCheck
echo "$ProbesDOWN" > $CONFIG/FO/ProbesDOWN
echo "$ProbesUP" > $CONFIG/FO/ProbesUP
echo "$Timeout" > $CONFIG/FO/Timeout
echo "$Pause" > $CONFIG/FO/Pause
echo "$PPPDRestart" > $CONFIG/FO/PPPDRestart
echo "$IP1" > $CONFIG/FO/IP1
echo "$EnabledIP1" > $CONFIG/FO/EnabledIP1
echo "$IP2" > $CONFIG/FO/IP2
echo "$EnabledIP2" > $CONFIG/FO/EnabledIP2
echo "$IP3" > $CONFIG/FO/IP3
echo "$EnabledIP3" > $CONFIG/FO/EnabledIP3
$SCRIPTS/routeupd_start
$SCRIPTS/nb_fw
$SCRIPTS/nb_setnexthop
$SCRIPTS/nb_startfo
