#!/bin/sh
. /etc/kerbynet.conf
if ps -e |grep -q -w failoverd ; then
  echo "<font color=#10d010>Active</font>"
else
  if [ "`cat $REGISTER/system/net/nb/FO/ICMPCheck 2>/dev/null`" = yes ] ; then
    echo "<font color=#FF2020>Not Running</font>"
  else
    echo "<font color=#FF2020>Disabled</font>"
  fi
fi
