#!/bin/sh
. /etc/kerbynet.conf
GW="$1"
[ -z "$GW" ] && exit 1
if [ "`cat  $REGISTER/system/net/nb/Enabled 2>/dev/null`" != yes ] ; then
  echo "-"
  exit
fi
CONFIG="$REGISTER/system/net/nb/Gateways/$GW"
MODE=`cat  $REGISTER/system/net/nb/Mode 2>/dev/null`
if [ "`cat $CONFIG/Enabled 2>/dev/null`" != yes ] ; then
  echo Disabled
  exit
fi
STATUSDIR=/tmp/nb/Gateways/$GW
if [ -r $STATUSDIR/Fault ] ; then
  if [ ! -r /tmp/nb_autoppp ] ; then
    INTERFACE=`cat $CONFIG/Interface 2>/dev/null`
    if [ "${INTERFACE:0:3}" = ppp ] ; then
      if [ "`cat $REGISTER/system/net/interfaces/$INTERFACE/Auto 2>/dev/null`" = NB ] ; then
        echo "<font color=#FF6600>Standby</font>"
      else
        echo "<font color=#FF2020>Fault</font>"
      fi
    else
      echo "<font color=#FF2020>Fault</font>"
    fi
  else
    echo "<font color=#FF2020>Fault</font>"
  fi 
  echo "<script>BODY.FaultGW++;BODY.TotalGW++;</script>"
  exit
fi
if ! ip ro sh ta 1$GW | grep -q ^default  ; then
  echo "<font color=#FF2020>No link</font>"
  echo "<script>BODY.NolinkGW++;BODY.TotalGW++;</script>"
  exit
fi
ACTIVE=""
if [ "$MODE" != FO ] ; then
  ACTIVE=yes
else
  IP=`cat $CONFIG/IP 2>/dev/null`
  INTERFACE=`cat $CONFIG/Interface 2>/dev/null`
  if [ -n "$IP" ] ; then
    if ip ro sh | grep -v metric | egrep -q -w "^default.+via $IP" ; then
      ACTIVE=yes
    fi
  else
    if ip ro sh | grep -v metric | grep -v via | egrep -w -q "^default.+dev $INTERFACE" ; then
      ACTIVE=yes
    fi
  fi
fi
if [ "$ACTIVE" = yes ] ; then
  echo "<font color=#10d010>Active</font>"
  echo "<script>BODY.ActiveGW++;BODY.TotalGW++;</script>"
else
  echo "<font color=#10d010>Spare</font>"
  echo "<script>BODY.SpareGW++;BODY.TotalGW++;</script>"
fi
