#!/bin/sh
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/net/nb
STATUSDIR=/tmp/nb/Gateways
cd $CONFIG/Gateways || exit 1
iptables -t mangle -L NB_CT_POST -n -v 2>/dev/null >/tmp/nb_ct_post
iptables -t mangle -L NB_STAT -n -v 2>/dev/null >/tmp/nb_stat
GWS=`ls -d *`
echo "<table width=100%>"
echo "<tr bgcolor=#9090f0 style='color: #FFFFFF'><th align=left width=40% nowrap>&nbsp;Gateway</th><th>&nbsp;Status&nbsp;</th><th>&nbsp;Failure&nbsp;</th><th>&nbsp;&nbsp;Outage&nbsp;&nbsp;</th><th>&nbsp;&nbsp;Uptime&nbsp;&nbsp;</th><th nowrap>&nbsp;Up %&nbsp;</th><th>&nbsp;Weight&nbsp;</th><th>&nbsp;Traffic&nbsp;</th><th>Connection</th></tr>"
for G in $GWS ; do

  DESCRIPTION=`cat $G/Description 2>/dev/null`
  IP=`cat $G/IP 2>/dev/null`
  INTERFACE=`cat $G/Interface 2>/dev/null`
  if [ -n "$IP" ] ; then
    DESCRIPTION="$DESCRIPTION ($IP)"
  else
    DESCRIPTION="$DESCRIPTION ($INTERFACE)"
  fi
  WEIGHT=`cat $G/Weight 2>/dev/null`
  FAILURE=`cat $STATUSDIR/$G/Failure 2>/dev/null`
  [ -z "$FAILURE" ] && FAILURE=0
  STATUS=`$SCRIPTS/nb_statusgw $G`
  OUTAGE=`cat $STATUSDIR/$G/Outage 2>/dev/null`
  [ -z "$OUTAGE" ] && OUTAGE=0
  UP=`cat $STATUSDIR/$G/UpTime 2>/dev/null`
  [ -z "$UP" ] && UP=0
  NOW=`date +%s`
  TIME=`cat $STATUSDIR/$G/Time 2>/dev/null`
  if [ -n "$TIME" ] ; then
     DELTA=$((NOW-TIME))
  else
     DELTA=0
  fi
  if echo $STATUS | egrep -q "Active|Spare" ; then
    UP=$((UP+DELTA))
  fi
  if echo $STATUS | grep -q Fault ; then
    OUTAGE=$((OUTAGE+DELTA))
  fi
  TOTAL=$((UP+OUTAGE))
  if [ "$TOTAL" -gt 0 ] ; then
    PERC=`echo $UP $TOTAL | awk '{printf("%6.2f",$1/$2*100)}'`
  else
    PERC="-"
  fi
  HEX=`echo 1$G |awk '{printf("0x%2x",$0)}'`
  CONN=`grep -w "set $HEX" < /tmp/nb_ct_post |awk '{print $1}'`
  [ -z "$CONN" ] && CONN="-"
  TRAF=`grep -w "match $HEX" < /tmp/nb_stat |awk '{print $2}'`
  [ -z "$TRAF" ] && TRAF="-"
  echo "<tr><td align=left nowrap>&nbsp;$DESCRIPTION</td><td align=center>$STATUS</td><td align=center>$FAILURE</td><td align=center nowrap>`$SCRIPTS/tick2time $OUTAGE`</td><td align=center nowrap>`$SCRIPTS/tick2time $UP`</td><td align=center>$PERC</td><td align=center>$WEIGHT</td><td align=center>$TRAF</td><td align=center>$CONN</td></tr>"
  echo "<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>"

done
echo "</table>"
