#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls -d ETH?? VPN?? WLAN?? BRIDGE?? BOND?? 2>/dev/null|grep -v VPN99`
for I in $INTERFACES ; do
   cd $CONFIG
   if ! [ -d $I/Bridge/ -o -d $I/Bond/ ] ; then
      echo "<option value='$I'>$I</option>" 
      if [ -d "$I/VLAN" ] ; then
        cd $I/VLAN
        VLANS=`ls`
        for V in $VLANS ; do
          if ! [ -d $V/Bridge/ -o -d $V/Bond/ ] ; then
           echo "<option value='$I.$V'>$I vlan $V</option>"
          fi
        done
      fi
   fi
done


