#!/bin/sh
. /etc/kerbynet.conf
function TERM () {
  I=0
  ps -e |grep -w -q ntpd || return 0
  while [ $I -lt 30 ] ; do
    if ps -e |grep -w -q ntpd ; then
      killall -TERM  ntpd 2>/dev/null >/dev/null
    else 
       return 0
    fi
    I=$((I+1))
  done
  return 1
}
TERM
if grep -q "130.60.75.60" $REGISTER/system/time/NTP/ServerList ; then
  mv $REGISTER/system/time/NTP/ServerList /tmp/ServerList
  grep -v "130.60.75.60" /tmp/ServerList | grep -v "209.104.4.227" |grep -v "200.144.121.33" |grep -v "193.40.133.134" > $REGISTER/system/time/NTP/ServerList
  echo "0.pool.ntp.org" >> $REGISTER/system/time/NTP/ServerList
  echo "1.pool.ntp.org" >> $REGISTER/system/time/NTP/ServerList
  echo "2.pool.ntp.org" >> $REGISTER/system/time/NTP/ServerList
  echo "3.pool.ntp.org" >> $REGISTER/system/time/NTP/ServerList



fi
SERVER="`cat $REGISTER/system/time/NTP/Server 2>/dev/null`"
CLIENT="`cat $REGISTER/system/time/NTP/Client 2>/dev/null`"
if [ "$SERVER" == yes -o "$CLIENT" == yes ] ; then
  FILE="/etc/ntp.conf"
  echo "driftfile /tmp/ntp.drift" > $FILE
  if [ "$SERVER" == yes ] ; then
    echo "restrict default nomodify notrap noquery" >> $FILE
  else
    echo "restrict default ignore" >> $FILE
  fi
  if [ "$CLIENT" == yes ] ; then  
    for S in `cat $REGISTER/system/time/NTP/ServerList 2>/dev/null` ; do
      echo "server $S" >> $FILE
      echo "restrict $S noquery nomodify notrap" >> $FILE
    done
    if ! [ -z "$S" ] ; then
      if ntpdate -u $S 2>/dev/null >/dev/null ; then
         $SCRIPTS/hwclock -w
      fi
    fi 
  fi
  cat <<EOF >> $FILE
server 127.127.1.0
fudge 127.127.1.0 stratum 10
restrict 127.0.0.1
EOF
  ntpd -g
fi 
