#!/bin/sh
. /etc/kerbynet.conf
CLIENT="$1"
SERVER="$2"
SERVERLIST="$3"
mkdir -p $REGISTER/system/time/NTP
echo "$CLIENT" >$REGISTER/system/time/NTP/Client
echo "$SERVER" >$REGISTER/system/time/NTP/Server
echo "$SERVERLIST" | tr " " "\n" >$REGISTER/system/time/NTP/ServerList
$SCRIPTS/ntp_start

