#!/bin/sh
. /etc/kerbynet.conf
if ps -e |grep -q -w vpn ; then
  TMP=/tmp/OVClients.$$
  echo "status 2" |nc  127.0.0.1 34099  > $TMP
  NCLIENTS=`grep "^CLIENT_LIST," $TMP |wc -l`
  echo "<p align=left>&nbsp;&nbsp;<font color=#2020A0><b>>></b>&nbsp;&nbsp;&nbsp;Connected Clients:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>$NCLIENTS</b></font>&nbsp;&nbsp;<br>"
  echo "<table width=100%  align=center>"
  grep "^HEADER,CLIENT_LIST," $TMP | awk -F, '{printf("<tr align=center bgcolor=#b0f0b0><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",$3,$4,$5,$6,$7,$8);}'
  grep "^CLIENT_LIST," $TMP | awk -F, '{printf("<tr align=center style=\"color: #404040\"><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",$2,$3,$4,$5,$6,$7);}'

  echo "</table>"
  rm -f $TMP 
else
  echo "&nbsp;Connected Clients: <b>0</b><br><br>"
  echo "<font color=#FF0000>&nbsp;>&nbsp;>&nbsp;OpenVPN MULTI Server has not started</font>"

fi
