#!/bin/sh
. /etc/kerbynet.conf
#printenv > /tmp/radius.env
function PRINTIP() {
  IP="$((IP32 % 256))"
  IP32="$((IP32 / 256))"
  IP="$((IP32 % 256)).$IP"
  IP32="$((IP32 / 256))"
  IP="$((IP32 % 256)).$IP"
  IP32="$((IP32 / 256))"
  IP="$((IP32 % 256)).$IP"
  IP32="$((IP32 / 256))"
  echo "Framed-IP-Address = $IP"
}
if [ "$SERVICE_TYPE" != "Framed-User" -o "$NAS_IP_ADDRESS" != "127.0.0.1" ] ; then
  exit
fi 

MINIP="`cat $REGISTER/system/l2tp/MinIP 2>/dev/null`"
MAXIP="`cat $REGISTER/system/l2tp/MaxIP 2>/dev/null`"
MINIP="`echo $MINIP |awk -F. '{printf "%d",$1*16777216+$2*65536+$3*256+$4}'`"
MAXIP="`echo $MAXIP |awk -F. '{printf "%d",$1*16777216+$2*65536+$3*256+$4}'`"

/sbin/ifconfig |grep "inet addr"|sed -r 's/.*addr:([0123456789]{1,3}.[0123456789]{1,3}.[0123456789]{1,3}.[0123456789]{1,3}) .*/\1/' |awk -F. '{printf "%d\n",$1*16777216+$2*65536+$3*256+$4}' >/tmp/iplist32
/sbin/ifconfig |grep P-t-P: |sed -r 's/.*P-t-P:([0123456789]{1,3}.[0123456789]{1,3}.[0123456789]{1,3}.[0123456789]{1,3}) .*/\1/' |awk -F. '{printf "%d\n",$1*16777216+$2*65536+$3*256+$4}' >>/tmp/iplist32

IP32="$MINIP"
while [ "$IP32" -le "$MAXIP" ] ; do
  if ! grep -q -w $IP32 /tmp/iplist32 ; then
    PRINTIP
    echo "$IP" > "/tmp/VPN_IP_$USER_NAME"
    exit
  fi
  IP32=$((IP32+1))
done
echo "not assigned" > "/tmp/VPN_IP_$USER_NAME"
echo "Framed-IP-Address = noip"
