#!/bin/sh
. /etc/kerbynet.conf
function TERM () {
    killall -w -TERM pptpd 2>/dev/null >/dev/null
}
logger -t VPN "Stopping: `$SCRIPTS/vpn_count` connections PPTP dropped"
TERM || ERROR=true
MAXIP=`cat $REGISTER/system/l2tp/MaxIP 2>/dev/null`
MINIP=`cat $REGISTER/system/l2tp/MinIP 2>/dev/null`
if ! [ -r "$REGISTER/system/ipsec/Enabled" ] ; then
  iptables -t nat -D SNATVS -m iprange --src-range $MINIP-$MAXIP -j MASQUERADE
fi
if [ "$ERROR" == "true" ] ; then
  exit 1
else
  exit 0
fi

