#!/bin/bash
. /etc/kerbynet.conf
function ShowPart {
  N=0
  echo -e "Please wait: scanning storage devices ...\n"
  $SCRIPTS/storage
  DISKS=$(cd /storage/INFO/DISK/ && ls)
  for D in $DISKS ; do
    DISK=$(echo $D | tr _ /)
    MODEL="$(cat /storage/INFO/DISK/$D/Model 2>/dev/null)"
    SIZE="$(cat /storage/INFO/DISK/$D/Size 2>/dev/null)"
    GIGA=$(echo $SIZE | awk '{printf ("%.2f",$1/1000000)}')
    echo "Disk: $MODEL  Size: $GIGA GB"
    PARTITIONS=$(cd /storage/INFO/DISK/$D/PART/ 2>/dev/null && ls)
    for P in $PARTITIONS ; do
      if [ -d "/storage/INFO/DISK/$D/PART/$P" ] ; then
        TYPE=$(cat /storage/INFO/DISK/$D/PART/$P/Type 2>/dev/null)
        if [ "$TYPE" != Extended ] ; then
          PARTITION=$(echo $P | tr _ /)
          LABEL=$(cat /storage/INFO/DISK/$D/PART/$P/Label 2>/dev/null)
          TYPE=$(cat /storage/INFO/DISK/$D/PART/$P/Type 2>/dev/null)
          BLOCKS=$(cat /storage/INFO/DISK/$D/PART/$P/Blocks 2>/dev/null)
          GIGA=$(echo $BLOCKS | awk '{printf ("%.2f",$1/1000000)}')
          PERCENT=$(cat /storage/INFO/DISK/$D/PART/$P/Percent 2>/dev/null)
          N=$((N+1))
          echo " <$N> $LABEL ($PARTITION:$TYPE) Size: $GIGA GB (${PERCENT} Used)"
          PART[$N]=$PARTITION
          TYPES[$N]="$TYPE"
          GIGAS[$N]="$GIGA"
          PERCS[$N]="${PERCENT%\%}"
        fi
      fi
    done
    echo
  done
}
function Create {
  INFO=/tmp/disk_info_$$
  ERROR=/tmp/disk_error_$$
  ShowPart
  if [ "$N" -eq 0 ] ; then 
     echo
     echo -e "ERROR: No partition found to contain profiles.\nYou should use the Web Interface in the section [Setup][Profiles]\nfor more advanced profile management."
     return 2
  fi
  K=1000
  until [ $K -ge 0 -a $K -le $N ] ; do
    echo -n "Select the partition where to create the new profile (1-$N) (0=Exit): "
    read  K
    [ $K -lt 1000 ] 2>/dev/null  || K=1000
  done
  [ $K -eq 0 ] && echo ABORTED && exit
  if echo "${TYPES[$K]}" |grep -i -q  fat ; then
    echo
    echo -e "ERROR: FAT filesystem type is not supported to contain profiles.\nYou should use the Web Interface in the section [Setup][Profiles]\nfor more advanced profile management."
    return 1 
  fi
  PARTITION=${PART[$K]}
  if ! df "$PARTITION"  |grep -q -w "$PARTITION" ; then
     mkdir -p /tmp/mpoint
     if ! mount "$PARTITION" /tmp/mpoint 2>/dev/null ; then
       echo
       echo -e "ERROR: This partition cannot contain profiles.\nYou should use the Web Interface in the section [Setup][Profiles]\nfor more advanced profile management."  
       rmdir /tmp/mpoint
       return 2
     fi 
     umount  "$PARTITION" && rmdir /tmp/mpoint
  fi
  if echo "${GIGAS[$K]}" "${PERCS[$K]}" |awk '{if ($1*(1-$2/100) >0.05) exit 1;}' ; then
    echo
    echo "ERROR: No free space available to create a new profile on $PARTITION"
    return
  fi
  $SCRIPTS/create-profile $PARTITION 
  if [ "$?" = 0 ] ; then
    echo " done"
  else
    echo " ERROR"
  fi


}
while true ; do
  echo
  echo "----------------------------------"
  echo "  P R O F I L E   M A N A G E R"
  echo "----------------------------------"
  echo
  echo "  <C> Create Profile"
  echo "  <A> Activate Profile"
  echo "  <D> Deactivate Profile"
  echo "  <Q> Quit"
  echo
  echo -n ">> "
  read -n1  X
  X=`echo $X | awk '{print toupper($0)}'`
  echo
  echo
  case "$X" in
    Q)
      exit
    ;;
    C)
      Create
    ;;
    A)
      if $SCRIPTS/localman_activatedb ; then
         echo "REBOOT in progress..." ; sleep 60
      fi
    ;;
    D)
      if $SCRIPTS/localman_deactivatedb ; then
         echo "REBOOT in progress..." ; sleep 60
      fi

    ;;
  esac

done

