#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
[ -z "$INTERFACE" ] && INTERFACE=ALL
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES="`ls`"
for I in ALL $INTERFACES ; do
  if [ "$INTERFACE" == "$I" ] ; then
     SELECTED=selected
  else
     SELECTED=""
  fi
  echo "<option value='$I' $SELECTED>$I</option>"
done
