#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
CLASS="$2"
[ -z "$INTERFACE" -o -z "$CLASS" ] && exit 1
CM="$REGISTER/system/net/QoS/Class/$CLASS"
if [ "`cat $CM/Enabled 2>/dev/null`" != yes ] ; then
  echo no
  exit
fi
if [ "$INTERFACE" != ALL ] ; then
  DIR="$REGISTER/system/net/interfaces/$INTERFACE/QoS/Class/$CLASS"
  if [ "`cat $DIR/Enabled 2>/dev/null`" != yes ] ; then
    echo no
  else 
    echo yes
  fi
else
  DIR="$REGISTER/system/net/interfaces"
  cd "$DIR"
  INTERFACES="`ls`"
  for I in $INTERFACES ; do
    DIR="$REGISTER/system/net/interfaces/$I/QoS/Class/$CLASS"
    if [ "`cat $DIR/Enabled 2>/dev/null`" == yes ] ; then
      echo yes
      exit
    fi
  done
  echo no
fi
