#!/bin/sh
. /etc/kerbynet.conf
INTERFACE="$1"
NAME="$2"
[ -z "$INTERFACE" ] && exit 1
CDIR="$REGISTER/system/net/interfaces/$INTERFACE/QoS/Class/"
if ! [ -d "$CDIR" ] ; then
  exit
fi
cd "$CDIR"
CLASS="`ls`"
TOT=0
for C in $CLASS ; do
  if [ "`$SCRIPTS/qos_ison $INTERFACE $C`" == yes -a "$C" != "$NAME" ] ; then
    G=`$SCRIPTS/qos_getbw $INTERFACE $C Guaranteed K`
    TOT=`echo "$TOT $G" | gawk '{print $1+$2}'`
  fi
done
echo $TOT
