#!/bin/sh
. /etc/kerbynet.conf
CLASSNAME="$1"
QDIR="$REGISTER/system/net/QoS/"
if ! [ -d "$QDIR/Class" ] ; then
  mkdir -p "$QDIR/Class"
fi
cd "$QDIR/Class"
CLASSES=`ls -d * 2>/dev/null`
if [ -n "$CLASSES" ] ; then
  for C in $CLASSES ; do
    NAME="$C"
    DESC="`cat $C/Description`"
    MAX="`cat $C/Max`"
    GUARANTEED="`cat $C/Guaranteed`"
    if [ -n "$MAX" ] ; then
      MAXUNIT="`cat $C/MaxUnit`"
    else
      MAXUNIT="&nbsp;"
    fi
    if [ -n "$GUARANTEED" ] ; then
      GUARANTEEDUNIT="`cat $C/GuaranteedUnit`"
    else
      GUARANTEEDUNIT="&nbsp;"
    fi
    PRIORITY="`cat $C/Priority`"
    PRIORITY="`$SCRIPTS/qos_printpriority $PRIORITY`"
    DSCP="`cat $C/DSCP 2>/dev/null`"
    ENABLED="`cat $C/Enabled`"
    if [ "$ENABLED" == yes ] ; then
       CHECKED=checked
    else
       CHECKED=""
    fi
    if [ "$C" == "$CLASSNAME" ] ; then
      CHK=checked
    else
      CHK=""
    fi
    echo "<tr bgcolor=#e8e8e8><td width=1%><input type=radio name='QoSClass' value='$C' $CHK onclick='ClassSelected()'></td><td>&nbsp;$NAME&nbsp;</td><td>&nbsp;$DESC</td><td align=center>$PRIORITY</td><td align=center>$DSCP</td><td align=center>$MAX$MAXUNIT</td><td align=center>$GUARANTEED$GUARANTEEDUNIT</td><td width=1%><input type=checkbox name=Enabled$C value=$C $CHECKED onclick='ChangeStatus(this)'></td></tr>"
  done
fi

