#!/bin/bash
. /etc/kerbynet.conf
INTERFACES="`cat /tmp/QoSNotSaved 2>/dev/null`"
if [ -n "$INTERFACES" ] ; then
  for I in $INTERFACES ; do
    $SCRIPTS/qos_setinterface $I
  done
fi
$SCRIPTS/mrtg_reload
rm -f /tmp/QoSNotSaved


