#!/bin/sh
. /etc/kerbynet.conf
REALM="$1"
SERVER="$2"
AUTHPORT="$3"
ACCTPORT="$4"
SECRET="$5"
NOSTRIP="$6"
LB="$7"
TYPE="$8"
ACCOUNTING="$9"

cd $REGISTER/system/radius/proxy/realms || exit 1
if [ "$TYPE" == Local ] ; then
  SERVER=LOCAL
  AUTHPORT="1812"
  ACCTPORT="1813"
  SECRET=""
  NOSTRIP=""
  LB=""
  ACCOUNTING="no"
fi
if [ "$TYPE" == Default ] ; then
  REALM=DEFAULT
fi
mkdir -p $REALM 2> /dev/null
cd $REALM || exit 2
echo $TYPE > Type
echo $LB > LB
NUM=`ls -d [0123456789][0123456789] 2>/dev/null | tail -1`
if [ "$NUM" == "" ] ; then
  NUM=00
else
  if [ "${NUM:0:1}" == 0 ] ; then
    NUM=${NUM:1:1}
  fi
  NUM=`echo $((NUM+1)) | awk '{printf "%02s",$0 }'`
fi
[ "$ACCOUNTING" != yes ] && ACCTPORT=""
mkdir $NUM
echo $SERVER > $NUM/Server
echo $NOSTRIP > $NUM/NoStrip
echo $AUTHPORT > $NUM/AuthPort
echo $ACCTPORT > $NUM/AcctPort
echo $ACCTPORT > $NUM/AcctPort
echo $SECRET > $NUM/Secret
echo $ACCOUNTING > $NUM/Acct
if ! $SCRIPTS/radius_start ; then
  $SCRIPTS/radius_proxydel "$REALM" "$NUM"
  $SCRIPTS/radius_start
  exit 6
fi

