#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
TAG="$2"
[ -z "$INTERFACENAME" -o -z "$TAG" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
INTERFACE=`echo $INTERFACENAME |cut -d. -f1`
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
VLANDIR="$IDIR/VLAN/$TAG"
if ! [ -d "$VLANDIR" ] ; then
   echo "VLAN $TAG doesn't exist." 1>&2
   exit 3
fi
if vconfig rem $INTERFACE.$TAG ; then
  rm -rf $VLANDIR
  if [ "${INTERFACENAME:0:6}" == BRIDGE ] ; then
    setallbridgedinterface $INTERFACENAME
  fi
  if [ "${INTERFACENAME:0:4}" == BOND ] ; then
    setallbondedinterface $INTERFACENAME
  fi

fi
