#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
OBJ="$2"
[ -z "$INTERFACENAME" -o -z "$OBJ" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
VLAN=`echo $INTERFACENAME | awk -F. '{print $2}'`
INTERFACE=`echo $INTERFACENAME |cut -d. -f1`
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
if ! [ -z "$VLAN" ] ; then 
  IDIR="$IDIR/VLAN/$VLAN"
  if ! [ -d "$IDIR" ] ; then
     echo "VLAN $VLAN doesn't exist." 1>&2
     exit 3
  fi
fi
ALIAS=`basename $OBJ`
IP=`cat $CONFIG/$OBJ/IP`
Netmask=`cat $CONFIG/$OBJ/Netmask`
#doBackup
rm -rf $CONFIG/$OBJ
ifconfig $INTERFACENAME:$ALIAS down
$SCRIPTS/ip_restart_daemon 2>/dev/null >/dev/null &
echo $IP/$Netmask
