#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
NAME="$1"
[ -z "$NAME" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
BRIDGEDIR="$CONFIG/$NAME"
BRIDGEDLIST=`cat $BRIDGEDIR/BridgeList`
for I in $BRIDGEDLIST ; do
   if echo $I | grep -q '\.' ; then
     TAG=`echo $I | awk -F. '{print $2}'`
     U=`echo $I | awk -F. '{print $1}'`
     rm -rf $CONFIG/$U/VLAN/$TAG/Bridge
   else
     rm -rf $CONFIG/$I/Bridge
   fi
   brctl delif $NAME $I 
   $SCRIPTS/setinterface $I
   $SCRIPTS/setvlans $I
   $SCRIPTS/router_natcheck $I
done
ifconfig $NAME down
brctl delbr $NAME
$SCRIPTS/routerconfig
rm -rf $BRIDGEDIR
