#!/bin/sh
. /etc/kerbynet.conf
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls`
for I in $INTERFACES ; do
   cd $CONFIG
   if ! [ -d $I/Bridge/ -o -d $I/Bond/ ] ; then
     if [ -r $I/RIP/Enabled ] ; then
      echo "<option value='$I'>$I</option>" 
     fi
   fi
   if [ -d "$I/VLAN" ] ; then
      cd $I/VLAN
      VLANS=`ls`
      for V in $VLANS ; do
        if [ -r $V/RIP/Enabled ] ; then
          echo "<option value='$I.$V'>$I vlan $V</option>"
        fi
      done
   fi
done


