#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls |sort -f`
for I in $INTERFACES ; do
   if ! [ -d $I/Bridge/ -o -d $I/Bond/ ] ; then 
     echo "<option value='$I'>$I</option>"
     if [ -d "$I/VLAN" ] ; then
       cd $I/VLAN
       VLANS=`ls`
       cd $CONFIG
       for V in $VLANS ; do
         echo "<option value='$I.$V'>$I vlan $V</option>"
       done
     fi
   fi
done


