#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
NATLIST=" $1 "
CONFIG="$REGISTER/system/net/interfaces"
cd $CONFIG
INTERFACES=`ls |sort -f`
for I in $INTERFACES ; do
   cd $CONFIG
   if ! [ -d $I/Bridge/ -o -d $I/Bond/ ] ; then 
     if  [ -d $I/NAT/Masquerade ] ; then
       if echo "$NATLIST" | grep -v -q " $I " ; then
          iptables -t nat -D POSTROUTING -o $I -j MASQUERADE
          rm -rf  "$I/NAT/Masquerade"
          REMOVED="$REMOVED $I"
       fi
     else 
       if  echo "$NATLIST" | grep -q " $I " ; then
          iptables -t nat -A POSTROUTING -o $I -j MASQUERADE
          mkdir -p "$I/NAT/Masquerade"
          ADDED="$ADDED $I"
       fi
     fi
     if [ -d "$I/VLAN" ] ; then
       cd $I/VLAN
       VLANS=`ls`
       for V in $VLANS ; do
          if  [ -d $V/NAT/Masquerade ] ; then
            if echo "$NATLIST" | grep -v -q " $I.$V " ; then
              iptables -t nat -D POSTROUTING -o $I.$V -j MASQUERADE
              rm -rf  "$V/NAT/Masquerade"
              REMOVED="$REMOVED ${I} vlan $V"
            fi
          else
            if  echo "$NATLIST" | grep -q " $I.$V " ; then
              iptables -t nat -A POSTROUTING -o $I.$V -j MASQUERADE
              mkdir -p "$V/NAT/Masquerade"
              ADDED="$ADDED ${I} vlan $V"
            fi
          fi
       done
     fi
   fi
done
if ! [ -z "$ADDED" ] ; then
  echo -n "enabled NAT on $ADDED"
fi
if ! [ -z "$REMOVED" ] ; then
  [ -z "$ADDED" ] || echo " and "
  echo -n "disabled NAT on $REMOVED"
fi
if [ -z "$ADDED" -a -z "$REMOVED" ] ; then
 echo -n "NAT interfaces unchanged"
fi


