#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
if echo $INTERFACE | grep -q '\.' ; then
  TAG=`echo $INTERFACE | awk -F. '{print $2}'`
  U=`echo $INTERFACE | awk -F. '{print $1}'`
  CONFIG="$REGISTER/system/net/interfaces/$U/VLAN/$TAG"
else
  CONFIG="$REGISTER/system/net/interfaces/$INTERFACE"
fi



cd $CONFIG || exit 2
NATTED="`iptables -t nat -L POSTROUTING -v |awk '{print $7}' |grep "^$INTERFACE"`"
if [ -d Bridge -o -d Bond ] ; then
  for I in $NATTED ; do
    iptables -t nat -D POSTROUTING -o $I -j MASQUERADE
    echo REMOVED $I
  done
else
  if  [ -d NAT/Masquerade ] ; then
    if ! echo "$NATTED" | grep -q -w $INTERFACE ; then
      iptables -t nat -A POSTROUTING -o $INTERFACE -j MASQUERADE
      echo Added $INTERFACE  
    fi
    if [ -d VLAN ] ; then
       cd VLAN
       VLANS=`ls`
       for V in $VLANS ; do
         if  [ -d $V/NAT/Masquerade ] ; then
           if ! echo "$NATTED" | grep  -q -w "$INTERFACE.$V" ; then
             iptables -t nat -A POSTROUTING -o $INTERFACE.$V -j MASQUERADE
             echo Added  vlan $INTERFACE.$V
           fi
         fi
       done
    fi
  fi 
fi
