#!/bin/bash
. /etc/kerbynet.conf
SCRIPTNAME="$1"
OPT="$2"
[ -z "$SCRIPTNAME" ] && exit 
DIR=$REGISTER/system/startup/scripts
if cd $DIR/$SCRIPTNAME 2>/dev/null ; then
  DESCRIPTION="`cat Description 2> /dev/null`"
else
  DESCRIPTION=$SCRIPTNAME
fi

if [ "$OPT" = test ] ; then
  VIEW="cat"
  export SCRIPT=/tmp/ScriptToRun$$
  tr -d "\r" > $SCRIPT
  chmod 755 $SCRIPT
else
  VIEW="logger -t Scripts"
  export SCRIPT=./File
fi

if [ "`cat Enabled 2>/dev/null`" = yes -o "$OPT" = test ] ; then
  [ "$OPT" != test ] && echo  -n "[$DESCRIPTION]: Running ... " | $VIEW 
   [ "$OPT" != test ] && echo  -n "Script [$DESCRIPTION]: Running ... "
  [ "$OPT" = test ] && echo
  ( $SCRIPT 2>&1 ; echo $? >/tmp/StartupScriptError$$ ) | $VIEW 
  if [ "`cat /tmp/StartupScriptError$$`" = 0 ] ; then 
    RESULT=SUCCESS
  else
    RESULT="ERROR (`cat /tmp/StartupScriptError$$`)"
  fi
  rm -f /tmp/StartupScriptError$$
  [ "$OPT" = test ] && rm -f $SCRIPT
  [ "$OPT" != test ] && echo  $RESULT
  [ "$OPT" = test ] && echo
  echo  "[$DESCRIPTION]: $RESULT" | $VIEW 
else
  echo  "[$DESCRIPTION]: Disabled" | $VIEW  
fi

