#!/bin/sh
. /etc/kerbynet.conf
SCRIPTNAME="$1"
ENABLED="$2"
[ -z "$SCRIPTNAME" ] && SCRIPTNAME=postboot
DIR=$REGISTER/system/startup/scripts
cd $DIR/$SCRIPTNAME 2>/dev/null || exit 1
echo "$ENABLED" > Enabled 
tr -d '\r' > File
chmod 755 File


