#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
IDIR="$CONFIG/$INTERFACE"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
if ! [ -r "$IDIR/Bond/Name" ] ; then
   echo "Interface $INTERFACE is not bonded." 1>&2
   exit 3
else
   BOND=`cat $IDIR/Bond/Name`
   if [ "`cat $IDIR/dhclient/Status 2>/dev/null`" == Enabled ] ; then
     $SCRIPTS/set_dhclient $INTERFACE Release
   fi
   ip addr flush $INTERFACE 2>/dev/null
   removezombievlan $INTERFACE
   if [ "${INTERFACE:0:3}" = VPN ] ; then
     if ifconfig $INTERFACE 2>/dev/null |grep -w -q  UP ; then
       STATUS=up
     else
       STATUS=down
     fi
   else
     STATUS=`cat $IDIR/STATUS 2>/dev/null`
   fi

   ifconfig $INTERFACE $STATUS
   if ! [ -r "$CONFIG/$BOND/Bridge/Name" ] ; then
     if [ -d "$IDIR/IP" ] ; then
       cd "$IDIR/IP"
       IPs=`ls -d ?? 2>/dev/null`
       if [ -n "$IPs" ] ; then
         for I in $IPs ; do
           IP="`cat $I/IP 2>/dev/null`"
           if [ -z "`$SCRIPTS/getipdir $BOND $IP`" ] ; then
             NETMASK="`cat $I/Netmask 2>/dev/null`"
             STATUS="`cat $I/STATUS 2>/dev/null`"
             $SCRIPTS/addip $BOND "$IP" "$NETMASK" "$STATUS"
           fi
         done
       fi
     fi
   fi
fi
