#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACENAME="$1"
[ -z "$INTERFACENAME" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
VLAN=`echo $INTERFACENAME | awk -F. '{print $2}'`
INTERFACE=`echo $INTERFACENAME |cut -d. -f1`
IDIR="$CONFIG/$INTERFACE"
[ -n "$VLAN" ] && IDIR="$IDIR/VLAN/$VLAN"
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi




  if ! [ -z "$VLAN" ] ; then 
    if ! [ -d "$IDIR" ] ; then
       echo "VLAN $VLAN ($INTERFACE) doesn't exist." 1>&2
       exit 3
    fi
    if ! ifconfig $INTERFACE.$VLAN 2>/dev/null >/dev/null ; then
       ifconfig $INTERFACE up
       if ! vconfig add $INTERFACE $VLAN 2>/dev/null >/dev/null ; then
          echo "VLAN $VLAN ($INTERFACE) not created." 1>&2
          exit 4
       fi
    fi 
  else 
    if [ "${INTERFACE:0:6}" == BRIDGE ] ; then
      brctl addbr $INTERFACE 2>/dev/null
      $SCRIPTS/setbridge $INTERFACE

    fi
    if [ "${INTERFACE:0:4}" == BOND ] ; then
      #$SCRIPTS/setbond $INTERFACE 
      setallbondedinterface $INTERFACE
    fi
  fi
  if [ "${INTERFACENAME:0:3}" = VPN -a "$INTERFACENAME" != VPN99 ] ; then
    if ifconfig $INTERFACENAME 2>/dev/null |grep -w -q  UP ; then
      STATUS=up
    else
      STATUS=down
    fi
  else
    STATUS=`cat $IDIR/STATUS 2>/dev/null`
  fi
  ifconfig $INTERFACENAME $STATUS 2>/dev/null >/dev/null
if ! [ -r "$IDIR/Bridge/Name" -o -r "$IDIR/Bond/Name" ] ; then

  IPDIR="$IDIR/IP"
  if cd $IPDIR 2>/dev/null ; then
    ADDRESSES=`ls`
    for A in $ADDRESSES ; do
      IP=`cat $A/IP`
      NETMASK=`cat $A/Netmask 2>/dev/null`
      STATUSIP=`cat $A/STATUS 2>/dev/null`
      if [ -z "$VLAN" ] ; then
        echo -e "$INTERFACE: $IP/$NETMASK"
      else
        echo -e "$INTERFACE (vlan $VLAN): $IP/$NETMASK"
      fi
      ifconfig $INTERFACENAME up 
      ifconfig $INTERFACENAME:$A $IP netmask $NETMASK broadcast `getbroadcast $IP $NETMASK` $STATUSIP 2>/dev/null >/dev/null
    done    
  fi
  ifconfig $INTERFACENAME $STATUS 2>/dev/null >/dev/null
  killall -1 named 2>/dev/null
  if [ -z "$VLAN" -a "`cat $IDIR/dhclient/Status 2>/dev/null`" == Enabled ] ; then
    $SCRIPTS/set_dhclient $INTERFACE Enabled
  fi
fi
