#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
CONFIG="$REGISTER/system/net/interfaces/"
if echo $INTERFACE | grep -q '\.' ; then
  TAG=`echo $INTERFACE | awk -F. '{print $2}'`
  U=`echo $INTERFACE | awk -F. '{print $1}'`
  IDIR="$CONFIG/$U/VLAN/$TAG"
else
  IDIR="$CONFIG/$INTERFACE"
fi
if ! [ -d "$IDIR" ] ; then
   echo "Interface $INTERFACE doesn't exist." 1>&2
   exit 2
fi
if ! [ -r "$IDIR/Bridge/Name" ] ; then
   echo "Interface $INTERFACE is not bridged." 1>&2
   exit 3
else
   BRIDGE=`cat $IDIR/Bridge/Name`
   if [ "`cat $IDIR/dhclient/Status 2>/dev/null`" == Enabled ] ; then
     $SCRIPTS/set_dhclient $INTERFACE Release
   fi
   brctl addbr $BRIDGE 2>/dev/null
   ip addr flush $INTERFACE 2>/dev/null
   removezombievlan $INTERFACE
   STATUS=`cat $IDIR/STATUS 2>/dev/null`
   ifconfig $INTERFACE $STATUS
   $SCRIPTS/setpathcost $INTERFACE
   if [ "$GUICONFIGBR" = Yes ] ; then
     if [ -d "$IDIR/IP" ] ; then
       cd "$IDIR/IP"
       IPs=`ls -d ?? 2>/dev/null`
       if [ -n "$IPs" ] ; then
          for I in $IPs ; do
            IP="`cat $I/IP 2>/dev/null`" 
            if [ -z "`$SCRIPTS/getipdir $BRIDGE $IP`" ] ; then
               NETMASK="`cat $I/Netmask 2>/dev/null`"
               STATUS="`cat $I/STATUS 2>/dev/null`"
               $SCRIPTS/addip $BRIDGE "$IP" "$NETMASK" "$STATUS"
            fi
          done
       fi
     fi
   fi
fi
