#!/bin/sh
. /etc/kerbynet.conf
ENABLED="$1"
ACLs="$2"
mkdir -p $REGISTER/system/ssh/
echo "$ENABLED" > $REGISTER/system/ssh/Enabled
if ! [ -z "$ACLs" ] ; then
  echo "$ACLs" | tr " " "\n" >$REGISTER/system/ssh/ACL
else
  echo -n > $REGISTER/system/ssh/ACL
fi
$SCRIPTS/fw_ssh_chain
