#!/bin/bash
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/cp/Auth/Shibboleth/
rm -rf $CONFIG/packages/tmp
mkdir -p $CONFIG/packages/tmp
cd $CONFIG/packages/tmp

if uudecode -o - |bzip2 -dc | tar x ; then
  GOOD=TRUE
  if ! [ -f opt/shibboleth-sp/Release/BUILD ] ; then
    GOOD=FALSE 
  fi
  if ! [ -f usr/local/shibboleth-sp/sbin/shibd ] ; then
    GOOD=FALSE 
  fi
  if [ "$GOOD" = TRUE ] ; then
    rm -rf $CONFIG/packages/last
    mv $CONFIG/packages/tmp $CONFIG/packages/last
    LAST=`ls -rtd /usr/local/shibboleth-sp/ /var/register/system/cp/Auth/Shibboleth/packages/last/ |tail -1`
    ln -sf "$LAST/usr/local/shibboleth-sp" /opt
    $SCRIPTS/cp_auth_start
    exit 0
  else
    rm -rf $CONFIG/packages/tmp
    exit 2
  fi
else
  rm -rf $CONFIG/packages/tmp
  exit 1
fi
