#!/bin/sh
function TERM () {
  I=0
  ps -e |grep -w -q slapd || return 0
  while [ $I -lt 30 ] ; do
    if ps -e |grep -w -q slapd ; then
      killall -TERM slapd 2> /dev/null
    else
       return 0
    fi
    I=$((I+1))
    if [ $I -gt 15 ] ; then 
      sleep 1
    fi
  done
  return 1
}
. /etc/kerbynet.conf
TERM
$SCRIPTS/rendertemplate slapd.conf


if [ "`cat $REGISTER/system/ldap/LDAPACTIVE 2>/dev/null`" == yes ] ; then
  BIND=""
else
  BIND=127.0.0.1
fi
if [ "`cat $REGISTER/system/ldap/LDAPSACTIVE 2>/dev/null`" == yes ] ; then
  /usr/local/libexec/slapd -4 -h "ldap://$BIND ldaps://"
else
  /usr/local/libexec/slapd -4 -h "ldap://$BIND"
fi
$SCRIPTS/dns_start NOCONFIG
