#!/bin/bash
. /etc/kerbynet.conf
SLOT="$1"
if [ -d /etc/slots ] ; then
  cd /etc/slots
  DESC="`cat $SLOT/conf/Description 2>/dev/null`"
  if [ -n "$DESC" ] ; then
    echo "$DESC"
  else
    echo Empty
  fi
else 
  echo "Not available"
fi
