#!/bin/bash
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/alerts/
SPOOLER=$CONFIG/Spooler
QUEUE=$SPOOLER/Queue
cd "$QUEUE" 2>/dev/null || exit 3
echo -n "Waiting for e-Mail and SMS spooling operations to terminate "
for TRY in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ; do
  echo -n .
  MESSAGES="`ls -d * 2>/dev/null`" 
  if [ -z "$MESSAGES" ] ; then
    break
  fi
  sleep 1   
done
echo
