#!/bin/bash
. /etc/kerbynet.conf
CONFIG=$REGISTER/system/alerts/
SPOOLER=$CONFIG/Spooler
QUEUE=$SPOOLER/Queue
cd "$QUEUE"
MAXAGE="`cat $SPOOLER/MaxAge`"
RETRY="`cat $SPOOLER/Retry`"
SMSTSD="/tmp/smstsd"
RATELIMIT="`cat $CONFIG/SMS/SMSRateLimit`"
[ -z "$RATELIMIT" ] && RATELIMIT=1000
mkdir -p "$SMSTSD"
while true; do
 for TRY in 1 2 3 ; do
  MESSAGES="`ls -d * 2>/dev/null`"    
  for M in $MESSAGES ; do
    TS="${M:2:10}"
    SEVERITY="`echo $M | awk -F_ '{print $3}'`" 
    SUBJECT="`cat $M/Subject 2>/dev/null`" 
    TYPE="`cat $M/Type 2>/dev/null`" 
    MRECIPIENT="`cat $M/Recipient 2>/dev/null`"
    if [ "$TYPE" = Recipient ] ; then
      TYPE="`cat $CONFIG/Recipients/$MRECIPIENT/Type`"
    fi
    ID="`echo $M | awk -F_ '{print $4}'`" 
    EVENT="`echo $M | awk -F_ '{print $5}'`" 
    NOW=`date +%s`
    if [ $((NOW-TS)) -gt $MAXAGE ] ; then
      $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): message expired."
      rm -rf $M
    else
      FAULT=0
      SENT="`cat $M/Sent 2>/dev/null`"
      if [ "`cat $REGISTER/system/alerts/SMS/SMSEnabled`" = yes -a "$TYPE" != "e-Mail" ] ; then
        find "$SMSTSD" -ctime +1 -exec rm {} \;
        if [ -n "$MRECIPIENT" ] ; then
	  RECIPIENTS="$MRECIPIENT"
	else
          RECIPIENTS="`$SCRIPTS/alerts_smsrecipient $SEVERITY`"
        fi
	if [ -z "$RECIPIENTS" ] ; then
	  $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): No SMS Recipients available for $SEVERITY severity"
	fi
        for R in $RECIPIENTS ; do
          RECIPIENT="`cat $CONFIG/Recipients/$R/Recipient`"
          RECIPIENT_DESC="`cat $CONFIG/Recipients/$R/Description`"
          if ! echo $SENT  |grep -q -w "$RECIPIENT" 2>/dev/null ; then
             DAYLYSMS=`ls $SMSTSD/* 2>/dev/null | wc -l |awk '{print $1}'`
	     if [ $DAYLYSMS -le $RATELIMIT ] ; then
               MSG="`awk -F: '{printf(\"%s:%s\n%s\n%s\",$1,$2,$3,$4)}' < $M/Subject`\n\n`grep "^HEADER:_:" $M/Body | awk -F":_:" '{print $2}'`\n\n`grep "^SMS:_:" $M/Body | awk -F":_:" '{print $2}'`"
	       MSG="${MSG:0:160}"
               if echo -e "$MSG" | $SCRIPTS/sendsms "$RECIPIENT" 2>/tmp/sms.error.$$ ; then
                 touch "$SMSTSD/$ID"
                 SENT="$SENT $RECIPIENT"
                 $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): SMS sent to $RECIPIENT_DESC ($RECIPIENT)"
               else 
                 FAULT=$((FAULT+1))
                 $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): SMS delivery FAULT for $RECIPIENT_DESC ($RECIPIENT)"
                 awk -vID=$ID '{printf("[%s]:::%s\n",ID,$0)}' < /tmp/sms.error.$$ >> /tmp/spooler_log
               fi
               rm -f /tmp/sms.error.$$
	     else
               FAULT=$((FAULT+1))
               $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): SMS not delivered to $RECIPIENT_DESC ($RECIPIENT): Rate Limit reached"
             fi
          fi
        done
      fi
      if [ "`cat $REGISTER/system/alerts/EMAIL/SMTPEnabled`" = yes -a "$TYPE" != "SMS" ] ; then
        if [ -n "$MRECIPIENT" ] ; then
          RECIPIENTS="$MRECIPIENT"
        else
          RECIPIENTS="`$SCRIPTS/alerts_mailrecipient $SEVERITY`"
	fi
	if [ -z "$RECIPIENTS" ] ; then
	  $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): No e-Mail Recipients available for $SEVERITY severity"
	fi
        for R in $RECIPIENTS ; do
          RECIPIENT="`cat $CONFIG/Recipients/$R/Recipient`"
          RECIPIENT_DESC="`cat $CONFIG/Recipients/$R/Description`"
          if ! echo $SENT | grep -q -w "$RECIPIENT" 2>/dev/null ; then
             if ( grep "^HEADER:_:" "$M/Body" | awk -F":_:" '{print $2}' ; echo ; grep "^MAIL:_:" "$M/Body" | awk -F":_:" '{print $2}' ) | $SCRIPTS/sendmail "$RECIPIENT" "$SUBJECT" 2>/tmp/sendmail.error.$$ ; then
               SENT="$SENT $RECIPIENT"
               $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): e-Mail sent to $RECIPIENT_DESC ($RECIPIENT)"
             else 
               FAULT=$((FAULT+1))
               $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): e-Mail delivery FAULT for $RECIPIENT_DESC ($RECIPIENT)"
	       awk -vID=$ID '{printf("[%s]:::%s\n",ID,$0)}' < /tmp/sendmail.error.$$ >> /tmp/spooler_log
             fi
             rm -f /tmp/sendmail.error.$$
          fi
        done
      fi
      if [ $FAULT -eq 0 ] ; then
        rm -rf $M/
        $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): Removed from the queue"
      else 
        echo "$SENT" > $M/Sent
        $SCRIPTS/alerts_logger "$ID" "$EVENT ($SEVERITY): Waiting to be reprocessed"
      fi 

    fi
  done
 done
 sleep $RETRY.23215
done
