#!/bin/sh
. /etc/kerbynet.conf
ENABLED=`cat $REGISTER/system/ssh/Enabled 2>/dev/null`

if [ "$ENABLED" == yes ] ; then
  if ! ps -ef | grep -q -w "/usr/local/sbin/sshd$" ; then
    /usr/local/sbin/sshd
  fi
else
  killall sshd 2>/dev/null
fi




