#!/bin/sh
. /etc/kerbynet.conf
TLSconfig="$REGISTER/$1"
CertType="$2"
CertSelected="$3"
[ -z "$CertType" ] && CertType=`cat $TLSconfig/CertType`
[ -z "$CertSelected" ] && CertSelected=`cat $TLSconfig/CertSelected`
if [ "$CertType" == Local ] ; then
  cd "$SSLDIR/certs" || exit 1
  if [ "$CertSelected" != ".default.pem" ] ; then
    PEMFILE="${CertSelected}_host.pem"
  else
    PEMFILE=".default.pem"
  fi
  CHECKCRL="-crl_check"
fi
if [ "$CertType" == Imported ] ; then
  cd "$SSLDIR/certs/imported_Certs/" || exit 1
  PEMFILE="${CertSelected}.pem"
  CHECKCRL=""
  STATUS=`openssl verify -CApath "$SSLDIR/certs/trusted_CAs/"  "$PEMFILE" 2>&1 |grep : |tail -1 | awk -F: '{print $2}'`
fi
if [ "$CertType" == ThisHost ] ; then
  cd "$SSLDIR/certs/ThisHost" || exit 1
  PEMFILE="/etc/ssl/certs/ThisHost/cert.pem"
  CHECKCRL=""

fi
STATUS=`openssl verify -CApath "$SSLDIR/certs/trusted_CAs/" $CHECKCRL "$PEMFILE" 2>&1 |grep : |tail -1 | awk -F: '{print $2}'`
if [ "$STATUS" == " OK" ] ; then
   echo "<font color=#00C000 class=Bigger1>$STATUS</font>"
else
   [ "$STATUS" == "error" ] && STATUS="Certificate not selected"
   echo "<font color=#FF0000 class=Bigger1>$STATUS</font>"
fi
