#!/bin/sh
. /etc/kerbynet.conf
function PrintIP {
  NOIP=""
  if [ "$MODE" != TXT ] ; then
    echo "<td align=center>"
  fi
  if pushd IP 2>/dev/null >/dev/null; then
    IPs=`ls -d ?? 2>/dev/null`
    for ip in $IPs ; do
      if [ "`cat $ip/STATUS 2>/dev/null`" == up  ] ; then
        if [ "$MODE" != TXT ] ; then
          echo "`cat $ip/IP`/`cat $ip/Netmask`<br>"
        else 
          echo -n "`cat $ip/IP`/`cat $ip/Netmask` "
        fi
        NOIP=false
      fi
    done
    popd >/dev/null
  fi
  if [ -z "$NOIP" ] ; then
    if [ "$MODE" != TXT ] ; then
      echo "Not configured"
    else
      echo -n "not configured "
    fi
  fi
  if [ "$MODE" != TXT ] ; then
    echo "</td>"
  else
    echo
  fi
}
function PrintVLAN {
  if pushd VLAN 2>/dev/null >/dev/null; then
    VLANs=`ls -d * 2>/dev/null`
    for vlan in $VLANs ; do
      if [ "`cat $vlan/STATUS 2>/dev/null`" == up  ] ; then
        pushd $vlan >/dev/null
        if [ "$MODE" != TXT ] ; then
          echo "<tr><td align=center>$I</td><td align=center>$vlan</td>"
        else
          echo -n "  $I vlan $vlan "
        fi
        PrintIP
        if [ "$MODE" != TXT ] ; then
          echo "</tr>"
        else
          :  
        fi
        popd >/dev/null
      fi
    done
    popd >/dev/null
  fi
}
STk="`rand``cat /tmp/STk_Admin 2>/dev/null`"
Disk="$1"
Part="$2"
DB="$3"
MODE="$4"
SOURCE="/storage/INFO/DISK/$Disk/PART/$Part/DB/$DB"
CONFIG="$SOURCE/interfaces"
cd $CONFIG
INTERFACES=`ls -d * 2>/dev/null`
if [ "$MODE" != TXT ] ; then
  if [ "`$SCRIPTS/getactivedb`" == "`echo $Part |tr _ /`:$DB" ] ; then
    ACTIVE=true
  else 
    ACTIVE=false
  fi
  cat << EOF
<html>
<head><link rel=stylesheet type=text/css href=/default.css>
<title>NetDB</title>
<script>
  Active=$ACTIVE;
</script>
</head>
<body>
<table width=100%><tr><td><hr></td><td width=1%><input type=button value="Info" onclick="location='kerbynet?Section=Storage&STk=$STk&Action=InfoDB&Part=$Part&DB=$DB&Disk=$Disk'"></td></tr></table>
<table width=100%><tr><td>
<table width=100% style="color: #404040" cellpadding=0 cellspacing=0 border=1>
<tr bgcolor=#e0e0ff style='color:#3030d0'><th> Interface</th><th>VLAN</th><th>IP/Netmask</th></tr>
EOF
fi
for I in $INTERFACES ; do
  if [ "`cat $I/STATUS 2>/dev/null`" == up ] ; then
    pushd $I >/dev/null
    if [ "$MODE" != TXT ] ; then
      echo "<tr>"
      echo "<td align=center>$I</td>"
      echo "<td align=center>Default</td>"
    else
      echo -n "  $I "
    fi 
    if [ -r Bridge/Name ] ; then
      if [ "$MODE" != TXT ] ; then
        echo "<td align=center>Member of `cat Bridge/Name`</td>"
      else
        echo " member of `cat Bridge/Name` "
      fi
    else
      if [ -r Bond/Name ] ; then
        if [ "$MODE" != TXT ] ; then
          echo "<td align=center>Member of `cat Bond/Name`</td>"
        else
          echo " member of `cat Bond/Name` "
        fi
      else
        PrintIP
        if [ "$MODE" != TXT ] ; then
          echo "</tr>"
        else
           :
        fi
        PrintVLAN
      fi
    fi 
    popd >/dev/null
  fi
done
if [ "$MODE" != TXT ] ; then
  echo "</table></td><td align=center valign=top><br>"
else
 : 
fi
GW=`$SCRIPTS/getdefaultgw "$SOURCE"|awk '{print $1}'`
[ -z "$GW" ] && GW="not configured"
if [ "$MODE" != TXT ] ; then
  echo "<font color=#3030d0><b>Default Gateway</b></font><br>$GW</font>"
  echo "</td></tr></table></body></html>"
else
  echo "  Default Gateway $GW" 
fi
