#!/bin/sh
. /etc/kerbynet.conf
KERNEL=`uname -r`
CPU=`grep "model name" /proc/cpuinfo |head -1 | cut -d: -f2`
MHZ=`grep "cpu MHz" /proc/cpuinfo | cut -d: -f2 | head -1 | cut -d. -f1` 
NCPU=`$SCRIPTS/cpus`
MEMORY=`grep "MemTotal" /proc/meminfo |cut -d: -f2`
MFREE=$($SCRIPTS/../api/MEMINFO |awk '{print $5}' | sed -r 's/.(.*)../\1/')
MUSED=$((100-MFREE))
UPTIME=`awk '{Days=$1/86400; Sec=$1%86400; Hours=Sec/3600; Sec=Sec%3600 ; Minutes=Sec/60; printf "%d days, %d:%d",Days,Hours,Minutes }' < /proc/uptime`

echo "<tr><td class=Smaller2 nowrap>CPU ($NCPU)</td><td class=Smaller2 style='color:#2020F0'><b>$CPU${MHZ}MHz</b></td><td width=1% class=Smaller2 align=right><a href=# onclick='newwin=open(\"kerbynet?STk=<xvar STk>&Action=Render&Object=cpu_details\", \"CPUDetails\",\"top=300,left=400,width=600,height=400,scrollbars=no,menubar=no,toolbar=no,statusbar=no\");newwin.focus();'>Details</a></td></tr>"
echo "<tr><td class=Smaller2 nowrap>Kernel</td><td class=Smaller2>$KERNEL</td><td></td></tr>"
echo "<tr><td class=Smaller2 nowrap>Memory&nbsp;&nbsp;</td><td class=Smaller2>$MEMORY&nbsp;&nbsp;($MUSED% used)</td><td class=Smaller2 align=right><a href=# onclick='newwin=open(\"kerbynet?STk=<xvar STk>&Action=Render&Object=mrtg_show&Type=System\", \"MRTG\",\"top=200,left=200,width=800,height=480,scrollbars=yes,menubar=no,toolbar=no,statusbar=no\");newwin.focus();'>Graphics</a></td></tr>"
echo "<tr><td class=Smaller2 nowrap>Uptime</td><td class=Smaller2>$UPTIME</td><td class=Smaller2></td></tr>"
echo "<script>"
echo "top.sommario.document.getElementById('AlertsMsg').innerHTML=\"`$SCRIPTS/alerts_status_sx`\"";
echo "</script>"
