#!/bin/bash
PROCESSNAME="$1"
RETRY="$2"
[ -z "$PROCESSNAME" ] && exit 1
[ -z "$RETRY" ] && RETRY=10
I=0
while [ $I -lt $RETRY -a -n "`pidof $PROCESSNAME`" ] ; do
  killall $PROCESSNAME 2>/dev/null
  sleep 0.5
  I=$((I+1)) 
done
I=0
while [ $I -lt $RETRY -a -n "`pidof $PROCESSNAME`" ] ; do
  killall -9 $PROCESSNAME 2>/dev/null
  sleep 0.5
  I=$((I+1)) 
done
if [ -z "`pidof $PROCESSNAME`" ] ; then
  exit 0
else
  exit 2
fi
