#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc
HOST="$1"
[ -z "$HOST" ] && exit 1
IP="`gethostbyname $HOST`"
if ! [ -z "$IP" ] ; then 
    if ! tracepath -n $IP ; then
      exit 2
    fi
else
    exit 5
fi
