#!/bin/sh
. /etc/kerbynet.conf
cd $REGISTER/system/openvpn/Auth/X509/ || exit 1

: > CAFile
CAs=`ls CAs/*.0 2>/dev/null`
for CA in $CAs ; do
  if [ -r "$CA" ] ; then
    cat $CA >> CAFile
  else
    rm -f $CA
  fi  
done
if ! openssl x509 -in CAFile -noout 2>/dev/null2>/dev/null ; then
  cp FakeCA.pem CAFile 
fi
: > CRLFile
CRLs=`ls CAs/*.r0 2>/dev/null`
for CRL in $CRLs ; do
  if [ -r "$CRL" ] ; then
    cat $CRL >> CRLFile
  else
    rm -f $CRL
  fi
done
