#!/bin/sh
. /etc/kerbynet.conf
export INTERFACE="$1"
[ -z "$INTERFACE" ] && exit 1
if [ "$INTERFACE" == VPN99 ] ; then
  exit
fi
export SEM="/tmp/VPN_MII_$INTERFACE"
export PATH="$PATH:/usr/local/bin:/usr/local/sbin:/usr/local/ssl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin/:/usr/local/sbin/"
[ -f $SEM ] && exit 0
echo  > $SEM
(
CONFIG="$REGISTER/system/net/interfaces/$INTERFACE"
if ! cd "$CONFIG" 2> /dev/null ; then
  rm -f $SEM
  exit
fi
NUM=${INTERFACE:3:2}
if [ "${NUM:0:1}" == 0  ] ; then
   NUM=${NUM:1:1}
fi
MGT=$[34000+$NUM]
DOWN=""
while ps -ef |grep -w openvpn |grep -w -q $INTERFACE ; do
  STATUS=`cat $CONFIG/STATUS 2>/dev/null`
  if [ "$STATUS" = up ] ; then
    if   echo state | nc -w1 127.0.0.1 $MGT 2>/dev/null | grep -q "CONNECTED" ; then
      /sbin/ifconfig $INTERFACE up
      $SCRIPTS/routerconfig >/dev/null
      logger -t ${INTERFACE}_L2L "Interface $INTERFACE is UP"
      rm -f $SEM
      $SCRIPTS/alert VPNFAULT $INTERFACE UP >/dev/null &
      exit
    else
      if [ -z "$DOWN" ] ; then
        /sbin/ifconfig $INTERFACE down
        DOWN=yes
        logger -t ${INTERFACE}_L2L "Interface $INTERFACE is DOWN"
        $SCRIPTS/alert VPNFAULT $INTERFACE DOWN >/dev/null &
      fi
    fi
  else
    rm -f $SEM
    exit
  fi
  sleep 2
done

) &
