#!/bin/sh
. /etc/kerbynet.conf
export PATH=$PATH:/usr/local/ssl/bin
NBIT=`cat $REGISTER/system/ssl/ca/keysize 2>/dev/null`
DAYS=`cat $REGISTER/system/ssl/ca/days 2>/dev/null`
[ -z "$NBIT" ] && NBIT=2048
[ -z "$DAYS" ] && DAYS=730
openssl req -new -batch -newkey rsa:$NBIT -nodes -out /tmp/x509default.req -keyout /tmp/x509default.key -days $DAYS -sha512 -subj "/OU=Hosts/CN=$HOSTNAME"
TMP=/tmp/x509_extfile_defaulthost
cat $SSLDIR/extensions > $TMP
echo -n "subjectAltName = DNS:`hostname`" >> $TMP
find /var/register/system/net/interfaces/ -name IP  -type f -exec awk '{printf(", IP:%s",$0)}' {} \; >> $TMP
echo >> $TMP
openssl ca  -batch -days $DAYS -in /tmp/x509default.req -out /tmp/x509default.cert -extfile $TMP -extensions host
rm -f $TMP
openssl x509 -in /tmp/x509default.cert -out "$SSLDIR/certs/${HOSTNAME}_host.pem"
mv /tmp/x509default.key "$SSLDIR/private/${HOSTNAME}_host.pem"
$SCRIPTS/onlyRootRW "$SSLDIR/private/${HOSTNAME}_host.pem"
ln -sf "$SSLDIR/certs/${HOSTNAME}_host.pem" "$SSLDIR/certs/.default.pem"
ln -sf "$SSLDIR/private/${HOSTNAME}_host.pem" "$SSLDIR/private/.default.pem"
rm -f /tmp/x509default.req /tmp/x509default.cert





