#!/bin/sh
source /etc/kerbynet.conf
$SCRIPTS/x509_reset

echo 0001 > $SSLDIR/serial
O=`echo $HOSTNAME | awk -F. '{print $2}'`
RAND=`rand`
RAND=${RAND:0:4}
OU="`echo $HOSTNAME | awk -F. '{print $1}'` $RAND"
SUBJECT="/O=$O/OU=$OU/CN=ZeroShell"

if openssl req -new -x509 -batch -newkey rsa:2048 -nodes -set_serial 0 -out /tmp/reqout.pem -keyout /tmp/keyout.pem -days 3650 -subj "$SUBJECT" ; then
  mv /tmp/reqout.pem /etc/ssl/certs/cacert.pem
  mv /tmp/keyout.pem /etc/ssl/private/cakey.pem
  openssl ca -gencrl -out /etc/ssl/certs/crl.pem
  $SCRIPTS/c_rehashCA
  echo 2048 > $REGISTER/system/ssl/ca/keysize
  echo 730 > $REGISTER/system/ssl/ca/days
fi

